'use client';
import { useState } from 'react';
import { CheckCircle2, CircleAlert, Clock3, Loader2, Ban } from 'lucide-react';

type Node={id:string;title:string;status:string;selectedModel?:string;qualityScore?:number;costCents?:number;tokensIn?:number;tokensOut?:number;dependencies:string[];output?:string;error?:string};
type Props={graph:{id:string;goal:string;status?:string;nodes:Node[]}};
const icons:any={completed:CheckCircle2,running:Loader2,failed:CircleAlert,blocked:Ban,pending:Clock3,ready:Clock3};

export default function TaskGraphView({graph}:Props){
 const [selected,setSelected]=useState(graph.nodes[0]?.id); const node=graph.nodes.find(n=>n.id===selected); const cost=graph.nodes.reduce((s,n)=>s+(n.costCents||0),0); const tokens=graph.nodes.reduce((s,n)=>s+(n.tokensIn||0)+(n.tokensOut||0),0);
 return <div className="space-y-6"><div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Metric label="Status" value={graph.status||'unknown'}/><Metric label="Nodes" value={String(graph.nodes.length)}/><Metric label="Cost" value={`$${(cost/100).toFixed(4)}`}/><Metric label="Tokens" value={tokens.toLocaleString()}/></div><div className="glass-card border border-[var(--border-color)] p-5 overflow-x-auto"><div className="flex gap-4 min-w-max">{graph.nodes.map(n=><button key={n.id} onClick={()=>setSelected(n.id)} className={`w-64 text-left rounded-xl border p-4 ${selected===n.id?'border-[var(--accent-primary)]':'border-[var(--border-color)]'}`}><div className="flex justify-between"><span className="font-mono text-xs text-[var(--text-muted)]">{n.id}</span><Status status={n.status}/></div><div className="font-semibold mt-2 text-[var(--text-primary)]">{n.title}</div><div className="text-xs mt-2 text-[var(--text-secondary)]">{n.selectedModel||'Model pending'}</div><div className="text-xs mt-1 text-[var(--text-muted)]">{n.qualityScore!=null?`${n.qualityScore}/100`: 'Quality pending'} · ${((n.costCents||0)/100).toFixed(4)}</div>{n.dependencies.length>0&&<div className="text-xs mt-2 text-[var(--text-muted)]">Depends on: {n.dependencies.join(', ')}</div>}</button>)}</div></div>{node&&<div className="glass-card border border-[var(--border-color)] p-6"><div className="flex justify-between"><div><h3 className="font-bold text-lg text-[var(--text-primary)]">{node.title}</h3><div className="font-mono text-xs text-[var(--text-muted)] mt-1">{node.id}</div></div><Status status={node.status}/></div><div className="grid md:grid-cols-3 gap-4 mt-5"><Metric label="Model" value={node.selectedModel||'—'}/><Metric label="Quality" value={node.qualityScore!=null?`${node.qualityScore}/100`:'—'}/><Metric label="Attempts" value={String((node as any).attemptedModels?.length||1)}/></div>{node.error&&<div className="mt-4 p-3 rounded-lg border border-red-500/30 text-red-400 text-sm">{node.error}</div>}{node.output&&<pre className="mt-4 max-h-80 overflow-auto whitespace-pre-wrap bg-[var(--bg-secondary)] p-4 rounded-lg text-sm text-[var(--text-secondary)]">{node.output}</pre>}</div>}</div>;
}
function Status({status}:{status:string}){const I=icons[status]||Clock3;return <I size={17} className="text-[var(--accent-primary)]"/>}
function Metric({label,value}:{label:string;value:string}){return <div className="glass-card border border-[var(--border-color)] p-3"><div className="text-xs text-[var(--text-muted)]">{label}</div><div className="text-sm font-semibold mt-1 text-[var(--text-primary)]">{value}</div></div>}
