'use client';
import { useMemo, useState } from 'react';
import { useSession } from 'next-auth/react';
import { useRouter } from 'next/navigation';
import { ArrowRight, ShieldCheck, Sparkles, CheckCircle2, Info, LockKeyhole } from 'lucide-react';
import { api, TaskMode } from '@/lib/api';

const examples = [
  { label:'Risk review', value:'Analyze this project, identify the highest-risk issues, and propose fixes I can review before anything changes.' },
  { label:'Hardening plan', value:'Review the current architecture and produce a prioritized plan for the next production-hardening pass.' },
  { label:'Failure investigation', value:'Investigate this failure, trace the likely cause, and give me a verified remediation path.' }
];

export default function NewTaskPage(){
 const {data:session}=useSession();const router=useRouter();const apiKey=(session as any)?.apiKey as string|undefined;const [prompt,setPrompt]=useState('');const [mode,setMode]=useState<TaskMode>('permission-based');const [creating,setCreating]=useState(false);const [error,setError]=useState<string|null>(null);
 const words=useMemo(()=>prompt.trim()?prompt.trim().split(/\s+/).length:0,[prompt]);
 async function handleSubmit(event:React.FormEvent){event.preventDefault();const value=prompt.trim();if(!value||!apiKey||creating)return;setCreating(true);setError(null);try{const task=await api.createTask(value,mode,undefined,apiKey);router.push(`/tasks/${task.id}`);}catch(err){setError(err instanceof Error?err.message:'Unable to start this work.');setCreating(false);}}
 return <div className="max-w-6xl space-y-6 md:space-y-7 pb-28 md:pb-10">
  <header><p className="text-sm text-[var(--accent-primary)] flex items-center gap-2"><Sparkles size={15}/> Workbench</p><h1 className="text-2xl md:text-3xl font-semibold text-[var(--text-primary)] mt-2">Start with the outcome</h1><p className="text-sm text-[var(--text-secondary)] mt-1 max-w-2xl leading-6">Tell Uden what needs to be true when the work is finished. Include context and constraints when they change what a correct result means.</p></header>
  <div className="grid grid-cols-1 lg:grid-cols-[1.6fr_1fr] gap-5 md:gap-6">
   <form onSubmit={handleSubmit} className="glass-card p-4 md:p-6 border border-[var(--border-color)] shadow-[var(--shadow-glow)] space-y-5">
    <div className="space-y-2"><div className="flex items-center justify-between gap-3"><label htmlFor="task-prompt" className="text-sm font-medium text-[var(--text-primary)]">What should Uden accomplish?</label><span className="text-[10px] uppercase tracking-wider text-[var(--text-muted)]">{words} words</span></div><textarea id="task-prompt" value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){e.preventDefault();e.currentTarget.form?.requestSubmit();}}} autoFocus rows={10} className="w-full resize-y min-h-56 md:min-h-64 rounded-xl border border-[var(--border-color)] bg-[var(--bg-secondary)] p-4 text-[var(--text-primary)] placeholder:text-[var(--text-muted)] outline-none focus:border-[var(--accent-primary)] transition-colors leading-6" placeholder="Outcome: what should be true?\nContext: what should Uden know?\nConstraints: what must it not do, or what matters most?"/><div className="flex flex-wrap gap-2 pt-1">{examples.map(example=><button key={example.label} type="button" onClick={()=>setPrompt(example.value)} className="text-left rounded-lg border border-[var(--border-color)] bg-[var(--bg-secondary)] px-3 py-2 text-xs text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:border-[var(--accent-primary)] transition-colors">{example.label}</button>)}</div></div>
    <div className="rounded-xl border border-[var(--border-color)] bg-[var(--bg-secondary)] p-3.5"><div className="flex items-start gap-3"><ShieldCheck size={17} className="mt-0.5 text-[var(--accent-primary)] shrink-0"/><div className="min-w-0 flex-1"><p className="text-sm font-medium text-[var(--text-primary)]">Execution mode</p><p className="text-xs text-[var(--text-secondary)] mt-1">This changes where the durable execution system can pause for human intervention.</p><div className="grid sm:grid-cols-2 gap-2 mt-3">{(['permission-based','permissionless'] as TaskMode[]).map(option=><button key={option} type="button" onClick={()=>setMode(option)} className={`text-left rounded-lg border p-3 ${mode===option?'border-[var(--accent-primary)] bg-[var(--accent-primary)]/10':'border-[var(--border-color)] bg-[var(--bg-card)]'}`}><span className="block text-xs font-semibold text-[var(--text-primary)]">{option==='permission-based'?'Approval-gated':'Permissionless'}</span><span className="block text-[11px] text-[var(--text-muted)] mt-1">{option==='permission-based'?'Pause before high-risk actions.':'Run policy-compliant actions without that approval gate.'}</span></button>)}</div></div></div>
    {!apiKey&&<p className="text-sm text-[var(--text-secondary)]">Sign in to start work. The task is created through the authenticated workspace API.</p>}{error&&<div role="alert" className="rounded-lg border border-red-400/30 bg-red-400/5 p-3 text-sm text-red-200">{error}</div>}
    <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3"><p className="text-[11px] text-[var(--text-muted)]">⌘/Ctrl + Enter starts work</p><button type="submit" disabled={!prompt.trim()||!apiKey||creating} className="btn btn-primary min-h-12 flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed">{creating?'Creating durable task…':<>Start work <ArrowRight size={17}/></>}</button></div>
   </form>
   <aside className="space-y-4"><div className="glass-card p-4 md:p-5 border border-[var(--border-color)]"><h2 className="font-semibold text-[var(--text-primary)]">Before execution</h2><ul className="mt-4 space-y-3 text-sm text-[var(--text-secondary)]"><li className="flex gap-2"><CheckCircle2 size={16} className="text-[var(--accent-primary)] shrink-0/>The requested outcome is recorded.</li><li className="flex gap-2"><CheckCircle2 size={16} className="text-[var(--accent-primary)]/>Execution state and decisions are durable.</li><li className="flex gap-2"><CheckCircle2 size={16} className="text-[var(--accent-primary)]/>Attempts, cost, and verification remain inspectable.</li></ul></div>
    <div className="glass-card p-4 md:p-5 border border-[var(--border-color)]"><div className="flex items-center gap-2"><LockKeyhole size={16} className="text-[var(--accent-primary)]"/><h2 className="font-semibold text-[var(--text-primary)]">Execution boundary</h2></div><p className="text-sm text-[var(--text-secondary)] mt-2 leading-6">Approval is an execution-system state transition. Permissionless does not bypass policy, capability, budget, or runtime controls.</p></div>
    <div className="glass-card p-4 md:p-5 border border-[var(--border-color)]"><div className="flex items-center gap-2"><Info size={16} className="text-[var(--accent-primary)]"/><h2 className="font-semibold text-[var(--text-primary)]">After you start</h2></div><ol className="mt-3 space-y-3 text-sm text-[var(--text-secondary)]"><li><b className="text-[var(--text-primary)]">1. Plan</b> — classify and decompose when needed.</li><li><b className="text-[var(--text-primary)]">2. Route</b> — select a model tier for each unit.</li><li><b className="text-[var(--text-primary)]">3. Execute</b> — real provider/runtime actions follow policy.</li><li><b className="text-[var(--text-primary)]">4. Verify</b> — preserve the durable trail.</li></ol></div></aside>
  </div>
 </div>;
}
