'use client';

import { useParams } from 'next/navigation';
import { ArrowLeft, CheckCircle, BrainCircuit, DollarSign, Radio, ShieldCheck, Workflow, Circle, AlertTriangle, RotateCw, Clock3, Info } from 'lucide-react';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import StatusBadge from '@/components/ui/StatusBadge';
import ModelPill from '@/components/ui/ModelPill';
import QualityScore from '@/components/ui/QualityScore';
import ExecutionTruth from '@/components/ui/ExecutionTruth';
import { formatCurrency, formatDate } from '@/lib/utils';
import { api, Task } from '@/lib/api';
import { Skeleton } from '@/components/ui/LoadingSkeleton';

const terminalStatuses = new Set(['completed', 'failed', 'rejected']);
const lifecycle = [
  { key: 'queued', label: 'Queued', detail: 'Recorded and waiting' },
  { key: 'running', label: 'Executing', detail: 'Work is running' },
  { key: 'completed', label: 'Verified', detail: 'Outcome recorded' },
];
function lifecycleIndex(status: string) { if(status==='completed')return 2;if(status==='failed'||status==='rejected')return -1;if(status==='awaiting-approval')return 0;if(status==='running')return 1;return 0; }

export default function TaskDetail() {
  const { id } = useParams<{ id: string }>();
  const [task,setTask]=useState<Task|null>(null); const [error,setError]=useState<string|null>(null); const [approving,setApproving]=useState(false); const [refreshing,setRefreshing]=useState(false);
  async function loadTask(silent=false){if(!id)return;if(!silent)setRefreshing(true);try{setTask(await api.getTask(id));setError(null);}catch(err){setError(err instanceof Error?err.message:'Failed to load task');}finally{if(!silent)setRefreshing(false);}}
  useEffect(()=>{void loadTask();},[id]);
  useEffect(()=>{if(!task||terminalStatuses.has(task.status)||task.status==='awaiting-approval')return;const timer=window.setInterval(()=>void loadTask(true),5000);return()=>window.clearInterval(timer);},[id,task?.status]);
  const approve=async()=>{if(!task)return;setApproving(true);setError(null);try{setTask(await api.approveTask(task.id));}catch(err){setError(err instanceof Error?err.message:'Failed to approve task');}finally{setApproving(false);}};
  if(!task)return <div className="p-4 md:p-8">{error?<p className="text-sm text-red-400" role="alert">{error}</p>:<Skeleton className="h-96 w-full"/>}</div>;
  const durationMs=task.completedAt?new Date(task.completedAt).getTime()-new Date(task.createdAt).getTime():null;const duration=durationMs!==null&&durationMs>=0?`${(durationMs/1000).toFixed(1)}s`:'In progress';const isLive=!terminalStatuses.has(task.status)&&task.status!=='awaiting-approval';const activeStep=lifecycleIndex(task.status);const isFailure=task.status==='failed'||task.status==='rejected';
  return <div className="space-y-5 md:space-y-6 max-w-6xl pb-28 md:pb-10">
    <header className="sticky top-0 z-20 -mx-4 px-4 py-3 md:static md:mx-0 md:px-0 md:py-0 bg-[var(--bg-primary)]/95 md:bg-transparent backdrop-blur-xl md:backdrop-blur-none border-b md:border-0" style={{borderColor:'var(--border-color')}}><div className="flex items-center gap-3"><Link href="/tasks" aria-label="Back to tasks" className="shrink-0 h-10 w-10 inline-flex items-center justify-center rounded-xl hover:bg-[var(--bg-secondary)] text-[var(--text-secondary)] transition-colors"><ArrowLeft size={19}/></Link><div className="min-w-0 flex-1"><div className="flex items-center gap-2 flex-wrap"><h1 className="text-lg md:text-2xl font-bold text-[var(--text-primary)] truncate">Task {task.id}</h1><StatusBadge status={task.status}/>{isLive&&<span className="text-xs text-[var(--accent-primary)] flex items-center gap-1"><Radio size={12} className="animate-pulse"/> Live</span>}</div><p className="text-xs text-[var(--text-muted)] mt-0.5 truncate">Created {formatDate(task.createdAt)}{task.completedAt?` · completed ${formatDate(task.completedAt)}`:''}</p></div><button type="button" onClick={()=>void loadTask()} disabled={refreshing} className="hidden sm:inline-flex btn btn-secondary shrink-0">{refreshing?'Refreshing…':'Refresh'}</button></div></header>
    {error&&<div role="alert" className="rounded-xl border border-red-500/30 bg-red-500/5 p-3 text-sm text-red-400">{error}</div>}
    <ExecutionTruth status={task.status}/>
    <section className="glass-card border border-[var(--border-color)] p-4 md:p-5" aria-label="Task lifecycle"><div className="flex items-start justify-between gap-4 mb-5"><div><h2 className="font-semibold text-[var(--text-primary)]">Execution lifecycle</h2><p className="text-xs text-[var(--text-secondary)] mt-1 max-w-2xl">This timeline is driven by recorded task state. A request being accepted never advances it by itself.</p></div>{isFailure&&<span className="hidden sm:block text-xs text-red-400">Execution stopped</span>}</div><div className="space-y-3 md:grid md:grid-cols-3 md:gap-4 md:space-y-0">{lifecycle.map((step,index)=>{const done=!isFailure&&activeStep>=index;const current=!isFailure&&activeStep===index;return <div key={step.key} className="relative flex items-center gap-3 md:block"><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full border ${done?'border-[var(--accent-primary)] text-[var(--accent-primary)] bg-[var(--accent-primary)]/5':'border-[var(--border-color)] text-[var(--text-muted)]'}`}>{done?<CheckCircle size={15}/>:<Circle size={15}/>}</span><div className="min-w-0 md:mt-2"><span className={`text-sm ${current?'font-semibold text-[var(--text-primary)]':'text-[var(--text-secondary)]'}`}>{step.label}</span><span className="block text-[11px] text-[var(--text-muted)]">{step.detail}</span></div>{index<lifecycle.length-1&&<div className={`absolute left-4 top-8 h-3 w-px md:left-8 md:top-4 md:h-px md:w-[calc(100%-1rem)] ${!isFailure&&activeStep>index?'bg-[var(--accent-primary)]':'bg-[var(--border-color)]'}`}/>}</div>;})}</div>
      {task.status==='awaiting-approval'&&<div className="mt-5 rounded-xl border border-[var(--accent-primary)]/30 bg-[var(--accent-primary)]/5 p-4"><div className="flex items-center gap-2 text-sm font-medium text-[var(--text-primary)]"><ShieldCheck size={16} className="text-[var(--accent-primary)]"/> Approval required before execution</div><p className="text-xs text-[var(--text-secondary)] mt-1">This task is paused at the enforced execution boundary. Approval changes the recorded state; it does not merely dismiss a UI prompt.</p><button type="button" className="btn btn-primary mt-4 w-full sm:w-auto" onClick={approve} disabled={approving}><CheckCircle size={15}/>{approving?'Approving…':'Approve execution'}</button></div>}
      {isFailure&&<div className="mt-5 rounded-xl border border-red-500/30 bg-red-500/5 p-4"><div className="flex items-center gap-2 text-sm font-medium text-[var(--text-primary)]"><AlertTriangle size={15} className="text-red-400"/> Execution did not reach a verified result.</div><p className="text-xs text-[var(--text-secondary)] mt-1">Do not treat retry as automatic success. Inspect the recorded graph and attempt history before choosing recovery.</p><Link href="/graphs" className="btn btn-secondary mt-4 inline-flex items-center gap-2"><RotateCw size={15}/> Review recovery path</Link></div>}
    </section>
    <div className="grid grid-cols-2 md:grid-cols-4 gap-3"><Metric icon={<BrainCircuit size={14}/>} label="Model" value={task.modelUsed||'Not selected'}/><Metric icon={<DollarSign size={14}/>} label="Recorded cost" value={formatCurrency(task.totalCostCents)}/><Metric icon={<Clock3 size={14}/>} label="Duration" value={duration}/><Metric icon={<ShieldCheck size={14}/>} label="Quality" value={typeof task.qualityScore==='number'?`${task.qualityScore}/100`:'Not available'}/></div>
    <div className="grid grid-cols-1 lg:grid-cols-[1.6fr_1fr] gap-5 md:gap-6"><div className="space-y-5 md:space-y-6"><section className="glass-card p-4 md:p-6 border border-[var(--border-color)] space-y-3"><h2 className="text-sm font-medium text-[var(--text-secondary)] uppercase tracking-wider">Requested outcome</h2><div className="p-4 bg-[var(--bg-secondary)] rounded-xl border border-[var(--border-color)] text-sm text-[var(--text-primary)] whitespace-pre-wrap leading-6">{task.prompt}</div></section><section className="glass-card p-4 md:p-6 border border-[var(--border-color)] space-y-3"><div className="flex items-center justify-between gap-3"><h2 className="text-sm font-medium text-[var(--text-secondary)] uppercase tracking-wider">Result</h2>{task.output&&<span className="text-xs text-[var(--accent-primary)]">Recorded output</span>}</div><div className="text-sm text-[var(--text-primary)] whitespace-pre-wrap leading-6">{task.output||(isLive?'Uden is still executing this work. The result will appear here when the execution system records it.':isFailure?'No verified result was recorded.':'No result generated.')}</div>{task.output&&<div className="pt-3 border-t border-[var(--border-color)] text-xs text-[var(--text-muted)] flex items-center gap-2"><Info size={13}/> Output presence does not independently prove correctness; verification state above is authoritative.</div>}</section></div>
      <aside className="space-y-5 md:space-y-6"><section className="glass-card p-4 md:p-6 border border-[var(--border-color)]"><h2 className="text-sm font-medium text-[var(--text-primary)] mb-4">Execution details</h2><div className="space-y-4"><Row icon={<BrainCircuit size={16}/>} label="Selected model"><ModelPill model={task.modelUsed||'Not selected'}/></Row><Row icon={<DollarSign size={16}/>} label="Recorded cost"><span className="font-mono font-medium">{formatCurrency(task.totalCostCents)}</span></Row><Row label="Mode"><span className="text-sm">{task.mode}</span></Row><Row label="Project"><span className="font-mono text-xs truncate max-w-40">{task.projectId||'Unassigned'}</span></Row><div className="pt-3 border-t border-[var(--border-color)] flex flex-col items-center"><span className="text-xs text-[var(--text-secondary)] mb-2">Quality check score</span>{typeof task.qualityScore==='number'?<QualityScore score={task.qualityScore} size="lg"/>:<span className="text-sm text-[var(--text-secondary)]">Not available</span>}</div></div></section><section className="glass-card p-4 md:p-6 border border-[var(--border-color)]"><div className="flex items-center gap-2 mb-2"><Workflow size={17} className="text-[var(--accent-primary)]"/><h2 className="text-sm font-medium text-[var(--text-primary)]">Execution trail</h2></div><p className="text-xs text-[var(--text-secondary)] leading-relaxed">Dependencies, model attempts, escalation decisions, node outputs, cost and timeline data are available in the Graphs workspace.</p><Link href="/graphs" className="mt-4 inline-flex items-center text-sm text-[var(--accent-primary)]">Open execution graphs →</Link></section></aside></div>
    <div className="sm:hidden"><button type="button" onClick={()=>void loadTask()} disabled={refreshing} className="btn btn-secondary w-full justify-center">{refreshing?'Refreshing…':'Refresh recorded state'}</button></div>
  </div>;
}
function Metric({icon,label,value}:{icon?:React.ReactNode;label:string;value:string}){return <div className="glass-card p-3.5 md:p-4 border border-[var(--border-color)]"><div className="flex items-center gap-2 text-xs text-[var(--text-muted)]">{icon}{label}</div><div className="mt-1 text-sm font-semibold text-[var(--text-primary)] truncate">{value}</div></div>;}
function Row({icon,label,children}:{icon?:React.ReactNode;label:string;children:React.ReactNode}){return <div className="flex items-center justify-between gap-3 pb-3 border-b border-[var(--border-color)]"><div className="flex items-center gap-2 text-[var(--text-secondary)] text-sm">{icon}{label}</div>{children}</div>;}
