import { describe, expect, it, beforeAll, afterAll } from 'vitest';
import { getPlatformProxy } from 'wrangler';
import type { D1Database } from '@cloudflare/workers-types';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { claimDueObjectives, createAutonomousObjective, markObjectiveRun } from './autonomous-objectives';
import type { TaskGraphPlan } from '@ai-work-partner/shared';

const here=dirname(fileURLToPath(import.meta.url));const root=resolve(here,'../..');
const execSqlFile=async(db:D1Database,path:string)=>{const sql=await readFile(path,'utf8');for(const statement of sql.replace(/^\uFEFF/,'').replace(/^[\t ]*--[^\r\n]*(?:\r?\n|$)/gm,'').split(';').map(s=>s.trim()).filter(Boolean))await db.prepare(statement).run()};

describe('autonomous objectives D1 integration',()=>{let db:D1Database;let dispose:(()=>Promise<void>)|undefined;const env={} as any;beforeAll(async()=>{const platform=await getPlatformProxy({configPath:resolve(root,'wrangler.jsonc'),persist:false});db=platform.env.DB as D1Database;env.DB=db;dispose=platform.dispose;await execSqlFile(db,resolve(here,'../db/schema.sql'));await execSqlFile(db,resolve(root,'migrations/0012_autonomous_objectives.sql'));await execSqlFile(db,resolve(root,'migrations/0015_autonomous_workflow_linkage.sql'));await execSqlFile(db,resolve(root,'migrations/0016_autonomous_objective_projects.sql'));await db.prepare('INSERT INTO tenants (id,name,email,api_key_hash) VALUES (?,?,?,?)').bind('objective-tenant','Objective Tenant','objective@example.test','objective-hash').run()});afterAll(async()=>{await dispose?.()});
  it('persists an objective, project linkage, and claims it exactly once when due',async()=>{const plan:TaskGraphPlan={goal:'collect daily competitor prices',projectId:'project-1',nodes:[{id:'collect',title:'Collect prices',prompt:'Collect prices',domain:'research',complexity:2,expectedFormat:'text',recommendedTier:1,dependencies:[],contextFrom:[]}]};const now=new Date('2026-09-07T03:00:00.000Z');const objective=await createAutonomousObjective(env,'objective-tenant',{name:'Price monitor',objective:'Collect competitor prices',plan,projectId:'project-1',permissions:['project:execute'],resources:['web'],successCriteria:'At least one verified price',intervalSeconds:3600,nextRunAt:'2026-09-07T02:59:00.000Z'});expect(objective.projectId).toBe('project-1');const claimed=await claimDueObjectives(env,now);expect(claimed).toHaveLength(1);expect(claimed[0].run.status).toBe('queued');expect(claimed[0].objective.nextRunAt).toBe('2026-09-07T04:00:00.000Z');expect(await claimDueObjectives(env,now)).toHaveLength(0);await markObjectiveRun(env,'objective-tenant',claimed[0].run.id,'queued',{graphId:'graph-1',workflowInstanceId:claimed[0].run.id});const row=await db.prepare('SELECT status,graph_id,workflow_instance_id FROM autonomous_objective_runs WHERE id=?').bind(claimed[0].run.id).first<any>();expect(row?.status).toBe('queued');expect(row?.graph_id).toBe('graph-1');expect(row?.workflow_instance_id).toBe(claimed[0].run.id);await markObjectiveRun(env,'objective-tenant',claimed[0].run.id,'completed',{graphId:'graph-1'});const completed=await db.prepare('SELECT status,completed_at FROM autonomous_objective_runs WHERE id=?').bind(claimed[0].run.id).first<any>();expect(completed?.status).toBe('completed');expect(completed?.completed_at).toBeTruthy()});
});
