import type { Env } from '../types';
import { listGitHubRepositories, getGitHubTree, getGitHubTreeBySha, getGitHubBlob, getGitHubCommit, listGitHubCommits, listGitHubPulls, getGitHubPull, createGitHubBranch, commitGitHubFiles, createGitHubPull, mergeGitHubPull, type GitHubWriteFile } from './github-connector';
import { getGitHubPullFiles } from './github-pull-files';
import { listOriginRepositories, listOriginCommits, getOriginCommit, getOriginBlob, getOriginTree, listOriginPulls, getOriginPull, getOriginPullFiles, createOriginBranch, commitOriginFiles, createOriginPull, mergeOriginPull, type OriginWriteFile } from './origin-connector';
export type CodeSourceProvider = 'github' | 'origin';
export interface CodeRepositoryRef { provider: CodeSourceProvider; owner: string; repo: string; }
export interface CodeFileChange { path: string; content: string; }
export interface CodeMutationPrecondition { expectedHeadSha: string; }
export interface CodeSource { provider: CodeSourceProvider; listRepositories(env: Env, tenantId: string): Promise<unknown>; getRepository(env: Env, tenantId: string, ref: CodeRepositoryRef): Promise<unknown>; getTree(env: Env, tenantId: string, ref: CodeRepositoryRef, treeRef: string): Promise<unknown>; getBlob(env: Env, tenantId: string, ref: CodeRepositoryRef, sha: string): Promise<unknown>; getCommit(env: Env, tenantId: string, ref: CodeRepositoryRef, sha: string): Promise<unknown>; listCommits(env: Env, tenantId: string, ref: CodeRepositoryRef, branch?: string): Promise<unknown>; listPullRequests(env: Env, tenantId: string, ref: CodeRepositoryRef): Promise<unknown>; getPullRequest(env: Env, tenantId: string, ref: CodeRepositoryRef, number: number): Promise<unknown>; getPullRequestFiles(env: Env, tenantId: string, ref: CodeRepositoryRef, number: number): Promise<unknown>; createBranch(env: Env, tenantId: string, ref: CodeRepositoryRef, branch: string, fromSha: string): Promise<unknown>; commitFiles(env: Env, tenantId: string, ref: CodeRepositoryRef, branch: string, changes: CodeFileChange[], precondition: CodeMutationPrecondition, message: string): Promise<unknown>; createPullRequest(env: Env, tenantId: string, ref: CodeRepositoryRef, head: string, base: string, title: string, body: string): Promise<unknown>; mergePullRequest(env: Env, tenantId: string, ref: CodeRepositoryRef, number: number, precondition: CodeMutationPrecondition): Promise<unknown>; }
function assertProviderRef(provider: CodeSourceProvider, ref: CodeRepositoryRef): void { if (ref.provider !== provider) throw new Error(`Code repository provider mismatch: expected ${provider}, received ${ref.provider}`); if (!ref.owner.trim() || !ref.repo.trim()) throw new Error('Code repository owner and name are required'); }
function githubOwnerRepo(ref: CodeRepositoryRef): [string,string] { assertProviderRef('github',ref); return [ref.owner,ref.repo]; }
function originOwnerRepo(ref: CodeRepositoryRef): [string,string] { assertProviderRef('origin',ref); return [ref.owner,ref.repo]; }
export function getCodeSource(provider: CodeSourceProvider): CodeSource {
 if(provider==='github') return { provider, listRepositories:(e,t)=>listGitHubRepositories(e,t), getRepository:async(e,t,r)=>{const[o,n]=githubOwnerRepo(r);const rs=await listGitHubRepositories(e,t);return rs.find(x=>x.full_name===`${o}/${n}`)??null;}, getTree:(e,t,r,tr)=>{const[o,n]=githubOwnerRepo(r);return /^[0-9a-f]{7,64}$/i.test(tr)?getGitHubTreeBySha(e,t,o,n,tr):getGitHubTree(e,t,o,n,tr);}, getBlob:(e,t,r,s)=>{const[o,n]=githubOwnerRepo(r);return getGitHubBlob(e,t,o,n,s);}, getCommit:(e,t,r,s)=>{const[o,n]=githubOwnerRepo(r);return getGitHubCommit(e,t,o,n,s);}, listCommits:(e,t,r,b)=>{const[o,n]=githubOwnerRepo(r);return listGitHubCommits(e,t,o,n,b);}, listPullRequests:(e,t,r)=>{const[o,n]=githubOwnerRepo(r);return listGitHubPulls(e,t,o,n);}, getPullRequest:(e,t,r,num)=>{const[o,n]=githubOwnerRepo(r);return getGitHubPull(e,t,o,n,num);}, getPullRequestFiles:(e,t,r,num)=>{const[o,n]=githubOwnerRepo(r);return getGitHubPullFiles(e,t,o,n,num);}, createBranch:(e,t,r,b,s)=>{const[o,n]=githubOwnerRepo(r);return createGitHubBranch(e,t,o,n,b,s);}, commitFiles:(e,t,r,b,c,p,m)=>{const[o,n]=githubOwnerRepo(r);return commitGitHubFiles(e,t,o,n,b,p.expectedHeadSha,m,c as GitHubWriteFile[]);}, createPullRequest:(e,t,r,h,b,title,body)=>{const[o,n]=githubOwnerRepo(r);return createGitHubPull(e,t,o,n,h,b,title,body);}, mergePullRequest:(e,t,r,num,p)=>{const[o,n]=githubOwnerRepo(r);return mergeGitHubPull(e,t,o,n,num,p.expectedHeadSha);} };
 return { provider, listRepositories:(e,t)=>listOriginRepositories(e,t), getRepository:async(e,t,r)=>{const[o,n]=originOwnerRepo(r);const result=await listOriginRepositories(e,t) as {repositories?:Array<{namespace?:string;name?:string}>};return result.repositories?.find(x=>x.namespace===o&&x.name===n)??null;}, getTree:(e,t,r,tr)=>{const[o,n]=originOwnerRepo(r);return getOriginTree(e,t,o,n,tr);}, getBlob:(e,t,r,s)=>{const[o,n]=originOwnerRepo(r);return getOriginBlob(e,t,o,n,s);}, getCommit:(e,t,r,s)=>{const[o,n]=originOwnerRepo(r);return getOriginCommit(e,t,o,n,s);}, listCommits:(e,t,r,b)=>{const[o,n]=originOwnerRepo(r);return listOriginCommits(e,t,o,n,b);}, listPullRequests:(e,t,r)=>{const[o,n]=originOwnerRepo(r);return listOriginPulls(e,t,o,n);}, getPullRequest:(e,t,r,num)=>{const[o,n]=originOwnerRepo(r);return getOriginPull(e,t,o,n,String(num));}, getPullRequestFiles:(e,t,r,num)=>{const[o,n]=originOwnerRepo(r);return getOriginPullFiles(e,t,o,n,String(num));}, createBranch:(e,t,r,b,s)=>{const[o,n]=originOwnerRepo(r);return createOriginBranch(e,t,o,n,b,s);}, commitFiles:(e,t,r,b,c,p,m)=>{const[o,n]=originOwnerRepo(r);return commitOriginFiles(e,t,o,n,b,p.expectedHeadSha,m,c as OriginWriteFile[]);}, createPullRequest:(e,t,r,h,b,title,body)=>{const[o,n]=originOwnerRepo(r);return createOriginPull(e,t,o,n,h,b,title,body);}, mergePullRequest:(e,t,r,num,p)=>{const[o,n]=originOwnerRepo(r);return mergeOriginPull(e,t,o,n,String(num),p.expectedHeadSha);} };
}
