import { describe, expect, it, beforeAll, afterAll } from 'vitest';
import { getPlatformProxy } from 'wrangler';
import type { D1Database } from '@cloudflare/workers-types';
import { resolve } from 'node:path';
import { authorizeExternalSideEffect, markExternalSideEffectInFlight, markExternalSideEffectUnknown, claimUnknownExternalSideEffect, reconcileClaimedExternalSideEffect } from './external-side-effects';
import { appendExecutionEvent, listExecutionEvents } from './execution-events';
import { authorizeRuntimeExecution } from './execution-runtimes';
import { applyCurrentD1Schema } from '../test/d1-bootstrap';
import type { RuntimeExecutionRequest } from '@ai-work-partner/shared';

const root=resolve(process.cwd());

describe('durable execution hardening D1 integration',()=>{let db:D1Database;let dispose:(()=>Promise<void>)|undefined;beforeAll(async()=>{const platform=await getPlatformProxy({configPath:resolve(root,'wrangler.test.jsonc'),persist:false});db=platform.env.DB as D1Database;dispose=platform.dispose;await applyCurrentD1Schema(db,root);await db.prepare('INSERT INTO tenants (id,name,email,api_key_hash) VALUES (?,?,?,?)').bind('hardening-tenant','Hardening Tenant','hardening@example.test','hardening-hash').run();await db.prepare('INSERT INTO tasks (id,tenant_id,prompt) VALUES (?,?,?)').bind('hardening-task','hardening-tenant','hardening').run();await db.prepare('INSERT INTO task_graphs (id,tenant_id,root_task_id,goal,status,execution_version,execution_owner,lease_until) VALUES (?,?,?,?,?,?,?,datetime(\'now\',\'+10 minutes\'))').bind('hardening-graph','hardening-tenant','hardening-task','hardening','running',7,'owner-a').run();await db.prepare('INSERT INTO task_graph_nodes (id,graph_id,tenant_id,title,prompt,domain,complexity,expected_format,recommended_tier,dependencies_json,context_from_json,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').bind('node-a','hardening-graph','hardening-tenant','Node','Node','engineering',1,'text',1,'[]','[]','ready').run();await db.prepare('INSERT INTO execution_runtimes (id,tenant_id,kind,state,capabilities_json,last_heartbeat_at) VALUES (?,?,?,?,?,CURRENT_TIMESTAMP)').bind('runtime-a','hardening-tenant','desktop_local','online',JSON.stringify(['command.exec','git.write'])).run()});afterAll(async()=>{await dispose?.()});

it('binds an external side effect to immutable intent and never silently reuses a key for different work',async()=>{const input={id:'side-effect-1',tenantId:'hardening-tenant',graphId:'hardening-graph',nodeId:'node-a',attemptId:'attempt-a',executionOwner:'owner-a',executionVersion:7,provider:'github',operation:'create_pull_request',idempotencyKey:'github:pr:attempt-a',requestFingerprint:'fp-a'};const first=await authorizeExternalSideEffect(db,input);const second=await authorizeExternalSideEffect(db,{...input,id:'side-effect-2'});expect(second.id).toBe(first.id);await expect(authorizeExternalSideEffect(db,{...input,id:'side-effect-3',requestFingerprint:'fp-b'})).rejects.toThrow(/different intent|raced/);await markExternalSideEffectInFlight(db,input);await markExternalSideEffectUnknown(db,input,'worker died after provider call');const unknown=await claimUnknownExternalSideEffect(db,'hardening-tenant','side-effect-1','recovery-a',30);expect(unknown?.recoveryOwner).toBe('recovery-a');const reconciled=await reconcileClaimedExternalSideEffect(db,unknown!,{status:'completed',externalOperationId:'github-pr-123',responseFingerprint:'resp-1'});expect(reconciled.status).toBe('completed');expect(reconciled.externalOperationId).toBe('github-pr-123');await expect(db.prepare("UPDATE external_side_effects SET external_operation_id='github-pr-999' WHERE id='side-effect-1'").run()).rejects.toThrow();});

it('prevents two recovery workers from owning the same unknown side effect',async()=>{const input={id:'side-effect-race',tenantId:'hardening-tenant',graphId:'hardening-graph',nodeId:'node-a',attemptId:'attempt-race',executionOwner:'owner-a',executionVersion:7,provider:'github',operation:'commit_files',idempotencyKey:'github:commit:race',requestFingerprint:'race-fp'};await authorizeExternalSideEffect(db,input);await markExternalSideEffectInFlight(db,input);await markExternalSideEffectUnknown(db,input,'lost acknowledgement');const first=await claimUnknownExternalSideEffect(db,'hardening-tenant',input.id,'recovery-1',60);const second=await claimUnknownExternalSideEffect(db,'hardening-tenant',input.id,'recovery-2',60);expect(first?.recoveryOwner).toBe('recovery-1');expect(second).toBeNull();});

it('keeps execution evidence append-only',async()=>{await appendExecutionEvent(db,{id:'event-1',tenantId:'hardening-tenant',graphId:'hardening-graph',nodeId:'node-a',attemptId:'attempt-events',executionOwner:'owner-a',executionVersion:7,eventType:'runtime.authorized',status:'authorized',details:{capability:'command.exec'}});await appendExecutionEvent(db,{id:'event-2',tenantId:'hardening-tenant',graphId:'hardening-graph',nodeId:'node-a',attemptId:'attempt-events',executionOwner:'owner-a',executionVersion:7,eventType:'runtime.unknown',status:'unknown',details:{reason:'worker crash'}});const events=await listExecutionEvents(db,'hardening-tenant','hardening-graph');expect(events.map(e=>e.eventType)).toEqual(['runtime.authorized','runtime.unknown']);await expect(db.prepare("UPDATE execution_events SET event_type='rewritten' WHERE id='event-1'").run()).rejects.toThrow();await expect(db.prepare("DELETE FROM execution_events WHERE id='event-1'").run()).rejects.toThrow();});

it('requires durable approval before a high-risk runtime capability can execute',async()=>{const request:RuntimeExecutionRequest={runtimeId:'runtime-a',graphId:'hardening-graph',nodeId:'node-a',attemptId:'runtime-attempt-1',executionOwner:'owner-a',executionVersion:7,leaseExpiresAt:new Date(Date.now()+600000).toISOString(),capability:'git.write'};await expect(authorizeRuntimeExecution(db,'hardening-tenant',request)).rejects.toThrow(/approval/);await db.prepare("INSERT INTO graph_approval_requests (id,tenant_id,graph_id,node_id,status,requested_by) VALUES (?,?,?,?,?,?)").bind('approval-1','hardening-tenant','hardening-graph','node-a','approved','test').run();const authorized=await authorizeRuntimeExecution(db,'hardening-tenant',request);expect(authorized.attemptId).toBe('runtime-attempt-1');});

it('rejects a new attempt whose generation is older than the authoritative graph',async()=>{await expect(db.prepare("INSERT INTO task_graph_attempts (id,graph_id,node_id,tenant_id,attempt_number,model,status,execution_owner,execution_version) VALUES (?,?,?,?,?,?,?,?,?)").bind('stale-attempt','hardening-graph','node-a','hardening-tenant',1,'test-model','running','owner-a',6).run()).rejects.toThrow(/generation/);});
});
