import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { getPlatformProxy } from 'wrangler';
import type { D1Database } from '@cloudflare/workers-types';
import { resolve } from 'node:path';
import type { TaskGraph } from '@ai-work-partner/shared';
import { applyCurrentD1Schema } from '../test/d1-bootstrap';
import { persistGraph } from './graph-persistence';
import { recordExecutionContradiction } from './execution-contradictions';
import { proposeExecutionDiagnosis, acceptExecutionDiagnosis, proposeCorrectiveAction, approveCorrectiveAction, startCorrectiveAction, completeCorrectiveAction, proposeExecutionPlanRevision, activateExecutionPlanRevision, recordExecutionValidation } from './execution-correction-loop';
import { resolveValidatedExecutionContradiction } from './execution-correction-finalization';

describe('execution correction loop D1 integration',()=>{
  let db:D1Database; let dispose:(()=>Promise<void>)|undefined;
  beforeAll(async()=>{const platform=await getPlatformProxy({configPath:resolve(process.cwd(),'wrangler.test.jsonc'),persist:false});db=platform.env.DB as D1Database;dispose=platform.dispose;await applyCurrentD1Schema(db,resolve(process.cwd()));await db.prepare('INSERT INTO tenants(id,name,email,api_key_hash) VALUES(?,?,?,?)').bind('correction-tenant','Correction','correction@example.test','correction-hash').run();await db.prepare('INSERT INTO tasks(id,tenant_id,prompt,status) VALUES(?,?,?,?)').bind('correction-root','correction-tenant','correction graph','processing').run();});
  afterAll(async()=>{await dispose?.()});
  it('durably walks contradiction -> diagnosis -> action -> revision -> validation',async()=>{const graph:TaskGraph={id:'correction-graph',rootTaskId:'correction-root',goal:'correction graph',createdAt:new Date().toISOString(),nodes:[{id:'node',title:'Node',prompt:'work',domain:'general',complexity:1,expectedFormat:'markdown',recommendedTier:1,dependencies:[],contextFrom:[],status:'ready',attemptedModels:[]}]};await persistGraph(db,'correction-tenant',graph);const contradiction=await recordExecutionContradiction(db,{tenantId:'correction-tenant',graphId:graph.id,nodeId:'node',category:'integrity',message:'Observed state contradicts expected state',expectedState:{version:3},observedState:{version:4}});const d=await proposeExecutionDiagnosis(db,{tenantId:'correction-tenant',graphId:graph.id,contradictionId:contradiction.id,diagnosis:'The worker planned against an older project version',confidence:0.97,evidence:{expectedVersion:3,observedVersion:4}});await acceptExecutionDiagnosis(db,'correction-tenant',d.id);const a=await proposeCorrectiveAction(db,{tenantId:'correction-tenant',graphId:graph.id,diagnosisId:d.id,action:'Refresh project state and rebuild the affected plan',actionInput:{refresh:true}});await approveCorrectiveAction(db,'correction-tenant',a.id);await startCorrectiveAction(db,'correction-tenant',a.id);await completeCorrectiveAction(db,'correction-tenant',a.id);const r=await proposeExecutionPlanRevision(db,{tenantId:'correction-tenant',graphId:graph.id,contradictionId:contradiction.id,correctiveActionId:a.id,previousPlanHash:'old-plan',revisedPlan:{nodes:['replanned-node'],reason:'version refresh'},reason:'Discard the stale plan and re-plan from observed state'});const active=await activateExecutionPlanRevision(db,'correction-tenant',r.id);const validation=await recordExecutionValidation(db,{tenantId:'correction-tenant',graphId:graph.id,contradictionId:contradiction.id,planRevisionId:active.id,expectedState:{version:4},observedState:{version:4},result:'passed',validationMessage:'Replanned execution now matches observed state'});await resolveValidatedExecutionContradiction(db,{tenantId:'correction-tenant',graphId:graph.id,contradictionId:contradiction.id,validationId:validation.id});const stored=await db.prepare('SELECT status FROM execution_contradictions WHERE id=?').bind(contradiction.id).first<{status:string}>();expect(stored?.status).toBe('resolved');expect(await db.prepare("SELECT COUNT(*) AS count FROM execution_plan_revisions WHERE graph_id=? AND status='active'").bind(graph.id).first<{count:number}>()).toMatchObject({count:1});});
});
