import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { getPlatformProxy } from 'wrangler';
import type { D1Database } from '@cloudflare/workers-types';
import { resolve } from 'node:path';
import { applyCurrentD1Schema } from '../test/d1-bootstrap';
import { persistGraph } from './graph-persistence';
import { recordExecutionContradiction } from './execution-contradictions';
import { proposeExecutionDiagnosis, acceptExecutionDiagnosis, proposeCorrectiveAction, approveCorrectiveAction, startCorrectiveAction, completeCorrectiveAction, proposeExecutionPlanRevision, activateExecutionPlanRevision, recordExecutionValidation } from './execution-correction-loop';
import { resolveValidatedExecutionContradiction } from './execution-correction-finalization-v2';
import type { TaskGraph } from '@ai-work-partner/shared';

describe('execution resolution idempotency D1 integration',()=>{
  let db:D1Database; let dispose:(()=>Promise<void>)|undefined;
  beforeAll(async()=>{const platform=await getPlatformProxy({configPath:resolve(process.cwd(),'wrangler.test.jsonc'),persist:false});db=platform.env.DB as D1Database;dispose=platform.dispose;await applyCurrentD1Schema(db,resolve(process.cwd()));await db.prepare('INSERT INTO tenants(id,name,email,api_key_hash) VALUES(?,?,?,?)').bind('idem-tenant','Idempotency','idem@example.test','idem-hash').run();await db.prepare('INSERT INTO tasks(id,tenant_id,prompt,status) VALUES(?,?,?,?)').bind('idem-root','idem-tenant','idempotency graph','processing').run();await db.prepare('INSERT INTO tenants(id,name,email,api_key_hash) VALUES(?,?,?,?)').bind('idem-other-tenant','Other Idempotency','other-idem@example.test','other-idem-hash').run();await db.prepare('INSERT INTO tasks(id,tenant_id,prompt,status) VALUES(?,?,?,?)').bind('idem-other-root','idem-other-tenant','other idempotency graph','processing').run();});
  afterAll(async()=>{await dispose?.()});
  async function setup(tenantId='idem-tenant',rootTaskId='idem-root',prefix=`idem-${crypto.randomUUID()}`){const graph:TaskGraph={id:`${prefix}-graph`,rootTaskId,goal:'idempotency graph',createdAt:new Date().toISOString(),nodes:[{id:`${prefix}-node`,title:'Node',prompt:'work',domain:'general',complexity:1,expectedFormat:'markdown',recommendedTier:1,dependencies:[],contextFrom:[],status:'ready',attemptedModels:[]}]};await persistGraph(db,tenantId,graph);const contradiction=await recordExecutionContradiction(db,{tenantId,graphId:graph.id,nodeId:`${prefix}-node`,category:'integrity',message:'Observed state contradicts expected state',expectedState:{version:1},observedState:{version:2}});const d=await proposeExecutionDiagnosis(db,{tenantId,graphId:graph.id,contradictionId:contradiction.id,diagnosis:'Stale state',confidence:0.99,evidence:{expectedVersion:1,observedVersion:2}});await acceptExecutionDiagnosis(db,tenantId,d.id);const a=await proposeCorrectiveAction(db,{tenantId,graphId:graph.id,diagnosisId:d.id,action:'Refresh state',executorPrincipal:'worker:idem'});await approveCorrectiveAction(db,tenantId,a.id);await startCorrectiveAction(db,tenantId,a.id);await completeCorrectiveAction(db,tenantId,a.id);const r=await proposeExecutionPlanRevision(db,{tenantId,graphId:graph.id,contradictionId:contradiction.id,correctiveActionId:a.id,revisedPlan:{nodes:['replanned']},reason:'Refresh'});const active=await activateExecutionPlanRevision(db,tenantId,r.id);const validation=await recordExecutionValidation(db,{tenantId,graphId:graph.id,contradictionId:contradiction.id,planRevisionId:active.id,result:'passed',validationMessage:'Independent validation passed',validatorPrincipal:'validator:idem'});return{graph,contradiction,validation};}
  it('retries the same request without duplicating resolution evidence',async()=>{const {graph,contradiction,validation}=await setup();const input={tenantId:'idem-tenant',graphId:graph.id,contradictionId:contradiction.id,validationId:validation.id,resolutionReason:'Validated repair',resolutionRequestId:'stable-request-1'};await resolveValidatedExecutionContradiction(db,input);await resolveValidatedExecutionContradiction(db,input);expect(await db.prepare('SELECT COUNT(*) AS count FROM execution_contradiction_resolutions WHERE contradiction_id=?').bind(contradiction.id).first<{count:number}>()).toMatchObject({count:1});});
  it('rejects reuse of a request id for a different resolution target',async()=>{const first=await setup();await resolveValidatedExecutionContradiction(db,{tenantId:'idem-tenant',graphId:first.graph.id,contradictionId:first.contradiction.id,validationId:first.validation.id,resolutionReason:'First',resolutionRequestId:'stable-request-2'});const second=await setup();await expect(resolveValidatedExecutionContradiction(db,{tenantId:'idem-tenant',graphId:second.graph.id,contradictionId:second.contradiction.id,validationId:second.validation.id,resolutionReason:'Replay against another contradiction',resolutionRequestId:'stable-request-2'})).rejects.toThrow('already used for a different resolution');});
  it('rejects reuse of a request id with a different immutable reason',async()=>{const first=await setup();await resolveValidatedExecutionContradiction(db,{tenantId:'idem-tenant',graphId:first.graph.id,contradictionId:first.contradiction.id,validationId:first.validation.id,resolutionReason:'Original reason',resolutionRequestId:'stable-request-3'});await expect(resolveValidatedExecutionContradiction(db,{tenantId:'idem-tenant',graphId:first.graph.id,contradictionId:first.contradiction.id,validationId:first.validation.id,resolutionReason:'Mutated reason',resolutionRequestId:'stable-request-3'})).rejects.toThrow('already used with a different resolution reason');});
  it('scopes request ids by tenant',async()=>{const first=await setup('idem-tenant','idem-root','tenant-a');await resolveValidatedExecutionContradiction(db,{tenantId:'idem-tenant',graphId:first.graph.id,contradictionId:first.contradiction.id,validationId:first.validation.id,resolutionReason:'Tenant A',resolutionRequestId:'shared-request-id'});const second=await setup('idem-other-tenant','idem-other-root','tenant-b');await expect(resolveValidatedExecutionContradiction(db,{tenantId:'idem-other-tenant',graphId:second.graph.id,contradictionId:second.contradiction.id,validationId:second.validation.id,resolutionReason:'Tenant B',resolutionRequestId:'shared-request-id'})).resolves.toBeUndefined();expect(await db.prepare('SELECT COUNT(*) AS count FROM execution_contradiction_resolutions WHERE resolution_request_id=?').bind('shared-request-id').first<{count:number}>()).toMatchObject({count:2});});
  it('rejects invalid request ids and reasons before touching durable state',async()=>{const {graph,contradiction,validation}=await setup();await expect(resolveValidatedExecutionContradiction(db,{tenantId:'idem-tenant',graphId:graph.id,contradictionId:contradiction.id,validationId:validation.id,resolutionReason:'',resolutionRequestId:'invalid-empty-reason'})).rejects.toThrow('Invalid contradiction resolution reason');await expect(resolveValidatedExecutionContradiction(db,{tenantId:'idem-tenant',graphId:graph.id,contradictionId:contradiction.id,validationId:validation.id,resolutionReason:'valid',resolutionRequestId:'   '})).rejects.toThrow('Invalid contradiction resolution request id');});
  it('makes concurrent reuse of one request id converge to one committed resolution',async()=>{const {graph,contradiction,validation}=await setup();const input={tenantId:'idem-tenant',graphId:graph.id,contradictionId:contradiction.id,validationId:validation.id,resolutionReason:'Concurrent stable retry',resolutionRequestId:'stable-concurrent-request'};const outcomes=await Promise.allSettled([resolveValidatedExecutionContradiction(db,input),resolveValidatedExecutionContradiction(db,input)]);expect(outcomes.filter(x=>x.status==='fulfilled')).toHaveLength(2);expect(await db.prepare('SELECT COUNT(*) AS count FROM execution_contradiction_resolutions WHERE contradiction_id=?').bind(contradiction.id).first<{count:number}>()).toMatchObject({count:1});});
});
