import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { getPlatformProxy } from 'wrangler';
import type { D1Database } from '@cloudflare/workers-types';
import { resolve } from 'node:path';
import { applyCurrentD1Schema } from '../test/d1-bootstrap';
import { persistGraph } from './graph-persistence';
import { recordExecutionContradiction } from './execution-contradictions';
import { proposeExecutionDiagnosis, acceptExecutionDiagnosis, proposeCorrectiveAction, approveCorrectiveAction, startCorrectiveAction, completeCorrectiveAction, proposeExecutionPlanRevision, activateExecutionPlanRevision, recordExecutionValidation } from './execution-correction-loop';
import { resolveValidatedExecutionContradiction } from './execution-correction-finalization-v2';
import type { TaskGraph } from '@ai-work-partner/shared';

describe('execution resolution evidence immutability D1 integration',()=>{
  let db:D1Database; let dispose:(()=>Promise<void>)|undefined;
  beforeAll(async()=>{const platform=await getPlatformProxy({configPath:resolve(process.cwd(),'wrangler.test.jsonc'),persist:false});db=platform.env.DB as D1Database;dispose=platform.dispose;await applyCurrentD1Schema(db,resolve(process.cwd()));await db.prepare('INSERT INTO tenants(id,name,email,api_key_hash) VALUES(?,?,?,?)').bind('evidence-tenant','Evidence','evidence@example.test','evidence-hash').run();await db.prepare('INSERT INTO tasks(id,tenant_id,prompt,status) VALUES(?,?,?,?)').bind('evidence-root','evidence-tenant','evidence graph','processing').run();});
  afterAll(async()=>{await dispose?.()});
  async function setup(prefix=`evidence-${crypto.randomUUID()}`){const rootTaskId=`${prefix}-root`;await db.prepare('INSERT INTO tasks(id,tenant_id,prompt,status) VALUES(?,?,?,?)').bind(rootTaskId,'evidence-tenant',`evidence graph ${prefix}`,'processing').run();const graph:TaskGraph={id:`${prefix}-graph`,rootTaskId,goal:'evidence graph',createdAt:new Date().toISOString(),nodes:[{id:`${prefix}-node`,title:'Node',prompt:'work',domain:'general',complexity:1,expectedFormat:'markdown',recommendedTier:1,dependencies:[],contextFrom:[],status:'ready',attemptedModels:[]}]};await persistGraph(db,'evidence-tenant',graph);const contradiction=await recordExecutionContradiction(db,{tenantId:'evidence-tenant',graphId:graph.id,nodeId:`${prefix}-node`,category:'integrity',message:'Expected and observed execution state diverged',expectedState:{version:1},observedState:{version:2}});const diagnosis=await proposeExecutionDiagnosis(db,{tenantId:'evidence-tenant',graphId:graph.id,contradictionId:contradiction.id,diagnosis:'Stale state',confidence:0.99,evidence:{expectedVersion:1,observedVersion:2}});await acceptExecutionDiagnosis(db,'evidence-tenant',diagnosis.id);const action=await proposeCorrectiveAction(db,{tenantId:'evidence-tenant',graphId:graph.id,diagnosisId:diagnosis.id,action:'Refresh state',executorPrincipal:'worker:evidence'});await approveCorrectiveAction(db,'evidence-tenant',action.id);await startCorrectiveAction(db,'evidence-tenant',action.id);await completeCorrectiveAction(db,'evidence-tenant',action.id);const revision=await proposeExecutionPlanRevision(db,{tenantId:'evidence-tenant',graphId:graph.id,contradictionId:contradiction.id,correctiveActionId:action.id,revisedPlan:{nodes:['replanned']},reason:'Repair stale state'});const active=await activateExecutionPlanRevision(db,'evidence-tenant',revision.id);const validation=await recordExecutionValidation(db,{tenantId:'evidence-tenant',graphId:graph.id,contradictionId:contradiction.id,planRevisionId:active.id,result:'passed',validationMessage:'Independent repair validation',validatorPrincipal:'validator:evidence'});await resolveValidatedExecutionContradiction(db,{tenantId:'evidence-tenant',graphId:graph.id,contradictionId:contradiction.id,validationId:validation.id,resolutionReason:'Validated repair',resolutionRequestId:`request-${prefix}`});return{graph,contradiction,diagnosis,action,revision:active,validation};}
  it('blocks mutation of resolved contradiction evidence',async()=>{const {contradiction}=await setup();await expect(db.prepare("UPDATE execution_contradictions SET message=? WHERE id=?").bind('rewritten evidence',contradiction.id).run()).rejects.toThrow('Resolved execution contradiction evidence is immutable');await expect(db.prepare("UPDATE execution_contradictions SET status='open' WHERE id=?").bind(contradiction.id).run()).rejects.toThrow('Resolved execution contradiction evidence is immutable');});
  it('blocks mutation and deletion of the validation used for resolution',async()=>{const {validation}=await setup();await expect(db.prepare("UPDATE execution_validations SET result='failed' WHERE id=?").bind(validation.id).run()).rejects.toThrow('Resolution validation evidence is immutable');await expect(db.prepare('DELETE FROM execution_validations WHERE id=?').bind(validation.id).run()).rejects.toThrow('Resolution validation evidence cannot be deleted');});
  it('blocks mutation and deletion of the corrective action used for resolution',async()=>{const {action}=await setup();await expect(db.prepare("UPDATE execution_corrective_actions SET executor_principal=? WHERE id=?").bind('attacker',action.id).run()).rejects.toThrow('Resolution corrective-action evidence is immutable');await expect(db.prepare('DELETE FROM execution_corrective_actions WHERE id=?').bind(action.id).run()).rejects.toThrow('Resolution corrective-action evidence cannot be deleted');});
  it('blocks mutation and deletion of the active plan revision used for resolution',async()=>{const {revision}=await setup();await expect(db.prepare("UPDATE execution_plan_revisions SET reason=? WHERE id=?").bind('rewritten plan',revision.id).run()).rejects.toThrow('Resolution plan evidence is immutable');await expect(db.prepare('DELETE FROM execution_plan_revisions WHERE id=?').bind(revision.id).run()).rejects.toThrow('Resolution plan evidence cannot be deleted');});
  it('blocks mutation and deletion of the diagnosis behind resolved corrective action',async()=>{const {diagnosis}=await setup();await expect(db.prepare("UPDATE execution_diagnoses SET diagnosis=? WHERE id=?").bind('rewritten diagnosis',diagnosis.id).run()).rejects.toThrow('Resolution diagnosis evidence is immutable');await expect(db.prepare('DELETE FROM execution_diagnoses WHERE id=?').bind(diagnosis.id).run()).rejects.toThrow('Resolution diagnosis evidence cannot be deleted');});
  it('prevents deleting a resolved contradiction and cascading away its resolution audit',async()=>{const {contradiction}=await setup();await expect(db.prepare('DELETE FROM execution_contradictions WHERE id=?').bind(contradiction.id).run()).rejects.toThrow('Resolved execution contradiction evidence cannot be deleted');expect(await db.prepare('SELECT COUNT(*) AS count FROM execution_contradiction_resolutions WHERE contradiction_id=?').bind(contradiction.id).first<{count:number}>()).toMatchObject({count:1});});
});
