export type ExecutionFence = { owner: string; fenceVersion: number };
export type ExecutionAttemptSideEffect = { id:string; graphId:string; nodeId:string; tenantId:string; attemptNumber:number; model:string; provider?:string; status:'running'|'completed'|'failed'; promptTokens?:number; completionTokens?:number; costCents?:number; qualityScore?:number; escalationReason?:string; error?:string; startedAt?:string; completedAt?:string };
export type RuntimeSideEffect = { id:string; graphId:string; nodeId:string; tenantId:string; attemptNumber:number; jobId:string; status:'queued'|'running'|'succeeded'|'failed'; exitCode?:number; output?:string };

export async function assertExecutionFence(db:D1Database,tenantId:string,graphId:string,fence:ExecutionFence):Promise<void>{const row=await db.prepare(`SELECT 1 AS valid FROM task_graphs WHERE id=? AND tenant_id=? AND execution_owner=? AND execution_version=? AND lease_until>=CURRENT_TIMESTAMP`).bind(graphId,tenantId,fence.owner,fence.fenceVersion).first();if(!row)throw new Error('Graph execution lease lost');}

export async function recordFencedAttempt(db:D1Database,attempt:ExecutionAttemptSideEffect,fence:ExecutionFence):Promise<void>{const startedAt=attempt.startedAt||new Date().toISOString();const result=await db.prepare(`INSERT INTO task_graph_attempts (id,graph_id,node_id,tenant_id,attempt_number,model,provider,status,prompt_tokens,completion_tokens,cost_cents,quality_score,escalation_reason,error,started_at,completed_at,execution_owner,execution_version) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(graph_id,node_id,attempt_number) DO UPDATE SET status=excluded.status,model=excluded.model,provider=excluded.provider,prompt_tokens=excluded.prompt_tokens,completion_tokens=excluded.completion_tokens,cost_cents=excluded.cost_cents,quality_score=excluded.quality_score,escalation_reason=excluded.escalation_reason,error=excluded.error,started_at=COALESCE(task_graph_attempts.started_at,excluded.started_at),completed_at=excluded.completed_at,execution_owner=excluded.execution_owner,execution_version=excluded.execution_version WHERE EXISTS (SELECT 1 FROM task_graphs WHERE id=? AND tenant_id=? AND execution_owner=? AND execution_version=? AND lease_until>=CURRENT_TIMESTAMP)`).bind(attempt.id,attempt.graphId,attempt.nodeId,attempt.tenantId,attempt.attemptNumber,attempt.model,attempt.provider||null,attempt.status,attempt.promptTokens||0,attempt.completionTokens||0,attempt.costCents||0,attempt.qualityScore??null,attempt.escalationReason||null,attempt.error||null,startedAt,attempt.completedAt||null,fence.owner,fence.fenceVersion,attempt.graphId,attempt.tenantId,fence.owner,fence.fenceVersion).run();if(!result.meta?.changes){await assertExecutionFence(db,attempt.tenantId,attempt.graphId,fence);throw new Error('Execution attempt side effect was not applied');}}

export async function recordFencedUsage(db:D1Database,usage:{id:string;tenantId:string;taskId?:string;graphId:string;model:string;provider:string;tokensIn:number;tokensOut:number;costCents:number},fence:ExecutionFence):Promise<boolean>{const result=await db.prepare(`INSERT OR IGNORE INTO usage_records (id,tenant_id,task_id,model,provider,tokens_in,tokens_out,cost_cents,graph_id,execution_owner,execution_version) SELECT ?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM task_graphs WHERE id=? AND tenant_id=? AND execution_owner=? AND execution_version=? AND lease_until>=CURRENT_TIMESTAMP)`).bind(usage.id,usage.tenantId,usage.taskId||null,usage.model,usage.provider,usage.tokensIn,usage.tokensOut,usage.costCents,usage.graphId,fence.owner,fence.fenceVersion,usage.graphId,usage.tenantId,fence.owner,fence.fenceVersion).run();await assertExecutionFence(db,usage.tenantId,usage.graphId,fence);return Boolean(result.meta?.changes);}

export async function reserveFencedBudget(db:D1Database,tenantId:string,graphId:string,referenceId:string,amountCents:number,fence:ExecutionFence):Promise<boolean>{await assertExecutionFence(db,tenantId,graphId,fence);const amount=Math.max(1,Math.ceil(amountCents));await db.prepare(`INSERT INTO budget_reservations (id,tenant_id,reference_id,amount_cents,status,graph_id,execution_owner,execution_version) SELECT ?,?,?,?,?,?,?,? WHERE ? <= (COALESCE((SELECT monthly_budget_cents FROM tenants WHERE id=?),10000)-COALESCE((SELECT SUM(cost_cents) FROM usage_records WHERE tenant_id=? AND created_at>=datetime('now','start of month')),0)-COALESCE((SELECT SUM(amount_cents) FROM budget_reservations WHERE tenant_id=? AND status='reserved' AND created_at>=datetime('now','start of month')),0)) ON CONFLICT(tenant_id,reference_id) DO NOTHING`).bind(crypto.randomUUID(),tenantId,referenceId,amount,'reserved',graphId,fence.owner,fence.fenceVersion,amount,tenantId,tenantId,tenantId).run();await assertExecutionFence(db,tenantId,graphId,fence);const row=await db.prepare(`SELECT status FROM budget_reservations WHERE tenant_id=? AND reference_id=?`).bind(tenantId,referenceId).first<{status:string}>();return row?.status==='reserved';}

export async function releaseFencedBudget(db:D1Database,tenantId:string,graphId:string,referenceId:string,fence:ExecutionFence):Promise<void>{const result=await db.prepare(`UPDATE budget_reservations SET status='released',released_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND graph_id=? AND reference_id=? AND status='reserved' AND execution_owner=? AND execution_version=?`).bind(tenantId,graphId,referenceId,fence.owner,fence.fenceVersion).run();await assertExecutionFence(db,tenantId,graphId,fence);if(!result.meta?.changes){const row=await db.prepare(`SELECT status FROM budget_reservations WHERE tenant_id=? AND reference_id=?`).bind(tenantId,referenceId).first<{status:string}>();if(row?.status==='reserved')throw new Error('Budget reservation fence mismatch');}}

export async function applyFencedRuntimeResult(db:D1Database,result:RuntimeSideEffect,fence:ExecutionFence):Promise<void>{await assertExecutionFence(db,result.tenantId,result.graphId,fence);const nodeStatus=result.status==='succeeded'?'completed':result.status==='failed'?'failed':'awaiting-runtime';const batch=await db.batch([db.prepare(`INSERT INTO graph_runtime_results (id,tenant_id,graph_id,node_id,attempt_number,job_id,status,exit_code,output,execution_owner,execution_version) VALUES (?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(graph_id,node_id,attempt_number) DO UPDATE SET job_id=excluded.job_id,status=excluded.status,exit_code=excluded.exit_code,output=excluded.output,execution_owner=excluded.execution_owner,execution_version=excluded.execution_version,updated_at=CURRENT_TIMESTAMP WHERE EXISTS (SELECT 1 FROM task_graphs WHERE id=? AND tenant_id=? AND execution_owner=? AND execution_version=? AND lease_until>=CURRENT_TIMESTAMP)`).bind(result.id,result.tenantId,result.graphId,result.nodeId,result.attemptNumber,result.jobId,result.status,result.exitCode??null,result.output??null,fence.owner,fence.fenceVersion,result.graphId,result.tenantId,fence.owner,fence.fenceVersion),db.prepare(`UPDATE task_graph_nodes SET runtime_job_id=?,output=?,status=?,error=?,completed_at=CASE WHEN ? IN ('completed','failed') THEN CURRENT_TIMESTAMP ELSE completed_at END,updated_at=CURRENT_TIMESTAMP WHERE graph_id=? AND id=? AND tenant_id=? AND EXISTS (SELECT 1 FROM task_graphs WHERE id=? AND tenant_id=? AND execution_owner=? AND execution_version=? AND lease_until>=CURRENT_TIMESTAMP)`).bind(result.jobId,result.output||null,nodeStatus,result.status==='failed'?(result.output||'Runtime job failed'):null,nodeStatus,result.graphId,result.nodeId,result.tenantId,result.graphId,result.tenantId,fence.owner,fence.fenceVersion)]);if(!batch[1]?.meta?.changes){await assertExecutionFence(db,result.tenantId,result.graphId,fence);throw new Error('Runtime result side effect was not applied');}}
