import type { D1Database } from '@cloudflare/workers-types';

export type ContradictionCategory='integrity'|'concurrency'|'planning'|'external_uncertainty';
export interface ExecutionContradictionInput { tenantId:string; graphId:string; nodeId?:string; category:ContradictionCategory; message:string; expectedState?:unknown; observedState?:unknown; }
export interface ExecutionContradictionRecord extends ExecutionContradictionInput { id:string; status:'open'|'resolved'; createdAt:string; resolvedAt?:string; }

type Row={id:string;tenant_id:string;graph_id:string;node_id:string|null;category:ContradictionCategory;message:string;expected_state_json:string|null;observed_state_json:string|null;status:'open'|'resolved';created_at:string;resolved_at:string|null};
function json(value:unknown):string|null{if(value===undefined)return null;return JSON.stringify(value).slice(0,20000)}
function map(row:Row):ExecutionContradictionRecord{return{id:row.id,tenantId:row.tenant_id,graphId:row.graph_id,nodeId:row.node_id??undefined,category:row.category,message:row.message,status:row.status,expectedState:row.expected_state_json?JSON.parse(row.expected_state_json):undefined,observedState:row.observed_state_json?JSON.parse(row.observed_state_json):undefined,createdAt:row.created_at,resolvedAt:row.resolved_at??undefined}}

export async function recordExecutionContradiction(db:D1Database,input:ExecutionContradictionInput):Promise<ExecutionContradictionRecord>{const message=input.message.slice(0,4000);const row=await db.prepare(`INSERT INTO execution_contradictions (id,tenant_id,graph_id,node_id,category,message,expected_state_json,observed_state_json) VALUES (?,?,?,?,?,?,?,?) RETURNING *`).bind(crypto.randomUUID(),input.tenantId,input.graphId,input.nodeId??null,input.category,message,json(input.expectedState),json(input.observedState)).first<Row>();if(!row)throw new Error('Failed to persist execution contradiction');return map(row)}
export async function listOpenExecutionContradictions(db:D1Database,tenantId:string,graphId:string):Promise<ExecutionContradictionRecord[]>{const rows=await db.prepare(`SELECT * FROM execution_contradictions WHERE tenant_id=? AND graph_id=? AND status='open' ORDER BY created_at ASC`).bind(tenantId,graphId).all<Row>();return(rows.results??[]).map(map)}
export async function resolveExecutionContradiction(db:D1Database,tenantId:string,id:string):Promise<ExecutionContradictionRecord>{const row=await db.prepare(`UPDATE execution_contradictions SET status='resolved',resolved_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=? AND status='open' RETURNING *`).bind(tenantId,id).first<Row>();if(!row)throw new Error('Execution contradiction not found or already resolved');return map(row)}

export function classifyExecutionContradiction(error:unknown):{category:ContradictionCategory;message:string}|null{const message=error instanceof Error?error.message:String(error);if(/execution lease lost|fence|stale owner|version conflict|terminal .*unresolved|unresolved .*side effect|illegal .*transition|idempotency key .*bound|expected version/i.test(message))return{category:/lease|fence|stale owner/i.test(message)?'concurrency':/idempotency|version|illegal .*transition|terminal .*unresolved|unresolved .*side effect/i.test(message)?'integrity':'planning',message};return null}
