import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { getPlatformProxy } from 'wrangler';
import type { D1Database } from '@cloudflare/workers-types';
import { resolve } from 'node:path';
import type { TaskGraph } from '@ai-work-partner/shared';
import { applyCurrentD1Schema } from '../test/d1-bootstrap';
import { recordExecutionContradiction, listOpenExecutionContradictions, resolveExecutionContradiction } from './execution-contradictions';
import { persistGraph } from './graph-persistence';

describe('execution contradiction ledger D1 integration',()=>{
  let db:D1Database; let dispose:(()=>Promise<void>)|undefined;
  beforeAll(async()=>{const platform=await getPlatformProxy({configPath:resolve(process.cwd(),'wrangler.test.jsonc'),persist:false});db=platform.env.DB as D1Database;dispose=platform.dispose;await applyCurrentD1Schema(db,resolve(process.cwd()));await db.prepare('INSERT INTO tenants(id,name,email,api_key_hash) VALUES(?,?,?,?)').bind('contradiction-tenant','Contradictions','contradiction@example.test','contradiction-hash').run();await db.prepare('INSERT INTO tasks(id,tenant_id,prompt,status) VALUES(?,?,?,?)').bind('contradiction-root','contradiction-tenant','contradiction graph','processing').run();});
  afterAll(async()=>{await dispose?.()});
  it('persists, lists, and resolves a contradiction without losing evidence',async()=>{const graph:TaskGraph={id:'contradiction-graph',rootTaskId:'contradiction-root',goal:'contradiction graph',createdAt:new Date().toISOString(),nodes:[{id:'node',title:'Node',prompt:'work',domain:'general',complexity:1,expectedFormat:'markdown',recommendedTier:1,dependencies:[],contextFrom:[],status:'ready',attemptedModels:[]}]};await persistGraph(db,'contradiction-tenant',graph);const created=await recordExecutionContradiction(db,{tenantId:'contradiction-tenant',graphId:graph.id,nodeId:'node',category:'concurrency',message:'Graph execution lease lost',expectedState:{owner:'worker-a',generation:7},observedState:{owner:'worker-b',generation:8}});expect(created.status).toBe('open');expect(created.expectedState).toEqual({owner:'worker-a',generation:7});const open=await listOpenExecutionContradictions(db,'contradiction-tenant',graph.id);expect(open).toHaveLength(1);expect(open[0].observedState).toEqual({owner:'worker-b',generation:8});const resolved=await resolveExecutionContradiction(db,'contradiction-tenant',created.id);expect(resolved.status).toBe('resolved');expect(resolved.resolvedAt).toBeTruthy();expect(await listOpenExecutionContradictions(db,'contradiction-tenant',graph.id)).toHaveLength(0);const stored=await db.prepare('SELECT status,expected_state_json,observed_state_json FROM execution_contradictions WHERE id=? AND tenant_id=?').bind(created.id,'contradiction-tenant').first<{status:string;expected_state_json:string;observed_state_json:string}>();expect(stored?.status).toBe('resolved');expect(JSON.parse(stored!.expected_state_json)).toEqual({owner:'worker-a',generation:7});expect(JSON.parse(stored!.observed_state_json)).toEqual({owner:'worker-b',generation:8});});
});
