import { describe, expect, it, beforeAll, afterAll } from 'vitest';
import { getPlatformProxy } from 'wrangler';
import type { D1Database } from '@cloudflare/workers-types';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { assertExecutionFence, recordFencedAttempt, recordFencedUsage, reserveFencedBudget, releaseFencedBudget, reclaimStaleBudgetReservations, applyFencedRuntimeResult } from './execution-side-effects';

const testDir=dirname(fileURLToPath(import.meta.url));
const engineRoot=resolve(testDir,'../..');
const execSqlFile=async(db:D1Database,path:string)=>{const sql=await readFile(path,'utf8');for(const statement of sql.replace(/^\uFEFF/,'').replace(/^[\t ]*--[^\r\n]*(?:\r?\n|$)/gm,'').split(';').map(s=>s.trim()).filter(Boolean))await db.prepare(statement).run();};

describe('execution side-effect fencing D1 integration',()=>{
 let db:D1Database;let dispose:(()=>Promise<void>)|undefined;
 beforeAll(async()=>{const platform=await getPlatformProxy({configPath:resolve(engineRoot,'wrangler.test.jsonc'),persist:false});db=platform.env.DB as D1Database;dispose=platform.dispose;await execSqlFile(db,resolve(testDir,'../db/schema.sql'));for(const migration of ['0002_task_graph_persistence.sql','0003_graph_durable_execution.sql','0004_budget_reservations.sql','0010_graph_node_approvals.sql','0011_runtime_job_linkage.sql','0012_graph_node_tool_persistence.sql','0013_graph_verification_repair.sql','0015_execution_side_effect_fencing.sql'])await execSqlFile(db,resolve(engineRoot,'migrations',migration));await db.prepare(`INSERT INTO tenants(id,name,email,api_key_hash,monthly_budget_cents) VALUES(?,?,?,?,?)`).bind('tenant-side','Side effects','side@test','hash-side',100).run();await db.prepare(`INSERT INTO tasks(id,tenant_id,prompt,status) VALUES(?,?,?,?)`).bind('root-side','tenant-side','side effects','processing').run();await db.prepare(`INSERT INTO task_graphs(id,tenant_id,root_task_id,goal,status,execution_version,execution_owner,lease_until) VALUES(?,?,?,?,?,?,?,datetime('now','+120 seconds'))`).bind('graph-side','tenant-side','root-side','side effects','running',2,'owner-current').run();await db.prepare(`INSERT INTO task_graph_nodes(id,graph_id,tenant_id,title,prompt,domain,complexity,expected_format,recommended_tier,dependencies_json,context_from_json,status,attempted_models_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind('node-side','graph-side','tenant-side','Node','Do work','general',1,'markdown',1,'[]','[]','ready','[]').run();});
 afterAll(async()=>{await dispose?.();});
 const current={owner:'owner-current',fenceVersion:2};const stale={owner:'owner-stale',fenceVersion:1};
 it('accepts current fenced attempt and makes repeated identity idempotent',async()=>{const attempt={id:'attempt-side',graphId:'graph-side',nodeId:'node-side',tenantId:'tenant-side',attemptNumber:1,model:'gpt-4o-mini',provider:'openai',status:'completed' as const,promptTokens:10,completionTokens:20,costCents:4,qualityScore:90};await recordFencedAttempt(db,attempt,current);await recordFencedAttempt(db,{...attempt,qualityScore:95});const rows=await db.prepare(`SELECT COUNT(*) AS count,MAX(quality_score) AS quality FROM task_graph_attempts WHERE graph_id=?`).bind('graph-side').first<{count:number;quality:number}>();expect(rows?.count).toBe(1);expect(rows?.quality).toBe(95);});
 it('rejects stale attempt and usage writes after reclaim',async()=>{await expect(recordFencedAttempt(db,{id:'attempt-stale',graphId:'graph-side',nodeId:'node-side',tenantId:'tenant-side',attemptNumber:2,model:'gpt-4o-mini',status:'running'},stale)).rejects.toThrow('Graph execution lease lost');await expect(recordFencedUsage(db,{id:'usage-stale',tenantId:'tenant-side',taskId:'root-side',graphId:'graph-side',model:'gpt-4o-mini',provider:'openai',tokensIn:1,tokensOut:1,costCents:1},stale)).rejects.toThrow('Graph execution lease lost');const count=await db.prepare(`SELECT COUNT(*) AS count FROM usage_records WHERE id=?`).bind('usage-stale').first<{count:number}>();expect(count?.count).toBe(0);});
 it('does not double-spend a budget reservation on repeated retry',async()=>{const first=await reserveFencedBudget(db,'tenant-side','graph-side','attempt-budget',10,current);const second=await reserveFencedBudget(db,'tenant-side','graph-side','attempt-budget',10,current);expect(first).toBe(true);expect(second).toBe(true);const row=await db.prepare(`SELECT COUNT(*) AS count,SUM(amount_cents) AS total FROM budget_reservations WHERE tenant_id=? AND reference_id=?`).bind('tenant-side','attempt-budget').first<{count:number;total:number}>();expect(row?.count).toBe(1);expect(row?.total).toBe(10);await releaseFencedBudget(db,'tenant-side','graph-side','attempt-budget',current);});
 it('rejects stale budget release after a new owner takes the generation',async()=>{await db.prepare(`INSERT INTO budget_reservations(id,tenant_id,reference_id,amount_cents,status,graph_id,execution_owner,execution_version) VALUES(?,?,?,?,?,?,?,?)`).bind('reservation-stale','tenant-side','attempt-stale-budget',10,'reserved','graph-side','owner-current',2).run();await db.prepare(`UPDATE task_graphs SET execution_owner=?,execution_version=?,lease_until=datetime('now','+120 seconds') WHERE id=?`).bind('owner-new',3,'graph-side').run();await expect(releaseFencedBudget(db,'tenant-side','graph-side','attempt-stale-budget',current)).rejects.toThrow('Graph execution lease lost');const row=await db.prepare(`SELECT status FROM budget_reservations WHERE reference_id=?`).bind('attempt-stale-budget').first<{status:string}>();expect(row?.status).toBe('reserved');});
 it('reclaims stale reservations even when a worker keeps the same owner identity',async()=>{await db.prepare(`UPDATE task_graphs SET execution_owner=?,execution_version=?,lease_until=datetime('now','+120 seconds') WHERE id=?`).bind('owner-current',4,'graph-side').run();await db.prepare(`INSERT INTO budget_reservations(id,tenant_id,reference_id,amount_cents,status,graph_id,execution_owner,execution_version) VALUES(?,?,?,?,?,?,?,?)`).bind('reservation-generation','tenant-side','attempt-generation',10,'reserved','graph-side','owner-current',2).run();const reclaimed=await reclaimStaleBudgetReservations(db,'tenant-side','graph-side');expect(reclaimed).toBe(1);const row=await db.prepare(`SELECT status FROM budget_reservations WHERE reference_id=?`).bind('tenant-side','attempt-generation').first<{status:string}>();expect(row?.status).toBe('released');});
 it('applies runtime result atomically for current generation and blocks stale result',async()=>{await db.prepare(`UPDATE task_graphs SET execution_owner=?,execution_version=?,lease_until=datetime('now','+120 seconds') WHERE id=?`).bind('owner-current',2,'graph-side').run();await applyFencedRuntimeResult(db,{id:'runtime-result',graphId:'graph-side',nodeId:'node-side',tenantId:'tenant-side',attemptNumber:3,jobId:'job-1',status:'succeeded',output:'done'},current);const node=await db.prepare(`SELECT status,runtime_job_id,output FROM task_graph_nodes WHERE graph_id=? AND id=?`).bind('graph-side','node-side').first<{status:string;runtime_job_id:string;output:string}>();expect(node?.status).toBe('completed');expect(node?.runtime_job_id).toBe('job-1');expect(node?.output).toBe('done');await db.prepare(`UPDATE task_graphs SET execution_owner=?,execution_version=?,lease_until=datetime('now','+120 seconds') WHERE id=?`).bind('owner-new',3,'graph-side').run();await expect(applyFencedRuntimeResult(db,{id:'runtime-stale',graphId:'graph-side',nodeId:'node-side',tenantId:'tenant-side',attemptNumber:3,jobId:'job-stale',status:'succeeded',output:'stale'},current)).rejects.toThrow('Graph execution lease lost');const unchanged=await db.prepare(`SELECT runtime_job_id,output FROM task_graph_nodes WHERE graph_id=? AND id=?`).bind('graph-side','node-side').first<{runtime_job_id:string;output:string}>();expect(unchanged?.runtime_job_id).toBe('job-1');expect(unchanged?.output).toBe('done');});
 it('proves tenant isolation at the fence boundary',async()=>{await expect(assertExecutionFence(db,'other-tenant','graph-side',current)).rejects.toThrow('Graph execution lease lost');});
});
