import type { D1Database } from '@cloudflare/workers-types';

export type DiagnosisStatus='proposed'|'accepted'|'rejected';
export type CorrectiveActionStatus='proposed'|'approved'|'executing'|'completed'|'failed'|'cancelled';
export type PlanRevisionStatus='proposed'|'active'|'superseded'|'rejected';
export type ValidationResult='passed'|'failed'|'inconclusive';

type DiagnosisRow={id:string;tenant_id:string;graph_id:string;contradiction_id:string;diagnosis:string;confidence:number;evidence_json:string|null;status:DiagnosisStatus;created_at:string;decided_at:string|null};
type ActionRow={id:string;tenant_id:string;graph_id:string;diagnosis_id:string;action:string;action_input_json:string|null;status:CorrectiveActionStatus;created_at:string;started_at:string|null;completed_at:string|null;error:string|null};
type RevisionRow={id:string;tenant_id:string;graph_id:string;contradiction_id:string;corrective_action_id:string;previous_plan_hash:string|null;revised_plan_json:string;reason:string;status:PlanRevisionStatus;created_at:string;activated_at:string|null;superseded_at:string|null};
type ValidationRow={id:string;tenant_id:string;graph_id:string;contradiction_id:string;plan_revision_id:string;expected_state_json:string|null;observed_state_json:string|null;result:ValidationResult;validation_message:string;created_at:string};

export interface ExecutionDiagnosis { id:string;tenantId:string;graphId:string;contradictionId:string;diagnosis:string;confidence:number;evidence?:unknown;status:DiagnosisStatus;createdAt:string;decidedAt?:string; }
export interface ExecutionCorrectiveAction { id:string;tenantId:string;graphId:string;diagnosisId:string;action:string;actionInput?:unknown;status:CorrectiveActionStatus;createdAt:string;startedAt?:string;completedAt?:string;error?:string; }
export interface ExecutionPlanRevision { id:string;tenantId:string;graphId:string;contradictionId:string;correctiveActionId:string;previousPlanHash?:string;revisedPlan:unknown;reason:string;status:PlanRevisionStatus;createdAt:string;activatedAt?:string;supersededAt?:string; }
export interface ExecutionValidation { id:string;tenantId:string;graphId:string;contradictionId:string;planRevisionId:string;expectedState?:unknown;observedState?:unknown;result:ValidationResult;validationMessage:string;createdAt:string; }

function json(value:unknown):string|null{return value===undefined?null:JSON.stringify(value).slice(0,20000)}
function parse(value:string|null):unknown{return value?JSON.parse(value):undefined}
function diagnosis(row:DiagnosisRow):ExecutionDiagnosis{return{id:row.id,tenantId:row.tenant_id,graphId:row.graph_id,contradictionId:row.contradiction_id,diagnosis:row.diagnosis,confidence:row.confidence,evidence:parse(row.evidence_json),status:row.status,createdAt:row.created_at,decidedAt:row.decided_at??undefined}}
function action(row:ActionRow):ExecutionCorrectiveAction{return{id:row.id,tenantId:row.tenant_id,graphId:row.graph_id,diagnosisId:row.diagnosis_id,action:row.action,actionInput:parse(row.action_input_json),status:row.status,createdAt:row.created_at,startedAt:row.started_at??undefined,completedAt:row.completed_at??undefined,error:row.error??undefined}}
function revision(row:RevisionRow):ExecutionPlanRevision{return{id:row.id,tenantId:row.tenant_id,graphId:row.graph_id,contradictionId:row.contradiction_id,correctiveActionId:row.corrective_action_id,previousPlanHash:row.previous_plan_hash??undefined,revisedPlan:JSON.parse(row.revised_plan_json),reason:row.reason,status:row.status,createdAt:row.created_at,activatedAt:row.activated_at??undefined,supersededAt:row.superseded_at??undefined}}
function validation(row:ValidationRow):ExecutionValidation{return{id:row.id,tenantId:row.tenant_id,graphId:row.graph_id,contradictionId:row.contradiction_id,planRevisionId:row.plan_revision_id,expectedState:parse(row.expected_state_json),observedState:parse(row.observed_state_json),result:row.result,validationMessage:row.validation_message,createdAt:row.created_at}}
function text(value:string,label:string,max:number):string{const v=value.trim();if(!v||v.length>max)throw new Error(`Invalid ${label}`);return v}

export async function proposeExecutionDiagnosis(db:D1Database,input:{tenantId:string;graphId:string;contradictionId:string;diagnosis:string;confidence:number;evidence?:unknown}):Promise<ExecutionDiagnosis>{if(!Number.isFinite(input.confidence)||input.confidence<0||input.confidence>1)throw new Error('Diagnosis confidence must be between 0 and 1');const contradiction=await db.prepare("SELECT id FROM execution_contradictions WHERE id=? AND tenant_id=? AND graph_id=? AND status='open'").bind(input.contradictionId,input.tenantId,input.graphId).first<{id:string}>();if(!contradiction)throw new Error('Open execution contradiction not found');const row=await db.prepare('INSERT INTO execution_diagnoses(id,tenant_id,graph_id,contradiction_id,diagnosis,confidence,evidence_json) VALUES(?,?,?,?,?,?,?) RETURNING *').bind(crypto.randomUUID(),input.tenantId,input.graphId,input.contradictionId,text(input.diagnosis,'diagnosis',12000),input.confidence,json(input.evidence)).first<DiagnosisRow>();if(!row)throw new Error('Failed to persist execution diagnosis');return diagnosis(row)}
export async function acceptExecutionDiagnosis(db:D1Database,tenantId:string,id:string):Promise<ExecutionDiagnosis>{const row=await db.prepare("UPDATE execution_diagnoses SET status='accepted',decided_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=? AND status='proposed' RETURNING *").bind(id,tenantId).first<DiagnosisRow>();if(!row)throw new Error('Execution diagnosis not found or not proposed');return diagnosis(row)}
export async function rejectExecutionDiagnosis(db:D1Database,tenantId:string,id:string):Promise<ExecutionDiagnosis>{const row=await db.prepare("UPDATE execution_diagnoses SET status='rejected',decided_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=? AND status='proposed' RETURNING *").bind(id,tenantId).first<DiagnosisRow>();if(!row)throw new Error('Execution diagnosis not found or not proposed');return diagnosis(row)}

export async function proposeCorrectiveAction(db:D1Database,input:{tenantId:string;graphId:string;diagnosisId:string;action:string;actionInput?:unknown}):Promise<ExecutionCorrectiveAction>{const d=await db.prepare("SELECT id FROM execution_diagnoses WHERE id=? AND tenant_id=? AND graph_id=? AND status='accepted'").bind(input.diagnosisId,input.tenantId,input.graphId).first<{id:string}>();if(!d)throw new Error('Accepted execution diagnosis not found');const row=await db.prepare('INSERT INTO execution_corrective_actions(id,tenant_id,graph_id,diagnosis_id,action,action_input_json) VALUES(?,?,?,?,?,?) RETURNING *').bind(crypto.randomUUID(),input.tenantId,input.graphId,input.diagnosisId,text(input.action,'corrective action',12000),json(input.actionInput)).first<ActionRow>();if(!row)throw new Error('Failed to persist corrective action');return action(row)}
export async function approveCorrectiveAction(db:D1Database,tenantId:string,id:string):Promise<ExecutionCorrectiveAction>{const row=await db.prepare("UPDATE execution_corrective_actions SET status='approved' WHERE id=? AND tenant_id=? AND status='proposed' RETURNING *").bind(id,tenantId).first<ActionRow>();if(!row)throw new Error('Corrective action not found or not proposed');return action(row)}
export async function startCorrectiveAction(db:D1Database,tenantId:string,id:string):Promise<ExecutionCorrectiveAction>{const row=await db.prepare("UPDATE execution_corrective_actions SET status='executing',started_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=? AND status='approved' RETURNING *").bind(id,tenantId).first<ActionRow>();if(!row)throw new Error('Corrective action not found or not approved');return action(row)}
export async function completeCorrectiveAction(db:D1Database,tenantId:string,id:string):Promise<ExecutionCorrectiveAction>{const row=await db.prepare("UPDATE execution_corrective_actions SET status='completed',completed_at=CURRENT_TIMESTAMP,error=NULL WHERE id=? AND tenant_id=? AND status='executing' RETURNING *").bind(id,tenantId).first<ActionRow>();if(!row)throw new Error('Corrective action not found or not executing');return action(row)}
export async function failCorrectiveAction(db:D1Database,tenantId:string,id:string,error:string):Promise<ExecutionCorrectiveAction>{const row=await db.prepare("UPDATE execution_corrective_actions SET status='failed',completed_at=CURRENT_TIMESTAMP,error=? WHERE id=? AND tenant_id=? AND status='executing' RETURNING *").bind(text(error,'corrective action error',4000),id,tenantId).first<ActionRow>();if(!row)throw new Error('Corrective action not found or not executing');return action(row)}

export async function proposeExecutionPlanRevision(db:D1Database,input:{tenantId:string;graphId:string;contradictionId:string;correctiveActionId:string;previousPlanHash?:string;revisedPlan:unknown;reason:string}):Promise<ExecutionPlanRevision>{const actionRow=await db.prepare("SELECT id FROM execution_corrective_actions WHERE id=? AND tenant_id=? AND graph_id=? AND status='completed'").bind(input.correctiveActionId,input.tenantId,input.graphId).first<{id:string}>();if(!actionRow)throw new Error('Completed corrective action not found');const contradiction=await db.prepare("SELECT id FROM execution_contradictions WHERE id=? AND tenant_id=? AND graph_id=? AND status='open'").bind(input.contradictionId,input.tenantId,input.graphId).first<{id:string}>();if(!contradiction)throw new Error('Open execution contradiction not found');const revised=JSON.stringify(input.revisedPlan)??'';if(!revised||revised.length>20000)throw new Error('Revised execution plan is invalid or too large');const row=await db.prepare('INSERT INTO execution_plan_revisions(id,tenant_id,graph_id,contradiction_id,corrective_action_id,previous_plan_hash,revised_plan_json,reason) VALUES(?,?,?,?,?,?,?,?) RETURNING *').bind(crypto.randomUUID(),input.tenantId,input.graphId,input.contradictionId,input.correctiveActionId,input.previousPlanHash??null,revised,text(input.reason,'plan revision reason',12000)).first<RevisionRow>();if(!row)throw new Error('Failed to persist execution plan revision');return revision(row)}
export async function activateExecutionPlanRevision(db:D1Database,tenantId:string,id:string):Promise<ExecutionPlanRevision>{const candidate=await db.prepare("SELECT * FROM execution_plan_revisions WHERE id=? AND tenant_id=? AND status='proposed'").bind(id,tenantId).first<RevisionRow>();if(!candidate)throw new Error('Execution plan revision not found or not proposed');await db.batch([db.prepare("UPDATE execution_plan_revisions SET status='superseded',superseded_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND graph_id=? AND status='active'").bind(tenantId,candidate.graph_id),db.prepare("UPDATE execution_plan_revisions SET status='active',activated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=? AND status='proposed'").bind(id,tenantId)]);const row=await db.prepare('SELECT * FROM execution_plan_revisions WHERE id=? AND tenant_id=?').bind(id,tenantId).first<RevisionRow>();if(!row)throw new Error('Activated execution plan revision disappeared');return revision(row)}
export async function recordExecutionValidation(db:D1Database,input:{tenantId:string;graphId:string;contradictionId:string;planRevisionId:string;expectedState?:unknown;observedState?:unknown;result:ValidationResult;validationMessage:string}):Promise<ExecutionValidation>{const rev=await db.prepare("SELECT id FROM execution_plan_revisions WHERE id=? AND tenant_id=? AND graph_id=? AND status='active'").bind(input.planRevisionId,input.tenantId,input.graphId).first<{id:string}>();if(!rev)throw new Error('Active execution plan revision not found');const contradiction=await db.prepare("SELECT id FROM execution_contradictions WHERE id=? AND tenant_id=? AND graph_id=? AND status='open'").bind(input.contradictionId,input.tenantId,input.graphId).first<{id:string}>();if(!contradiction)throw new Error('Open execution contradiction not found');const row=await db.prepare('INSERT INTO execution_validations(id,tenant_id,graph_id,contradiction_id,plan_revision_id,expected_state_json,observed_state_json,result,validation_message) VALUES(?,?,?,?,?,?,?,?,?) RETURNING *').bind(crypto.randomUUID(),input.tenantId,input.graphId,input.contradictionId,input.planRevisionId,json(input.expectedState),json(input.observedState),input.result,text(input.validationMessage,'validation message',12000)).first<ValidationRow>();if(!row)throw new Error('Failed to persist execution validation');return validation(row)}
