import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { getPlatformProxy } from 'wrangler';
import type { D1Database } from '@cloudflare/workers-types';
import { resolve } from 'node:path';
import type { TaskGraph } from '@ai-work-partner/shared';
import { applyCurrentD1Schema } from '../test/d1-bootstrap';
import { persistGraph } from './graph-persistence';
import { recordExecutionContradiction } from './execution-contradictions';
import { proposeExecutionDiagnosis, acceptExecutionDiagnosis, proposeCorrectiveAction, approveCorrectiveAction, startCorrectiveAction, completeCorrectiveAction, proposeExecutionPlanRevision, activateExecutionPlanRevision, recordExecutionValidation } from './execution-correction-loop';
import { resolveValidatedExecutionContradiction } from './execution-correction-finalization-v2';

describe('execution correction loop D1 integration',()=>{
  let db:D1Database; let dispose:(()=>Promise<void>)|undefined;
  beforeAll(async()=>{const platform=await getPlatformProxy({configPath:resolve(process.cwd(),'wrangler.test.jsonc'),persist:false});db=platform.env.DB as D1Database;dispose=platform.dispose;await applyCurrentD1Schema(db,resolve(process.cwd()));await db.prepare('INSERT INTO tenants(id,name,email,api_key_hash) VALUES(?,?,?,?)').bind('correction-tenant','Correction','correction@example.test','correction-hash').run();await db.prepare('INSERT INTO tasks(id,tenant_id,prompt,status) VALUES(?,?,?,?)').bind('correction-root','correction-tenant','correction graph','processing').run();});
  afterAll(async()=>{await dispose?.()});

  async function setup(prefix:string){const graph:TaskGraph={id:`${prefix}-graph`,rootTaskId:'correction-root',goal:'correction graph',createdAt:new Date().toISOString(),nodes:[{id:`${prefix}-node`,title:'Node',prompt:'work',domain:'general',complexity:1,expectedFormat:'markdown',recommendedTier:1,dependencies:[],contextFrom:[],status:'ready',attemptedModels:[]}]};await persistGraph(db,'correction-tenant',graph);const contradiction=await recordExecutionContradiction(db,{tenantId:'correction-tenant',graphId:graph.id,nodeId:`${prefix}-node`,category:'integrity',message:'Observed state contradicts expected state',expectedState:{version:3},observedState:{version:4}});const d=await proposeExecutionDiagnosis(db,{tenantId:'correction-tenant',graphId:graph.id,contradictionId:contradiction.id,diagnosis:'Worker planned against stale state',confidence:0.97,evidence:{expectedVersion:3,observedVersion:4}});await acceptExecutionDiagnosis(db,'correction-tenant',d.id);const a=await proposeCorrectiveAction(db,{tenantId:'correction-tenant',graphId:graph.id,diagnosisId:d.id,action:'Refresh state and rebuild plan',executorPrincipal:'worker:correction'});await approveCorrectiveAction(db,'correction-tenant',a.id);await startCorrectiveAction(db,'correction-tenant',a.id);await completeCorrectiveAction(db,'correction-tenant',a.id);const r=await proposeExecutionPlanRevision(db,{tenantId:'correction-tenant',graphId:graph.id,contradictionId:contradiction.id,correctiveActionId:a.id,previousPlanHash:'old-plan',revisedPlan:{nodes:['replanned-node'],reason:'version refresh'},reason:'Re-plan from observed state'});const active=await activateExecutionPlanRevision(db,'correction-tenant',r.id);return{graph,contradiction,active};}

  it('durably walks contradiction -> diagnosis -> action -> revision -> independent validation -> resolution',async()=>{const {graph,contradiction,active}=await setup('happy');const validation=await recordExecutionValidation(db,{tenantId:'correction-tenant',graphId:graph.id,contradictionId:contradiction.id,planRevisionId:active.id,expectedState:{version:4},observedState:{version:4},result:'passed',validationMessage:'Replanned execution matches observed state',validatorPrincipal:'validator:independent'});await resolveValidatedExecutionContradiction(db,{tenantId:'correction-tenant',graphId:graph.id,contradictionId:contradiction.id,validationId:validation.id,resolutionReason:'Independent validation confirmed the revised plan against observed state'});expect(await db.prepare('SELECT status FROM execution_contradictions WHERE id=?').bind(contradiction.id).first<{status:string}>()).toMatchObject({status:'resolved'});expect(await db.prepare('SELECT executor_principal,validator_principal FROM execution_contradiction_resolutions WHERE contradiction_id=?').bind(contradiction.id).first()).toMatchObject({executor_principal:'worker:correction',validator_principal:'validator:independent'});});

  it('rejects failed validation',async()=>{const {graph,contradiction,active}=await setup('failed');const validation=await recordExecutionValidation(db,{tenantId:'correction-tenant',graphId:graph.id,contradictionId:contradiction.id,planRevisionId:active.id,result:'failed',validationMessage:'Observed state still diverges',validatorPrincipal:'validator:independent'});await expect(resolveValidatedExecutionContradiction(db,{tenantId:'correction-tenant',graphId:graph.id,contradictionId:contradiction.id,validationId:validation.id,resolutionReason:'Must not resolve'})).rejects.toThrow();expect(await db.prepare('SELECT status FROM execution_contradictions WHERE id=?').bind(contradiction.id).first<{status:string}>()).toMatchObject({status:'open'});});

  it('rejects inconclusive validation',async()=>{const {graph,contradiction,active}=await setup('inconclusive');const validation=await recordExecutionValidation(db,{tenantId:'correction-tenant',graphId:graph.id,contradictionId:contradiction.id,planRevisionId:active.id,result:'inconclusive',validationMessage:'External state unavailable',validatorPrincipal:'validator:independent'});await expect(resolveValidatedExecutionContradiction(db,{tenantId:'correction-tenant',graphId:graph.id,contradictionId:contradiction.id,validationId:validation.id,resolutionReason:'Must not resolve'})).rejects.toThrow();});

  it('rejects self-validation',async()=>{const {graph,contradiction,active}=await setup('self');const validation=await recordExecutionValidation(db,{tenantId:'correction-tenant',graphId:graph.id,contradictionId:contradiction.id,planRevisionId:active.id,result:'passed',validationMessage:'Executor claims success',validatorPrincipal:'worker:correction'});await expect(resolveValidatedExecutionContradiction(db,{tenantId:'correction-tenant',graphId:graph.id,contradictionId:contradiction.id,validationId:validation.id,resolutionReason:'Must require independent validator'})).rejects.toThrow();expect(await db.prepare('SELECT status FROM execution_contradictions WHERE id=?').bind(contradiction.id).first<{status:string}>()).toMatchObject({status:'open'});});

  it('cannot resolve through the legacy direct resolver',async()=>{const {graph,contradiction}=await setup('legacy');await expect(db.prepare("UPDATE execution_contradictions SET status='resolved' WHERE id=? AND tenant_id=? AND status='open'").bind(contradiction.id,'correction-tenant').run()).rejects.toThrow();expect(await db.prepare('SELECT status FROM execution_contradictions WHERE id=?').bind(contradiction.id).first<{status:string}>()).toMatchObject({status:'open'});});

  it('preserves original contradiction evidence after resolution',async()=>{const {graph,contradiction,active}=await setup('evidence');const validation=await recordExecutionValidation(db,{tenantId:'correction-tenant',graphId:graph.id,contradictionId:contradiction.id,planRevisionId:active.id,expectedState:{version:4},observedState:{version:4},result:'passed',validationMessage:'Independent validation passed',validatorPrincipal:'validator:independent'});await resolveValidatedExecutionContradiction(db,{tenantId:'correction-tenant',graphId:graph.id,contradictionId:contradiction.id,validationId:validation.id,resolutionReason:'Validated repaired state'});const row=await db.prepare('SELECT category,message,expected_state_json,observed_state_json,status FROM execution_contradictions WHERE id=?').bind(contradiction.id).first<{category:string;message:string;expected_state_json:string;observed_state_json:string;status:string}>();expect(row).toMatchObject({category:'integrity',message:'Observed state contradicts expected state',expected_state_json:'{"version":3}',observed_state_json:'{"version":4}',status:'resolved'});});
});
