import type { D1Database } from '@cloudflare/workers-types';

export interface ExecutionEventInput { id:string; tenantId:string; graphId:string; nodeId?:string; attemptId?:string; executionOwner?:string; executionVersion?:number; eventType:string; status?:string; externalOperationId?:string; details?:Record<string,unknown>; occurredAt?:string; }
export interface ExecutionEventRecord extends ExecutionEventInput { occurredAt:string; }
type Row={id:string;tenant_id:string;graph_id:string;node_id:string|null;attempt_id:string|null;execution_owner:string|null;execution_version:number|null;event_type:string;status:string|null;external_operation_id:string|null;details_json:string;occurred_at:string};
const parse=(value:string)=>{try{const parsed=JSON.parse(value);return parsed&&typeof parsed==='object'&&!Array.isArray(parsed)?parsed as Record<string,unknown>:{};}catch{return{};}};
const map=(r:Row):ExecutionEventRecord=>({id:r.id,tenantId:r.tenant_id,graphId:r.graph_id,nodeId:r.node_id??undefined,attemptId:r.attempt_id??undefined,executionOwner:r.execution_owner??undefined,executionVersion:r.execution_version??undefined,eventType:r.event_type,status:r.status??undefined,externalOperationId:r.external_operation_id??undefined,details:parse(r.details_json),occurredAt:r.occurred_at});
export async function appendExecutionEvent(db:D1Database,input:ExecutionEventInput):Promise<ExecutionEventRecord>{const row=await db.prepare(`INSERT INTO execution_events (id,tenant_id,graph_id,node_id,attempt_id,execution_owner,execution_version,event_type,status,external_operation_id,details_json,occurred_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,COALESCE(?,CURRENT_TIMESTAMP)) RETURNING *`).bind(input.id,input.tenantId,input.graphId,input.nodeId??null,input.attemptId??null,input.executionOwner??null,input.executionVersion??null,input.eventType,input.status??null,input.externalOperationId??null,JSON.stringify(input.details??{}),input.occurredAt??null).first<Row>();if(!row)throw new Error('Execution event append failed');return map(row);}
export async function listExecutionEvents(db:D1Database,tenantId:string,graphId:string,limit=200):Promise<ExecutionEventRecord[]>{const safe=Math.max(1,Math.min(500,Math.trunc(limit)));const rows=await db.prepare(`SELECT * FROM execution_events WHERE tenant_id=? AND graph_id=? ORDER BY occurred_at ASC,id ASC LIMIT ${safe}`).bind(tenantId,graphId).all<Row>();return(rows.results??[]).map(map);}
export async function listAttemptExecutionEvents(db:D1Database,tenantId:string,attemptId:string,limit=100):Promise<ExecutionEventRecord[]>{const safe=Math.max(1,Math.min(500,Math.trunc(limit)));const rows=await db.prepare(`SELECT * FROM execution_events WHERE tenant_id=? AND attempt_id=? ORDER BY occurred_at ASC,id ASC LIMIT ${safe}`).bind(tenantId,attemptId).all<Row>();return(rows.results??[]).map(map);}
