import { describe, expect, it, beforeAll, afterAll } from 'vitest';
import { getPlatformProxy } from 'wrangler';
import { resolve } from 'node:path';
import type { D1Database } from '@cloudflare/workers-types';
import type { TaskGraph } from '@ai-work-partner/shared';
import { applyCurrentD1Schema } from '../test/d1-bootstrap';
import { persistGraph, acquireGraphExecutionLease } from './graph-persistence';
import { registerExecutionRuntime, authorizeRuntimeExecution, markRuntimeExecutionInFlight, completeRuntimeExecution, claimRecoverableRuntimeExecution, listRecoverableRuntimeExecutions } from './execution-runtimes';

describe.sequential('execution runtime fencing D1 integration', () => {
  let db: D1Database; let dispose: (() => Promise<void>) | undefined;
  beforeAll(async () => { const engineRoot=resolve(process.cwd());const platform=await getPlatformProxy({configPath:resolve(engineRoot,'wrangler.test.jsonc'),persist:false});db=platform.env.DB as D1Database;dispose=platform.dispose;await applyCurrentD1Schema(db,engineRoot);await db.prepare(`INSERT INTO tenants (id,name,email,api_key_hash,monthly_budget_cents) VALUES (?,?,?,?,?)`).bind('runtime-tenant','Runtime tests','runtime@example.test','runtime-hash',100).run();for(const [id,prompt] of [['runtime-root','runtime execution test'],['runtime-fence-root','runtime fence test'],['runtime-recovery-root','runtime recovery test']])await db.prepare(`INSERT INTO tasks (id,tenant_id,prompt,status) VALUES (?,?,?,?)`).bind(id,'runtime-tenant',prompt,'processing').run();});
  afterAll(async()=>{await dispose?.();});
  it('requires the runtime to advertise the requested capability',async()=>{await registerExecutionRuntime(db,'runtime-tenant',{id:'desktop-a',tenantId:'runtime-tenant',kind:'desktop_local',state:'online',capabilities:['git.read'],lastHeartbeatAt:new Date().toISOString()});const graph:TaskGraph={id:'runtime-capability-graph',rootTaskId:'runtime-root',goal:'runtime capability',createdAt:new Date().toISOString(),nodes:[{id:'node',title:'Node',prompt:'execute',domain:'general',complexity:1,expectedFormat:'text',recommendedTier:1,dependencies:[],contextFrom:[],status:'ready',attemptedModels:[]}]};await persistGraph(db,'runtime-tenant',graph);const version=await acquireGraphExecutionLease(db,'runtime-tenant',graph.id,'runtime-worker');await expect(authorizeRuntimeExecution(db,'runtime-tenant',{runtimeId:'desktop-a',graphId:graph.id,nodeId:'node',attemptId:'runtime-capability-attempt',executionOwner:'runtime-worker',executionVersion:version!,leaseExpiresAt:new Date(Date.now()+60000).toISOString(),capability:'command.exec',command:'echo',args:['hello']})).rejects.toThrow('lacks the requested capability');});
  it('fences runtime completion to the exact graph owner and generation',async()=>{await registerExecutionRuntime(db,'runtime-tenant',{id:'desktop-b',tenantId:'runtime-tenant',kind:'desktop_local',state:'online',capabilities:['command.exec'],lastHeartbeatAt:new Date().toISOString()});const graph:TaskGraph={id:'runtime-fence-graph',rootTaskId:'runtime-fence-root',goal:'runtime fence',createdAt:new Date().toISOString(),nodes:[{id:'node',title:'Node',prompt:'execute',domain:'general',complexity:1,expectedFormat:'text',recommendedTier:1,dependencies:[],contextFrom:[],status:'ready',attemptedModels:[]}]};await persistGraph(db,'runtime-tenant',graph);const version=await acquireGraphExecutionLease(db,'runtime-tenant',graph.id,'runtime-worker-a');const request={runtimeId:'desktop-b',graphId:graph.id,nodeId:'node',attemptId:'runtime-fence-attempt',executionOwner:'runtime-worker-a',executionVersion:version!,leaseExpiresAt:new Date(Date.now()+60000).toISOString(),capability:'command.exec' as const,command:'echo',args:['hello']};await authorizeRuntimeExecution(db,'runtime-tenant',request);await markRuntimeExecutionInFlight(db,'runtime-tenant',request);await db.prepare(`UPDATE task_graphs SET execution_owner='runtime-worker-b', execution_version=?, lease_until=datetime('now','+120 seconds') WHERE id=?`).bind(version!+1,graph.id).run();await expect(completeRuntimeExecution(db,'runtime-tenant',request,{runtimeId:'desktop-b',graphId:graph.id,nodeId:'node',attemptId:'runtime-fence-attempt',outcome:'completed',startedAt:new Date().toISOString(),finishedAt:new Date().toISOString(),stdout:'stale'})).rejects.toThrow('Graph execution lease lost');const row=await db.prepare(`SELECT status FROM runtime_executions WHERE tenant_id=? AND attempt_id=?`).bind('runtime-tenant','runtime-fence-attempt').first<{status:string}>();expect(row?.status).toBe('in_flight');});
  it('allows one recovery worker to claim only after the original graph fence is abandoned',async()=>{await registerExecutionRuntime(db,'runtime-tenant',{id:'desktop-recovery',tenantId:'runtime-tenant',kind:'desktop_local',state:'online',capabilities:['command.exec'],lastHeartbeatAt:new Date().toISOString()});const graph:TaskGraph={id:'runtime-recovery-graph',rootTaskId:'runtime-recovery-root',goal:'runtime recovery',createdAt:new Date().toISOString(),nodes:[{id:'node',title:'Node',prompt:'recover',domain:'general',complexity:1,expectedFormat:'text',recommendedTier:1,dependencies:[],contextFrom:[],status:'ready',attemptedModels:[]}]};await persistGraph(db,'runtime-tenant',graph);const version=await acquireGraphExecutionLease(db,'runtime-tenant',graph.id,'runtime-worker');const request={runtimeId:'desktop-recovery',graphId:graph.id,nodeId:'node',attemptId:'runtime-recovery-attempt',executionOwner:'runtime-worker',executionVersion:version!,leaseExpiresAt:new Date(Date.now()+60000).toISOString(),capability:'command.exec' as const};await authorizeRuntimeExecution(db,'runtime-tenant',request);await markRuntimeExecutionInFlight(db,'runtime-tenant',request);await db.prepare(`UPDATE task_graphs SET execution_owner='runtime-worker-b', execution_version=?, lease_until=datetime('now','+120 seconds') WHERE id=?`).bind(version!+1,graph.id).run();const first=await claimRecoverableRuntimeExecution(db,'runtime-tenant','runtime-recovery-attempt','recovery-worker-a');expect(first?.attemptId).toBe('runtime-recovery-attempt');expect(first?.recoveryVersion).toBe(1);const second=await claimRecoverableRuntimeExecution(db,'runtime-tenant','runtime-recovery-attempt','recovery-worker-b');expect(second).toBeNull();});
  it('does not advertise a runtime execution as recoverable while its original graph generation is still live',async()=>{await registerExecutionRuntime(db,'runtime-tenant',{id:'desktop-list',tenantId:'runtime-tenant',kind:'desktop_local',state:'online',capabilities:['command.exec'],lastHeartbeatAt:new Date().toISOString()});const graph:TaskGraph={id:'runtime-list-graph',rootTaskId:'runtime-recovery-root',goal:'runtime listing',createdAt:new Date().toISOString(),nodes:[{id:'node',title:'Node',prompt:'list',domain:'general',complexity:1,expectedFormat:'text',recommendedTier:1,dependencies:[],contextFrom:[],status:'ready',attemptedModels:[]}]};await persistGraph(db,'runtime-tenant',graph);const version=await acquireGraphExecutionLease(db,'runtime-tenant',graph.id,'runtime-list-worker');const request={runtimeId:'desktop-list',graphId:graph.id,nodeId:'node',attemptId:'runtime-list-attempt',executionOwner:'runtime-list-worker',executionVersion:version!,leaseExpiresAt:new Date(Date.now()+60000).toISOString(),capability:'command.exec' as const};await authorizeRuntimeExecution(db,'runtime-tenant',request);await markRuntimeExecutionInFlight(db,'runtime-tenant',request);expect(await listRecoverableRuntimeExecutions(db,'runtime-tenant')).toEqual([]);await db.prepare(`UPDATE task_graphs SET lease_until=datetime('now','-1 second') WHERE id=? AND tenant_id=? AND execution_owner=? AND execution_version=?`).bind(graph.id,'runtime-tenant','runtime-list-worker',version!).run();expect((await listRecoverableRuntimeExecutions(db,'runtime-tenant')).map(item=>item.attemptId)).toContain('runtime-list-attempt');});
});
