import type { D1Database } from '@cloudflare/workers-types';

export type ExternalSideEffectStatus='authorized'|'in_flight'|'completed'|'failed'|'unknown';
export interface ExternalSideEffectInput { id:string; tenantId:string; graphId:string; nodeId:string; attemptId:string; executionOwner:string; executionVersion:number; provider:string; operation:string; idempotencyKey:string; requestFingerprint:string; }
export interface ExternalSideEffectRecord extends ExternalSideEffectInput { status:ExternalSideEffectStatus; externalOperationId?:string; responseFingerprint?:string; error?:string; createdAt:string; updatedAt:string; completedAt?:string; }
type Row={id:string;tenant_id:string;graph_id:string;node_id:string;attempt_id:string;execution_owner:string;execution_version:number;provider:string;operation:string;idempotency_key:string;request_fingerprint:string;status:ExternalSideEffectStatus;external_operation_id:string|null;response_fingerprint:string|null;error:string|null;created_at:string;updated_at:string;completed_at:string|null};
const map=(r:Row):ExternalSideEffectRecord=>({id:r.id,tenantId:r.tenant_id,graphId:r.graph_id,nodeId:r.node_id,attemptId:r.attempt_id,executionOwner:r.execution_owner,executionVersion:r.execution_version,provider:r.provider,operation:r.operation,idempotencyKey:r.idempotency_key,requestFingerprint:r.request_fingerprint,status:r.status,externalOperationId:r.external_operation_id??undefined,responseFingerprint:r.response_fingerprint??undefined,error:r.error??undefined,createdAt:r.created_at,updatedAt:r.updated_at,completedAt:r.completed_at??undefined});

export async function getExternalSideEffectByIdempotency(db:D1Database,tenantId:string,idempotencyKey:string):Promise<ExternalSideEffectRecord|null>{const row=await db.prepare('SELECT * FROM external_side_effects WHERE tenant_id=? AND idempotency_key=?').bind(tenantId,idempotencyKey).first<Row>();return row?map(row):null;}
export async function authorizeExternalSideEffect(db:D1Database,input:ExternalSideEffectInput):Promise<ExternalSideEffectRecord>{const existing=await getExternalSideEffectByIdempotency(db,input.tenantId,input.idempotencyKey);if(existing){if(existing.requestFingerprint!==input.requestFingerprint||existing.provider!==input.provider||existing.operation!==input.operation||existing.graphId!==input.graphId||existing.nodeId!==input.nodeId||existing.attemptId!==input.attemptId)throw new Error('External side-effect idempotency key is already bound to different intent');return existing;}const row=await db.prepare(`INSERT INTO external_side_effects (id,tenant_id,graph_id,node_id,attempt_id,execution_owner,execution_version,provider,operation,idempotency_key,request_fingerprint,status) SELECT ?,?,?,?,?,?,?,?,?,?,?,? WHERE EXISTS (SELECT 1 FROM task_graphs WHERE id=? AND tenant_id=? AND execution_owner=? AND execution_version=? AND lease_until IS NOT NULL AND lease_until>CURRENT_TIMESTAMP) ON CONFLICT(tenant_id,idempotency_key) DO NOTHING RETURNING *`).bind(input.id,input.tenantId,input.graphId,input.nodeId,input.attemptId,input.executionOwner,input.executionVersion,input.provider,input.operation,input.idempotencyKey,input.requestFingerprint,'authorized',input.graphId,input.tenantId,input.executionOwner,input.executionVersion).first<Row>();if(row)return map(row);const raced=await getExternalSideEffectByIdempotency(db,input.tenantId,input.idempotencyKey);if(raced){if(raced.requestFingerprint!==input.requestFingerprint)throw new Error('External side-effect idempotency key raced with different intent');return raced;}throw new Error('Graph execution lease lost before external side-effect authorization');}
export async function markExternalSideEffectInFlight(db:D1Database,input:ExternalSideEffectInput):Promise<ExternalSideEffectRecord>{const row=await db.prepare(`UPDATE external_side_effects SET status='in_flight',updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=? AND execution_owner=? AND execution_version=? AND status='authorized' AND EXISTS (SELECT 1 FROM task_graphs WHERE id=? AND tenant_id=? AND execution_owner=? AND execution_version=? AND lease_until IS NOT NULL AND lease_until>CURRENT_TIMESTAMP) RETURNING *`).bind(input.tenantId,input.id,input.executionOwner,input.executionVersion,input.graphId,input.tenantId,input.executionOwner,input.executionVersion).first<Row>();if(!row)throw new Error('External side-effect start rejected by execution fence');return map(row);}
export async function completeExternalSideEffect(db:D1Database,input:ExternalSideEffectInput,result:{externalOperationId:string;responseFingerprint?:string}):Promise<ExternalSideEffectRecord>{if(!result.externalOperationId.trim())throw new Error('External operation identity is required for completion');const row=await db.prepare(`UPDATE external_side_effects SET status='completed',external_operation_id=?,response_fingerprint=?,error=NULL,completed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=? AND execution_owner=? AND execution_version=? AND status IN ('in_flight','unknown') RETURNING *`).bind(result.externalOperationId,result.responseFingerprint??null,input.tenantId,input.id,input.executionOwner,input.executionVersion).first<Row>();if(!row)throw new Error('External side-effect completion rejected by execution fence');return map(row);}
export async function failExternalSideEffect(db:D1Database,input:ExternalSideEffectInput,error:string):Promise<ExternalSideEffectRecord>{const row=await db.prepare(`UPDATE external_side_effects SET status='failed',error=?,completed_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=? AND execution_owner=? AND execution_version=? AND status IN ('authorized','in_flight','unknown') RETURNING *`).bind(error.slice(0,4000),input.tenantId,input.id,input.executionOwner,input.executionVersion).first<Row>();if(!row)throw new Error('External side-effect failure update rejected by execution fence');return map(row);}
export async function markExternalSideEffectUnknown(db:D1Database,input:ExternalSideEffectInput,error:string):Promise<ExternalSideEffectRecord>{const row=await db.prepare(`UPDATE external_side_effects SET status='unknown',error=?,updated_at=CURRENT_TIMESTAMP WHERE tenant_id=? AND id=? AND execution_owner=? AND execution_version=? AND status IN ('authorized','in_flight','unknown') RETURNING *`).bind(error.slice(0,4000),input.tenantId,input.id,input.executionOwner,input.executionVersion).first<Row>();if(!row)throw new Error('External side-effect uncertainty update rejected by execution fence');return map(row);}
export async function listUnknownExternalSideEffects(db:D1Database,tenantId:string,limit=50):Promise<ExternalSideEffectRecord[]>{const safe=Math.max(1,Math.min(100,Math.trunc(limit)));const rows=await db.prepare(`SELECT * FROM external_side_effects WHERE tenant_id=? AND status='unknown' ORDER BY updated_at ASC LIMIT ${safe}`).bind(tenantId).all<Row>();return(rows.results??[]).map(map);}
export async function resolveExternalSideEffect(db:D1Database,tenantId:string,idempotencyKey:string):Promise<ExternalSideEffectRecord|null>{return getExternalSideEffectByIdempotency(db,tenantId,idempotencyKey);}
