import type { Env } from '../types';

const API_URL='https://api.github.com';
const MAX_FILES=300;
const MAX_PATCH=100_000;

export interface GitHubPullFile { sha:string; filename:string; status:string; additions:number; deletions:number; changes:number; blob_url?:string; raw_url?:string; contents_url?:string; patch?:string|null; previous_filename?:string; }

function b64Decode(value:string):Uint8Array{const normalized=value.replace(/-/g,'+').replace(/_/g,'/').replace(/\s/g,'');const padded=normalized+'='.repeat((4-normalized.length%4)%4);return Uint8Array.from(atob(padded),c=>c.charCodeAt(0));}
function keyBytes(secret:string):Uint8Array{const bytes=b64Decode(secret);if(bytes.byteLength!==32)throw new Error('GITHUB_TOKEN_ENCRYPTION_KEY must decode to 32 bytes');return bytes;}
async function decrypt(value:string,secret:string):Promise<string>{const combined=b64Decode(value);if(combined.length<13)throw new Error('Invalid encrypted GitHub token');const key=await crypto.subtle.importKey('raw',keyBytes(secret),'AES-GCM',false,['decrypt']);return new TextDecoder().decode(await crypto.subtle.decrypt({name:'AES-GCM',iv:combined.slice(0,12)},key,combined.slice(12)));}
async function getToken(env:Env,tenantId:string):Promise<string>{if(!env.GITHUB_TOKEN_ENCRYPTION_KEY)throw new Error('GitHub integration is not configured');const row=await env.DB.prepare('SELECT access_token_encrypted FROM github_connections WHERE tenant_id=? ORDER BY updated_at DESC LIMIT 1').bind(tenantId).first<{access_token_encrypted:string}>();if(!row)throw new Error('GitHub is not connected');return decrypt(row.access_token_encrypted,env.GITHUB_TOKEN_ENCRYPTION_KEY);}
function repoPart(value:string,label:string):string{const v=value.trim();if(!v||!/^[A-Za-z0-9_.-]+$/.test(v))throw new Error(`Invalid GitHub ${label}`);return v;}
export async function getGitHubPullFiles(env:Env,tenantId:string,owner:string,repo:string,number:number):Promise<GitHubPullFile[]>{if(!Number.isInteger(number)||number<1)throw new Error('Invalid pull request number');const token=await getToken(env,tenantId);const o=repoPart(owner,'owner'),r=repoPart(repo,'repository');const files:GitHubPullFile[]=[];for(let page=1;page<=10&&files.length<MAX_FILES;page++){const response=await fetch(`${API_URL}/repos/${encodeURIComponent(o)}/${encodeURIComponent(r)}/pulls/${number}/files?per_page=100&page=${page}`,{headers:{Accept:'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','User-Agent':'Uden/1.0',Authorization:`Bearer ${token}`}});if(!response.ok){if(response.status===401)throw new Error('GitHub authorization expired');if(response.status===403)throw new Error('GitHub API permission or rate limit exceeded');if(response.status===404)throw new Error('GitHub pull request not found');throw new Error(`GitHub pull request files request failed (${response.status})`);}const batch=await response.json() as GitHubPullFile[];for(const file of batch){files.push({...file,patch:file.patch?file.patch.slice(0,MAX_PATCH):file.patch??null});if(files.length>=MAX_FILES)break;}if(batch.length<100)break;}return files;}
