import { describe, expect, it, beforeAll, afterAll } from 'vitest';
import { getPlatformProxy } from 'wrangler';
import type { D1Database } from '@cloudflare/workers-types';
import { resolve } from 'node:path';
import { persistGraph, getPersistedGraph } from './graph-persistence';
import type { TaskGraph } from '@ai-work-partner/shared';
import { applyCurrentD1Schema } from '../test/d1-bootstrap';

describe('graph runtime linkage D1 integration', () => { let db: D1Database; let dispose: (() => Promise<void>) | undefined; beforeAll(async () => { const engineRoot = resolve(process.cwd()); const platform = await getPlatformProxy({ configPath: resolve(engineRoot, 'wrangler.test.jsonc'), persist: false }); db = platform.env.DB as D1Database; dispose = platform.dispose; await applyCurrentD1Schema(db, engineRoot); await db.prepare('INSERT INTO tenants (id,name,email,api_key_hash) VALUES (?,?,?,?)').bind('runtime-tenant','Runtime Tenant','runtime@example.test','runtime-hash').run(); await db.prepare('INSERT INTO projects (id,tenant_id,name) VALUES (?,?,?)').bind('project-1','runtime-tenant','Runtime Project').run(); }); afterAll(async () => { await dispose?.(); });
  it('round-trips runtime, approval, verification, and project-tool state without losing durable execution metadata', async () => { const graph: TaskGraph = { id:'runtime-graph', rootTaskId:'runtime-task', goal:'run project tests', projectId:'project-1', createdAt:new Date().toISOString(), nodes:[{ id:'execute', title:'Run tests', prompt:'npm test', domain:'code', complexity:1, expectedFormat:'text', recommendedTier:1, dependencies:[], contextFrom:[], status:'awaiting-runtime', attemptedModels:[], kind:'project-tool', tool:'execute', toolInput:{command:'npm test'}, approvalRequired:true, approvalState:'approved', approvedBy:'admin', approvedAt:new Date().toISOString(), runtimeJobId:'job-123', verification:{passed:false,reason:'Runtime execution is not terminal',checkedAt:new Date().toISOString()}, repairAttempts:2 }] }; await db.prepare('INSERT INTO tasks (id,tenant_id,prompt,status,mode,escalation_count,created_at) VALUES (?,?,?,?,?,?,CURRENT_TIMESTAMP)').bind('runtime-task','runtime-tenant','run project tests','processing','permissionless',0).run(); await persistGraph(db,'runtime-tenant',graph); const persisted=await getPersistedGraph(db,'runtime-tenant',graph.id); expect(persisted?.projectId).toBe('project-1'); expect(persisted?.nodes[0].status).toBe('awaiting-runtime'); expect(persisted?.nodes[0].runtimeJobId).toBe('job-123'); expect(persisted?.nodes[0].approvalState).toBe('approved'); expect(persisted?.nodes[0].kind).toBe('project-tool'); expect(persisted?.nodes[0].tool).toBe('execute'); expect(persisted?.nodes[0].toolInput).toEqual({command:'npm test'}); expect(persisted?.nodes[0].verification?.passed).toBe(false); expect(persisted?.nodes[0].repairAttempts).toBe(2); });
});
