import type { TaskGraph, TaskNode, TaskNodeStatus } from '@ai-work-partner/shared';

export type GraphAttemptRecord = { id:string; graphId:string; nodeId:string; tenantId:string; attemptNumber:number; model:string; provider?:string; status:string; promptTokens?:number; completionTokens?:number; costCents?:number; qualityScore?:number; escalationReason?:string; error?:string; startedAt?:string; completedAt?:string; };
export type GraphExecutionLease = { owner:string; leaseSeconds?:number; fenceVersion?:number };
const parse=<T>(value:unknown,fallback:T):T=>{try{return value==null?fallback:JSON.parse(String(value));}catch{return fallback;}};

export async function persistGraph(db:D1Database,tenantId:string,graph:TaskGraph,projectId?:string,lease?:GraphExecutionLease):Promise<void>{const owner=lease?.owner||null;const leaseSeconds=lease?.leaseSeconds||120;await db.prepare(`INSERT INTO task_graphs (id,tenant_id,root_task_id,project_id,goal,execution_principal,status,execution_version,execution_owner,lease_until,created_at,updated_at) VALUES (?,?,?,?,?,?,'running',1,?,datetime('now','+'||?||' seconds'),?,CURRENT_TIMESTAMP)`).bind(graph.id,tenantId,graph.rootTaskId,projectId??graph.projectId??null,graph.goal,graph.executionPrincipal||null,owner,leaseSeconds,graph.createdAt).run();for(const node of graph.nodes)await persistGraphNode(db,tenantId,graph.id,node);}

function nodeValues(node:TaskNode):any[]{return [node.title,node.prompt,node.domain,node.complexity,node.expectedFormat,node.recommendedTier,JSON.stringify(node.dependencies),JSON.stringify(node.contextFrom),node.kind||'model',node.tool||null,node.toolInput?JSON.stringify(node.toolInput):null,node.status,node.selectedModel||null,node.activeAttemptNumber??null,JSON.stringify(node.attemptedModels||[]),node.output||null,node.qualityScore??null,node.costCents||0,node.tokensIn||0,node.tokensOut||0,node.error||null,node.approvalRequired?1:0,node.approvalState||'not-required',node.approvalReason||null,node.approvedBy||null,node.approvedAt||null,node.runtimeJobId||null,node.verification?.passed===undefined?null:(node.verification.passed?1:0),node.verification?.reason||null,node.verification?.checkedAt||null,node.repairAttempts||0,node.repairError||null,node.status==='running'?new Date().toISOString():null,node.status==='completed'?new Date().toISOString():null];}
function nodeInsertParams(graphId:string,tenantId:string,node:TaskNode):any[]{return [node.id,graphId,tenantId,...nodeValues(node)];}
function nodeUpdateStatement(db:D1Database,tenantId:string,graphId:string,node:TaskNode,lease:GraphExecutionLease){const values=nodeValues(node);const guard=lease.fenceVersion===undefined?`execution_owner=? AND lease_until>=CURRENT_TIMESTAMP`:`execution_owner=? AND execution_version=? AND lease_until>=CURRENT_TIMESTAMP`;const params=[...values,graphId,node.id,tenantId,graphId,tenantId,lease.owner,...(lease.fenceVersion===undefined?[]:[lease.fenceVersion])];return db.prepare(`UPDATE task_graph_nodes SET title=?,prompt=?,domain=?,complexity=?,expected_format=?,recommended_tier=?,dependencies_json=?,context_from_json=?,kind=?,tool=?,tool_input_json=?,status=?,selected_model=?,active_attempt_number=?,attempted_models_json=?,output=?,quality_score=?,cost_cents=?,tokens_in=?,tokens_out=?,error=?,approval_required=?,approval_state=?,approval_reason=?,approved_by=?,approved_at=?,runtime_job_id=?,verification_passed=?,verification_reason=?,verification_checked_at=?,repair_attempts=?,repair_error=?,started_at=COALESCE(?,started_at),completed_at=COALESCE(?,completed_at),updated_at=CURRENT_TIMESTAMP WHERE graph_id=? AND id=? AND tenant_id=? AND EXISTS (SELECT 1 FROM task_graphs WHERE id=? AND tenant_id=? AND ${guard})`).bind(...params);}

export async function persistGraphNode(db:D1Database,tenantId:string,graphId:string,node:TaskNode,lease?:GraphExecutionLease):Promise<void>{
  if(lease){const result=await nodeUpdateStatement(db,tenantId,graphId,node,lease).run();if(!result.meta?.changes)throw new Error('Graph execution lease lost');return;}
  await db.prepare(`INSERT INTO task_graph_nodes (id,graph_id,tenant_id,title,prompt,domain,complexity,expected_format,recommended_tier,dependencies_json,context_from_json,kind,tool,tool_input_json,status,selected_model,active_attempt_number,attempted_models_json,output,quality_score,cost_cents,tokens_in,tokens_out,error,approval_required,approval_state,approval_reason,approved_by,approved_at,runtime_job_id,verification_passed,verification_reason,verification_checked_at,repair_attempts,repair_error,created_at,started_at,completed_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP,?,?,CURRENT_TIMESTAMP) ON CONFLICT(graph_id,id) DO UPDATE SET title=excluded.title,prompt=excluded.prompt,domain=excluded.domain,complexity=excluded.complexity,expected_format=excluded.expected_format,recommended_tier=excluded.recommended_tier,dependencies_json=excluded.dependencies_json,context_from_json=excluded.context_from_json,kind=excluded.kind,tool=excluded.tool,tool_input_json=excluded.tool_input_json,status=excluded.status,selected_model=excluded.selected_model,active_attempt_number=excluded.active_attempt_number,attempted_models_json=excluded.attempted_models_json,output=excluded.output,quality_score=excluded.quality_score,cost_cents=excluded.cost_cents,tokens_in=excluded.tokens_in,tokens_out=excluded.tokens_out,error=excluded.error,approval_required=excluded.approval_required,approval_state=excluded.approval_state,approval_reason=excluded.approval_reason,approved_by=excluded.approved_by,approved_at=excluded.approved_at,runtime_job_id=excluded.runtime_job_id,verification_passed=excluded.verification_passed,verification_reason=excluded.verification_reason,verification_checked_at=excluded.verification_checked_at,repair_attempts=excluded.repair_attempts,repair_error=excluded.repair_error,started_at=COALESCE(excluded.started_at,task_graph_nodes.started_at),completed_at=COALESCE(excluded.completed_at,task_graph_nodes.completed_at),updated_at=CURRENT_TIMESTAMP`).bind(...nodeInsertParams(graphId,tenantId,node)).run();
}

export async function persistGraphSnapshot(db:D1Database,tenantId:string,graph:TaskGraph,status:string,activeNodeId?:string|null,lastError?:string|null,lease?:GraphExecutionLease):Promise<void>{
  const terminal=['completed','failed','blocked','awaiting-approval','awaiting-runtime'].includes(status);
  const leaseSeconds=lease?.leaseSeconds||120;
  if(lease){
    if(lease.fenceVersion===undefined)throw new Error('Graph execution lease generation required');
    const atomicGuard=db.prepare(`UPDATE task_graphs SET id=NULL WHERE id=? AND tenant_id=? AND NOT EXISTS (SELECT 1 FROM task_graphs WHERE id=? AND tenant_id=? AND execution_owner=? AND execution_version=? AND lease_until>=CURRENT_TIMESTAMP AND (SELECT COUNT(*) FROM task_graph_nodes WHERE graph_id=? AND tenant_id=?)=?)`).bind(graph.id,tenantId,graph.id,tenantId,lease.owner,lease.fenceVersion,graph.id,tenantId,graph.nodes.length);
    const nodeStatements=graph.nodes.map(node=>nodeUpdateStatement(db,tenantId,graph.id,node,lease));
    const finalGraph=db.prepare(`UPDATE task_graphs SET status=?,active_node_id=?,last_error=?,started_at=COALESCE(started_at,CURRENT_TIMESTAMP),completed_at=CASE WHEN ? THEN CURRENT_TIMESTAMP ELSE completed_at END,execution_owner=CASE WHEN ? THEN NULL ELSE execution_owner END,lease_until=CASE WHEN ? THEN NULL ELSE datetime('now','+'||?||' seconds') END,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=? AND execution_owner=? AND execution_version=? AND lease_until>=CURRENT_TIMESTAMP AND (SELECT COUNT(*) FROM task_graph_nodes WHERE graph_id=? AND tenant_id?)=?`).bind(status,activeNodeId||null,lastError||null,terminal?1:0,terminal?1:0,terminal?1:0,leaseSeconds,graph.id,tenantId,lease.owner,lease.fenceVersion,graph.id,tenantId,graph.nodes.length);
    const verification=db.prepare(`SELECT id FROM task_graphs WHERE id=? AND tenant_id=? AND execution_version=? AND ((? IS NULL AND execution_owner IS NULL) OR execution_owner=?) AND ((SELECT COUNT(*) FROM task_graph_nodes WHERE graph_id=? AND tenant_id=?)=?)`).bind(graph.id,tenantId,lease.fenceVersion,terminal?null:lease.owner,terminal?null:lease.owner,graph.id,tenantId,graph.nodes.length);
    const results=await db.batch([atomicGuard,...nodeStatements,finalGraph,verification]);
    const verificationResult=results[results.length-1];
    if(!Boolean(verificationResult?.results?.length))throw new Error('Graph execution lease lost');
    return;
  }
  for(const node of graph.nodes)await persistGraphNode(db,tenantId,graph.id,node);
  const owner=null;const bindings:any[]=[status,activeNodeId||null,lastError||null,terminal?1:0,terminal?1:0,terminal?1:0,leaseSeconds,graph.id,tenantId,owner,owner];
  await db.prepare(`UPDATE task_graphs SET status=?,active_node_id=?,last_error=?,started_at=COALESCE(started_at,CURRENT_TIMESTAMP),completed_at=CASE WHEN ? THEN CURRENT_TIMESTAMP ELSE completed_at END,execution_owner=CASE WHEN ? THEN NULL ELSE execution_owner END,lease_until=CASE WHEN ? THEN NULL ELSE datetime('now','+'||?||' seconds') END,execution_version=execution_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=? AND (? IS NULL OR execution_owner IS NULL OR execution_owner=? OR lease_until<CURRENT_TIMESTAMP)`).bind(...bindings).run();
}

export async function acquireGraphExecutionLease(db:D1Database,tenantId:string,graphId:string,owner:string,leaseSeconds=120):Promise<number|null>{const result=await db.prepare(`UPDATE task_graphs SET execution_owner=?,lease_until=datetime('now','+'||?||' seconds'),execution_version=execution_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=? AND (execution_owner IS NULL OR execution_owner=? OR lease_until<CURRENT_TIMESTAMP) RETURNING execution_version`).bind(owner,leaseSeconds,graphId,tenantId,owner).first<{execution_version:number}>();return result?.execution_version??null;}
export async function renewGraphExecutionLease(db:D1Database,tenantId:string,graphId:string,lease:GraphExecutionLease):Promise<void>{if(lease.fenceVersion===undefined)throw new Error('Graph execution lease generation required');const leaseSeconds=lease.leaseSeconds||120;const row=await db.prepare(`UPDATE task_graphs SET lease_until=datetime('now','+'||?||' seconds'),updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=? AND execution_owner=? AND execution_version=? RETURNING execution_version`).bind(leaseSeconds,graphId,tenantId,lease.owner,lease.fenceVersion).first<{execution_version:number}>();if(!row)throw new Error('Graph execution lease lost');}

export async function recordGraphAttempt(db:D1Database,attempt:GraphAttemptRecord):Promise<void>{await db.prepare(`INSERT INTO task_graph_attempts (id,graph_id,node_id,tenant_id,attempt_number,model,provider,status,prompt_tokens,completion_tokens,cost_cents,quality_score,escalation_reason,error,started_at,completed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(graph_id,node_id,attempt_number) DO UPDATE SET status=excluded.status,model=excluded.model,provider=excluded.provider,prompt_tokens=excluded.prompt_tokens,completion_tokens=excluded.completion_tokens,cost_cents=excluded.cost_cents,quality_score=excluded.quality_score,escalation_reason=excluded.escalation_reason,error=excluded.error,started_at=COALESCE(task_graph_attempts.started_at,excluded.started_at),completed_at=excluded.completed_at`).bind(attempt.id,attempt.graphId,attempt.nodeId,attempt.tenantId,attempt.attemptNumber,attempt.model,attempt.provider||null,attempt.promptTokens||0,attempt.completionTokens||0,attempt.costCents||0,attempt.qualityScore??null,attempt.escalationReason||null,attempt.error||null,attempt.startedAt||new Date().toISOString(),attempt.completedAt||null).run();}

export async function getPersistedGraph(db:D1Database,tenantId:string,graphId:string):Promise<TaskGraph|null>{const graph=await db.prepare(`SELECT * FROM task_graphs WHERE id=? AND tenant_id=?`).bind(graphId,tenantId).first<any>();if(!graph)return null;const rows=await db.prepare(`SELECT * FROM task_graph_nodes WHERE graph_id=? AND tenant_id=? ORDER BY created_at,id`).bind(graphId,tenantId).all<any>();return{id:graph.id,rootTaskId:graph.root_task_id,goal:graph.goal,projectId:graph.project_id||undefined,executionPrincipal:graph.execution_principal||undefined,createdAt:graph.created_at,completedAt:graph.completed_at||undefined,nodes:(rows.results||[]).map((node:any)=>{const failedRuntime=Boolean(node.runtime_job_id)&&node.status==='failed';const approvalState=failedRuntime?'pending':(node.approval_state||'not-required');return{id:node.id,title:node.title,prompt:node.prompt,domain:node.domain,complexity:node.complexity,expectedFormat:node.expected_format,recommendedTier:node.recommended_tier,dependencies:parse(node.dependencies_json,[]),contextFrom:parse(node.context_from_json,[]),status:node.status as TaskNodeStatus,kind:node.kind||'model',tool:node.tool||undefined,toolInput:parse(node.tool_input_json,undefined),attemptedModels:parse(node.attempted_models_json,[]),selectedModel:node.selected_model||undefined,activeAttemptNumber:node.active_attempt_number??undefined,output:node.output||undefined,qualityScore:node.quality_score??undefined,costCents:node.cost_cents??0,tokensIn:node.tokens_in??0,tokensOut:node.tokens_out??0,error:node.error||undefined,approvalRequired:Boolean(node.approval_required)||failedRuntime,approvalState,approvalReason:failedRuntime?'Runtime repair requires explicit approval':node.approval_reason||undefined,approvedBy:failedRuntime?undefined:node.approved_by||undefined,approvedAt:failedRuntime?undefined:node.approved_at||undefined,runtimeJobId:node.runtime_job_id||undefined,verification:node.verification_passed===null||node.verification_passed===undefined?undefined:{passed:Boolean(node.verification_passed),reason:node.verification_reason||'',checkedAt:node.verification_checked_at||''},repairAttempts:node.repair_attempts??0,repairError:node.repair_error||undefined};})};}
export async function listPersistedGraphs(db:D1Database,tenantId:string,limit=50,offset=0){const result=await db.prepare(`SELECT id,root_task_id,project_id,goal,status,execution_principal,execution_version,active_node_id,last_error,execution_owner,lease_until,created_at,started_at,completed_at,updated_at FROM task_graphs WHERE tenant_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?`).bind(tenantId,limit,offset).all<any>();return result.results||[];}
export async function listGraphAttempts(db:D1Database,tenantId:string,graphId:string,nodeId?:string){const result=nodeId?await db.prepare(`SELECT * FROM task_graph_attempts WHERE tenant_id=? AND graph_id=? AND node_id=? ORDER BY attempt_number`).bind(tenantId,graphId,nodeId).all<any>():await db.prepare(`SELECT * FROM task_graph_attempts WHERE tenant_id=? AND graph_id=? ORDER BY node_id,attempt_number`).bind(tenantId,graphId).all<any>();return result.results||[];}
