import type { HonoEnv } from '../types';
import { recordUsage, reserveBudget, releaseBudget } from './cost';
import { checkQuality } from './quality';
import { getProvider } from './providers';
import { routeGraphNode } from './graph-router';
import { createEscalationLog, createTask, getMonthlySpend, getTenantById, updateTask } from '../db/queries';
import { persistGraph, persistGraphSnapshot, recordGraphAttempt, acquireGraphExecutionLease, getPersistedGraph, type GraphExecutionLease } from './graph-persistence';
import { classifyTask } from './classifier';
import { retryWithBackoff } from './retry';
import { sanitizeProviderError, isRetryableProviderError } from './provider-errors';
import { executeProjectTool, type ProjectTool, type RuntimeResult } from './project-context';
import { getProjectRuntimeJob } from './project-runtime';

// The executor's persistence closure carries the acquisition's fencing generation
// for the entire lifetime of the worker. A reclaimed graph therefore invalidates
// every subsequent write from the stale worker.
function executionLease(owner: string, fenceVersion: number): GraphExecutionLease {
  return { owner, fenceVersion };
}

export function blockDependents(graph: TaskGraph): void { const failed = new Set(graph.nodes.filter((node) => node.status === 'failed').map((node) => node.id)); let changed = true; while (changed) { changed = false; for (const node of graph.nodes) { if (node.status !== 'pending' && node.status !== 'ready') continue; const failedDependency = node.dependencies.find((dependency) => failed.has(dependency)); if (failedDependency) { node.error = `Blocked by failed dependency: ${failedDependency}`; setNodeStatus(node, 'blocked'); failed.add(node.id); changed = true; } } } }
export function getReadyGraphNodes(graph: TaskGraph): TaskNode[] { return graph.nodes.filter((node) => (node.status === 'ready' || node.status === 'pending') && node.dependencies.every((dependency) => graph.nodes.some((candidate) => candidate.id === dependency && candidate.status === 'completed'))); }

async function executeGraphState(env: HonoEnv['Bindings'], tenantId: string, graph: TaskGraph, qualityPreference: 'cost-optimized' | 'balanced' | 'quality-first', lease: GraphExecutionLease): Promise<GraphExecutionResult> {
  const executionOrder: string[] = []; const budgetLeft = async () => { const tenant = await getTenantById(env.DB, tenantId); const budget = tenant?.monthlyBudgetCents || 10000; const spent = await getMonthlySpend(env.DB, tenantId); return Math.max(0, budget - spent); }; const persist = async (status = 'running', error?: string) => { const active = graph.nodes.find((node) => node.status === 'running')?.id || null; await persistGraphSnapshot(env.DB, tenantId, graph, status, active, error, lease); };
  while (graph.nodes.some((node) => node.status === 'pending' || node.status === 'ready')) { blockDependents(graph); const ready = getReadyGraphNodes(graph); if (ready.length === 0) break; for (const node of ready) { if (gateGraphNodeForApproval(node)) { await persist('awaiting-approval', node.approvalReason); continue; } await executeNode(env, graph, node, tenantId, qualityPreference, budgetLeft, persist); if (node.status === 'failed' && canRepair(node) && graph.projectId) { try { await proposeGraphRepair(env, tenantId, graph, node); } catch (repairError) { node.repairError = repairError instanceof Error ? repairError.message : 'Repair proposal generation failed'; await persist('failed', node.repairError); } } if (node.status === 'completed') executionOrder.push(node.id); blockDependents(graph); await persist(node.status === 'awaiting-approval' ? 'awaiting-approval' : 'running'); } }
  const awaiting = graph.nodes.find((node) => node.status === 'awaiting-approval'); const awaitingRuntime = graph.nodes.find((node) => node.status === 'awaiting-runtime'); const failed = graph.nodes.some((node) => node.status === 'failed'); const blocked = graph.nodes.some((node) => node.status === 'blocked'); const status: GraphExecutionResult['status'] = awaiting ? 'awaiting-approval' : awaitingRuntime ? 'awaiting-runtime' : failed ? 'failed' : blocked ? 'blocked' : 'completed'; graph.completedAt = status === 'completed' ? new Date().toISOString() : undefined;
  const terminalNodes = graph.nodes.filter((node) => !graph.nodes.some((candidate) => candidate.dependencies.includes(node.id))); const output = terminalNodes.filter((node) => node.output).map((node) => node.output).join('\n\n'); const totalCostCents = graph.nodes.reduce((sum, node) => sum + (node.costCents || 0), 0); const tokensIn = graph.nodes.reduce((sum, node) => sum + (node.tokensIn || 0), 0); const tokensOut = graph.nodes.reduce((sum, node) => sum + (node.tokensOut || 0), 0); await persistGraphSnapshot(env.DB, tenantId, graph, status, awaiting?.id || awaitingRuntime?.id || null, awaiting?.approvalReason || (awaitingRuntime ? `Waiting for runtime job ${awaitingRuntime.runtimeJobId || 'unknown'}` : failed ? 'One or more graph nodes failed' : null), lease); return { graph, status, output, totalCostCents: Math.round(totalCostCents * 100) / 100, tokensIn, tokensOut, executionOrder };
}

export async function executeTaskGraph(env: HonoEnv['Bindings'], tenantId: string, plan: TaskGraphPlan, projectId?: string): Promise<GraphExecutionResult> {
  validateTaskGraphPlan(plan); if (plan.nodes.length === 0) throw new Error('Invalid graph: at least one node is required'); const tenant = await getTenantById(env.DB, tenantId); const qualityPreference = tenant?.qualityPreference || 'balanced'; const rootClassification = classifyTask(plan.goal); const rootTask: Task = { id: crypto.randomUUID(), tenantId, projectId, prompt: plan.goal, mode: 'permissionless', status: 'processing', classifiedTier: rootClassification.recommendedTier, classifiedDomain: rootClassification.domain, classifiedComplexity: rootClassification.complexity, expectedFormat: rootClassification.expectedFormat, escalationCount: 0, createdAt: new Date().toISOString() }; await createTask(env.DB, rootTask, { primaryModel: 'graph', fallbackChain: [], estimatedCostCents: 0, reasoning: 'Root task created for task-graph execution' });
  const graph: TaskGraph & { projectId?: string } = { id: crypto.randomUUID(), rootTaskId: rootTask.id, goal: plan.goal, nodes: plan.nodes.map((node) => ({ ...node, status: node.dependencies.length === 0 ? 'ready' : 'pending', attemptedModels: [], approvalRequired: node.approvalRequired ?? (node.kind === 'project-tool' && (node.tool === 'patch' || node.tool === 'execute')), approvalState: node.approvalRequired || (node.kind === 'project-tool' && (node.tool === 'patch' || node.tool === 'execute')) ? 'pending' : 'not-required' })), createdAt: new Date().toISOString(), projectId };
  const owner = graph.id; await persistGraph(env.DB, tenantId, graph, projectId, { owner }); const fenceVersion = await acquireGraphExecutionLease(env.DB, tenantId, graph.id, owner); if (fenceVersion === null) throw new Error('Graph execution lease could not be acquired'); const lease = executionLease(owner, fenceVersion);
  try { const result = await executeGraphState(env, tenantId, graph, qualityPreference, lease); await updateTask(env.DB, rootTask.id, tenantId, { status: result.status === 'completed' ? 'completed' : result.status === 'awaiting-approval' ? 'awaiting-approval' : result.status === 'awaiting-runtime' ? 'processing' : 'failed', output: result.output, totalCostCents: result.totalCostCents, tokensIn: result.tokensIn, tokensOut: result.tokensOut, escalationCount: graph.nodes.reduce((count, node) => count + Math.max(0, node.attemptedModels.length - 1), 0), ...(result.status === 'completed' ? { completedAt: new Date().toISOString() } : {}) }); return result; } catch (error) { const safe = sanitizeProviderError('graph', error); await persistGraphSnapshot(env.DB, tenantId, graph, 'failed', graph.nodes.find((node) => node.status === 'running')?.id || null, safe.message, lease); throw safe; }
}

async function resumeRuntimeJobs(env: HonoEnv['Bindings'], tenantId: string, graph: TaskGraph): Promise<void> {
  const projectId = graphProjectId(env, graph); if (!projectId) { for (const node of graph.nodes.filter((candidate) => candidate.status === 'awaiting-runtime')) { node.status = 'failed'; node.error = 'Runtime continuation requires a project-backed graph'; } return; }
  for (const node of graph.nodes.filter((candidate) => candidate.status === 'awaiting-runtime')) {
    if (!node.runtimeJobId) { node.status = 'failed'; node.error = 'Runtime continuation is missing its job id'; continue; }
    try {
      const result = await getProjectRuntimeJob(env, tenantId, projectId, node.runtimeJobId);
      node.output = result.output || node.output;
      if (result.status === 'succeeded') { node.verification = verifyRuntimeResult(result,nodeSuccessCriteria(node)); if (node.verification.passed) { node.error = undefined; node.qualityScore = 1; node.status = 'completed'; } else { node.error = node.verification.reason; node.status = 'failed'; } }
      else if (result.status === 'failed') { node.verification = verifyRuntimeResult(result,nodeSuccessCriteria(node)); node.error = node.verification.reason; node.status = 'failed'; }
      else { node.error = undefined; node.status = 'awaiting-runtime'; }
    } catch (error) { const safe = sanitizeProviderError('project-runtime', error); node.error = safe.message; node.status = 'awaiting-runtime'; }
  }
}

export async function resumeTaskGraph(env: HonoEnv['Bindings'], tenantId: string, graphId: string): Promise<GraphExecutionResult> {
  const graph = await getPersistedGraph(env.DB, tenantId, graphId); if (!graph) throw new Error('Graph not found'); const owner = crypto.randomUUID(); const fenceVersion = await acquireGraphExecutionLease(env.DB, tenantId, graphId, owner); if (fenceVersion === null) throw new Error('Graph is currently owned by another execution'); const lease = executionLease(owner, fenceVersion);
  const tenant = await getTenantById(env.DB, tenantId); const qualityPreference = tenant?.qualityPreference || 'balanced';
  await resumeRuntimeJobs(env, tenantId, graph);
  for (const node of graph.nodes) { if (node.status === 'running' || node.status === 'blocked') { if (node.approvalState === 'pending') node.status = 'awaiting-approval'; else { node.status = node.dependencies.length === 0 ? 'ready' : 'pending'; node.error = 'Recovered for retry after interrupted execution'; } } else if (node.status === 'failed' && node.approvalState === 'pending') { node.status = 'awaiting-approval'; } }
  await persistGraphSnapshot(env.DB, tenantId, graph, 'running', null, null, lease); try { const result = await executeGraphState(env, tenantId, graph, qualityPreference, lease); await updateTask(env.DB, graph.rootTaskId, tenantId, { status: result.status === 'completed' ? 'completed' : result.status === 'awaiting-approval' ? 'awaiting-approval' : result.status === 'awaiting-runtime' ? 'processing' : 'failed', output: result.output, totalCostCents: result.totalCostCents, tokensIn: result.tokensIn, tokensOut: result.tokensOut, escalationCount: graph.nodes.reduce((count, node) => count + Math.max(0, node.attemptedModels.length - 1), 0), ...(result.status === 'completed' ? { completedAt: new Date().toISOString() } : {}) }); return result; } catch (error) { const safe = sanitizeProviderError('graph', error); await persistGraphSnapshot(env.DB, tenantId, graph, 'failed', graph.nodes.find((node) => node.status === 'running')?.id || null, safe.message, lease); throw safe; }
}