import type { TaskGraph, TaskNode, TaskNodeStatus } from '@ai-work-partner/shared';

export type GraphAttemptRecord = { id:string; graphId:string; nodeId:string; tenantId:string; attemptNumber:number; model:string; provider?:string; status:string; promptTokens?:number; completionTokens?:number; costCents?:number; qualityScore?:number; escalationReason?:string; error?:string; startedAt?:string; completedAt?:string };
const parse=<T>(v:unknown,f:T):T=>{try{return v==null?f:JSON.parse(String(v));}catch{return f;}};

export async function persistGraph(db:D1Database,tenantId:string,graph:TaskGraph,projectId?:string){
 await db.prepare(`INSERT INTO task_graphs (id,tenant_id,root_task_id,project_id,goal,status,execution_version,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP)`).bind(graph.id,tenantId,graph.rootTaskId,projectId||null,graph.goal,'running',1,graph.createdAt).run();
 for(const node of graph.nodes) await persistGraphNode(db,tenantId,graph.id,node);
}
export async function persistGraphNode(db:D1Database,tenantId:string,graphId:string,node:TaskNode){
 await db.prepare(`INSERT INTO task_graph_nodes (id,graph_id,tenant_id,title,prompt,domain,complexity,expected_format,recommended_tier,dependencies_json,context_from_json,status,selected_model,attempted_models_json,output,quality_score,cost_cents,tokens_in,tokens_out,error,created_at,started_at,completed_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(graph_id,id) DO UPDATE SET status=excluded.status,selected_model=excluded.selected_model,attempted_models_json=excluded.attempted_models_json,output=excluded.output,quality_score=excluded.quality_score,cost_cents=excluded.cost_cents,tokens_in=excluded.tokens_in,tokens_out=excluded.tokens_out,error=excluded.error,started_at=excluded.started_at,completed_at=excluded.completed_at,updated_at=CURRENT_TIMESTAMP`).bind(node.id,graphId,tenantId,node.title,node.prompt,node.domain,node.complexity,node.expectedFormat,node.recommendedTier,JSON.stringify(node.dependencies),JSON.stringify(node.contextFrom),node.status,node.selectedModel||null,JSON.stringify(node.attemptedModels||[]),node.output||null,node.qualityScore??null,node.costCents||0,node.tokensIn||0,node.tokensOut||0,node.error||null,graphId?new Date().toISOString():null,node.status==='running'?new Date().toISOString():null,node.status==='completed'?new Date().toISOString():null).run();
}
export async function persistGraphSnapshot(db:D1Database,tenantId:string,graph:TaskGraph,status:string,activeNodeId?:string|null,lastError?:string|null){
 for(const node of graph.nodes) await persistGraphNode(db,tenantId,graph.id,node);
 await db.prepare(`UPDATE task_graphs SET status=?,active_node_id=?,last_error=?,started_at=COALESCE(started_at,CURRENT_TIMESTAMP),completed_at=?,execution_version=execution_version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND tenant_id=?`).bind(status,activeNodeId||null,lastError||null,['completed','failed','blocked'].includes(status)?new Date().toISOString():null,graph.id,tenantId).run();
}
export async function recordGraphAttempt(db:D1Database,a:GraphAttemptRecord){await db.prepare(`INSERT INTO task_graph_attempts (id,graph_id,node_id,tenant_id,attempt_number,model,provider,status,prompt_tokens,completion_tokens,cost_cents,quality_score,escalation_reason,error,started_at,completed_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).bind(a.id,a.graphId,a.nodeId,a.tenantId,a.attemptNumber,a.model,a.provider||null,a.status,a.promptTokens||0,a.completionTokens||0,a.costCents||0,a.qualityScore??null,a.escalationReason||null,a.error||null,a.startedAt||new Date().toISOString(),a.completedAt||null).run();}
export async function getPersistedGraph(db:D1Database,tenantId:string,graphId:string):Promise<TaskGraph|null>{const g=await db.prepare(`SELECT * FROM task_graphs WHERE id=? AND tenant_id=?`).bind(graphId,tenantId).first<any>();if(!g)return null;const r=await db.prepare(`SELECT * FROM task_graph_nodes WHERE graph_id=? AND tenant_id=? ORDER BY created_at,id`).bind(graphId,tenantId).all<any>();return{id:g.id,rootTaskId:g.root_task_id,goal:g.goal,createdAt:g.created_at,completedAt:g.completed_at||undefined,nodes:(r.results||[]).map((n:any)=>({id:n.id,title:n.title,prompt:n.prompt,domain:n.domain,complexity:n.complexity,expectedFormat:n.expected_format,recommendedTier:n.recommended_tier,dependencies:parse(n.dependencies_json,[]),contextFrom:parse(n.context_from_json,[]),status:n.status as TaskNodeStatus,attemptedModels:parse(n.attempted_models_json,[]),selectedModel:n.selected_model||undefined,output:n.output||undefined,qualityScore:n.quality_score??undefined,costCents:n.cost_cents??0,tokensIn:n.tokens_in??0,tokensOut:n.tokens_out??0,error:n.error||undefined}))};}
export async function listPersistedGraphs(db:D1Database,tenantId:string,limit=50,offset=0){const r=await db.prepare(`SELECT id,root_task_id,project_id,goal,status,execution_version,active_node_id,last_error,created_at,started_at,completed_at,updated_at FROM task_graphs WHERE tenant_id=? ORDER BY created_at DESC LIMIT ? OFFSET ?`).bind(tenantId,limit,offset).all<any>();return r.results||[];}
export async function listGraphAttempts(db:D1Database,tenantId:string,graphId:string,nodeId?:string){const r=nodeId?await db.prepare(`SELECT * FROM task_graph_attempts WHERE tenant_id=? AND graph_id=? AND node_id=? ORDER BY attempt_number`).bind(tenantId,graphId,nodeId).all<any>():await db.prepare(`SELECT * FROM task_graph_attempts WHERE tenant_id=? AND graph_id=? ORDER BY node_id,attempt_number`).bind(tenantId,graphId).all<any>();return r.results||[];}
