import type { Env } from '../types';

const API_URL = 'https://api.cursor.com/v1/origin';
const INSTALL_URL = 'https://cursor.com/codebase/apps/install';
const JWKS_URL = 'https://api.cursor.com/v1/origin/keys';
const ISSUER = 'https://api.cursor.com/v1/origin';
const STATE_TTL_MS = 10 * 60 * 1000;
const TOKEN_TTL_S = 240;

interface OriginJwtHeader { alg?: string; kid?: string; typ?: string; }
interface OriginJwk extends JsonWebKey { kid?: string; }
interface OriginReceipt { iss?: string; aud?: string; sub?: string; namespace_id?: string; iat?: number; exp?: number; jti?: string; state?: string; installedBy?: { id?: string; email?: string; displayName?: string }; }
interface OriginToken { token: string; expiresAt: string; }
export interface OriginWriteFile { path: string; content?: string; encoding?: 'utf-8' | 'base64'; delete?: boolean; mode?: 'file' | 'executable' | 'symlink'; }

function required(env: Env): { appId: string; privateKey: string; callback: string } {
  if (!env.ORIGIN_APP_ID || !env.ORIGIN_APP_PRIVATE_KEY || !env.ORIGIN_REDIRECT_URI) throw new Error('Origin integration is not configured');
  return { appId: env.ORIGIN_APP_ID, privateKey: env.ORIGIN_APP_PRIVATE_KEY, callback: env.ORIGIN_REDIRECT_URI };
}
function b64(bytes: Uint8Array): string { let s=''; for(const b of bytes)s+=String.fromCharCode(b); return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,''); }
function unb64(value:string):Uint8Array { const padded=value.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-value.length%4)%4); return Uint8Array.from(atob(padded),c=>c.charCodeAt(0)); }
function jsonPart<T>(value:string):T { return JSON.parse(new TextDecoder().decode(unb64(value))); }
function pemBytes(pem:string):Uint8Array { const body=pem.replace(/-----BEGIN PRIVATE KEY-----/,'').replace(/-----END PRIVATE KEY-----/,'').replace(/\s/g,''); return unb64(body); }
async function signJwt(env:Env):Promise<string> { const {appId,privateKey}=required(env); const now=Math.floor(Date.now()/1000); const header=b64(new TextEncoder().encode(JSON.stringify({alg:'EdDSA',kid:appId,typ:'JWT'}))); const payload=b64(new TextEncoder().encode(JSON.stringify({iss:appId,aud:'origin-apps',iat:now,exp:now+TOKEN_TTL_S}))); const key=await crypto.subtle.importKey('pkcs8',pemBytes(privateKey),{name:'Ed25519'},false,['sign']); const sig=await crypto.subtle.sign('Ed25519',key,new TextEncoder().encode(`${header}.${payload}`)); return `${header}.${payload}.${b64(new Uint8Array(sig))}`; }
async function originRequest<T>(token:string,path:string,init:RequestInit={}):Promise<T>{ const headers=new Headers(init.headers); headers.set('Authorization',`Bearer ${token}`); headers.set('Accept','application/json'); if(init.body&&!headers.has('Content-Type'))headers.set('Content-Type','application/json'); const response=await fetch(`${API_URL}${path}`,{...init,headers}); if(!response.ok){if(response.status===401)throw new Error('Origin authorization expired');if(response.status===403)throw new Error('Origin permission denied');if(response.status===404)throw new Error('Origin resource not found');if(response.status===409)throw new Error('Origin repository state changed; retry from the latest ref');if(response.status===429)throw new Error('Origin rate limit exceeded');throw new Error(`Origin API request failed (${response.status})`);} return response.status===204?undefined as T:await response.json() as T; }
async function appRequest<T>(env:Env,path:string,init:RequestInit={}):Promise<T>{return originRequest<T>(await signJwt(env),path,init);}
async function verifyReceipt(env:Env,receipt:string):Promise<OriginReceipt>{ const {appId}=required(env); const parts=receipt.split('.'); if(parts.length!==3)throw new Error('Invalid Origin installation receipt'); const header=jsonPart<OriginJwtHeader>(parts[0]); const payload=jsonPart<OriginReceipt>(parts[1]); if(header.alg!=='EdDSA'||header.typ!=='origin-installation-receipt+jwt'||!header.kid)throw new Error('Invalid Origin installation receipt'); if(payload.iss!==ISSUER||payload.aud!==appId||!payload.sub||!payload.namespace_id||!payload.exp||payload.exp<=Math.floor(Date.now()/1000))throw new Error('Invalid or expired Origin installation receipt'); const jwks=await fetch(JWKS_URL); if(!jwks.ok)throw new Error('Origin signing keys unavailable'); const body=await jwks.json() as {keys?:OriginJwk[]}; const jwk=body.keys?.find(k=>k.kid===header.kid); if(!jwk)throw new Error('Unknown Origin signing key'); const key=await crypto.subtle.importKey('jwk',jwk,{name:'Ed25519'},false,['verify']); const valid=await crypto.subtle.verify('Ed25519',key,unb64(parts[2]),new TextEncoder().encode(`${parts[0]}.${parts[1]}`)); if(!valid)throw new Error('Invalid Origin installation receipt signature'); return payload; }
async function hash(value:string):Promise<string>{return b64(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value))));}

export async function createOriginInstallUrl(env:Env,tenantId:string):Promise<string>{ required(env); const raw=`${tenantId}.${Date.now()}.${crypto.randomUUID()}`; const state=b64(new TextEncoder().encode(raw)); await env.DB.prepare('INSERT INTO origin_oauth_states(state_hash,tenant_id,expires_at) VALUES(?,?,?)').bind(await hash(state),tenantId,Date.now()+STATE_TTL_MS).run(); const params=new URLSearchParams({client_id:env.ORIGIN_APP_ID!,scope:'repository:metadata:read repository:contents:read repository:pull_requests:read repository:checks:read',redirect_uri:env.ORIGIN_REDIRECT_URI!,state,summary:'Allow Uden to work with this workspace codebase'}); return `${INSTALL_URL}?${params.toString()}`; }
export async function completeOriginInstall(env:Env,receipt:string):Promise<{tenantId:string;installationId:string;namespaceId:string}>{ const payload=await verifyReceipt(env,receipt); if(!payload.state)throw new Error('Origin installation receipt is missing state'); const consumed=await env.DB.prepare('UPDATE origin_oauth_states SET used_at=CURRENT_TIMESTAMP WHERE state_hash=? AND used_at IS NULL AND expires_at>? RETURNING tenant_id').bind(await hash(payload.state),Date.now()).first<{tenant_id:string}>(); if(!consumed?.tenant_id)throw new Error('Invalid or already-used Origin installation state'); const tenantId=consumed.tenant_id; await env.DB.prepare(`INSERT INTO origin_connections(id,tenant_id,installation_id,namespace_id,installed_by,state) VALUES(?,?,?,?,?,'active') ON CONFLICT(tenant_id,installation_id) DO UPDATE SET namespace_id=excluded.namespace_id,installed_by=excluded.installed_by,state='active',updated_at=CURRENT_TIMESTAMP`).bind(crypto.randomUUID(),tenantId,payload.sub,payload.namespace_id,payload.installedBy?.id||null).run(); return {tenantId,installationId:payload.sub!,namespaceId:payload.namespace_id!}; }

async function installationToken(env:Env,tenantId:string,scopes?:string[]):Promise<string>{ const row=await env.DB.prepare("SELECT installation_id FROM origin_connections WHERE tenant_id=? AND state='active' ORDER BY updated_at DESC LIMIT 1").bind(tenantId).first<{installation_id:string}>(); if(!row)throw new Error('Origin is not connected'); const result=await appRequest<OriginToken>(env,`/app/installations/${encodeURIComponent(row.installation_id)}/access_tokens`,{method:'POST',body:JSON.stringify({scopes:scopes||['repository:metadata:read','repository:contents:read','repository:pull_requests:read','repository:checks:read']})}); return result.token; }
export async function disconnectOrigin(env:Env,tenantId:string):Promise<void>{const row=await env.DB.prepare('SELECT installation_id FROM origin_connections WHERE tenant_id=? ORDER BY updated_at DESC LIMIT 1').bind(tenantId).first<{installation_id:string}>(); if(row){try{await appRequest(env,`/app/installations/${encodeURIComponent(row.installation_id)}`,{method:'DELETE'});}catch(error){if(error instanceof Error&&!/not found|authorization/i.test(error.message))throw error;}} await env.DB.prepare("UPDATE origin_connections SET state='deleted',updated_at=CURRENT_TIMESTAMP WHERE tenant_id=?").bind(tenantId).run();}
export async function listOriginRepositories(env:Env,tenantId:string):Promise<unknown>{return originRequest(await installationToken(env,tenantId),'/installation/repos?pageSize=100');}
export async function getOriginRepository(env:Env,tenantId:string,owner:string,repo:string):Promise<unknown>{return originRequest(await installationToken(env,tenantId,['repository:metadata:read']),`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`);}
export async function listOriginBranches(env:Env,tenantId:string,owner:string,repo:string):Promise<unknown>{return originRequest(await installationToken(env,tenantId),`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/branches?pageSize=100`);}
export async function listOriginCommits(env:Env,tenantId:string,owner:string,repo:string,sha?:string):Promise<unknown>{const q=sha?`?sha=${encodeURIComponent(sha)}&pageSize=100`:'?pageSize=100';return originRequest(await installationToken(env,tenantId),`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/commits${q}`);}
export async function getOriginCommit(env:Env,tenantId:string,owner:string,repo:string,sha:string):Promise<unknown>{return originRequest(await installationToken(env,tenantId),`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/commits/${encodeURIComponent(sha)}`);}
export async function getOriginBlob(env:Env,tenantId:string,owner:string,repo:string,sha:string):Promise<unknown>{return originRequest(await installationToken(env,tenantId),`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/blobs/${encodeURIComponent(sha)}`);}
export async function getOriginGitCommit(env:Env,tenantId:string,owner:string,repo:string,sha:string):Promise<unknown>{return originRequest(await installationToken(env,tenantId),`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/commits/${encodeURIComponent(sha)}`);}
export async function getOriginTree(env:Env,tenantId:string,owner:string,repo:string,sha:string):Promise<unknown>{return originRequest(await installationToken(env,tenantId),`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/trees/${encodeURIComponent(sha)}?recursive=true`);}
export async function listOriginPulls(env:Env,tenantId:string,owner:string,repo:string,state='open'):Promise<unknown>{return originRequest(await installationToken(env,tenantId),`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/pulls?state=${encodeURIComponent(state)}&pageSize=100`);}
export async function getOriginPull(env:Env,tenantId:string,owner:string,repo:string,number:string):Promise<unknown>{return originRequest(await installationToken(env,tenantId),`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/pulls/${encodeURIComponent(number)}`);}
export async function getOriginPullFiles(env:Env,tenantId:string,owner:string,repo:string,number:string):Promise<unknown>{return originRequest(await installationToken(env,tenantId),`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/pulls/${encodeURIComponent(number)}/files?pageSize=100`);}
export async function compareOriginCommits(env:Env,tenantId:string,owner:string,repo:string,basehead:string):Promise<unknown>{return originRequest(await installationToken(env,tenantId),`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/compare/${encodeURIComponent(basehead)}`);}

function branchName(value:string):string{const branch=value.trim();if(!/^[A-Za-z0-9._\/-]+$/.test(branch)||branch.startsWith('/')||branch.endsWith('/')||branch.includes('..')||branch.includes('@{'))throw new Error('Invalid Origin branch name');return branch;}
function sha(value:string,label:string):string{const result=value.trim();if(!/^[a-f0-9]{40}$|^[a-f0-9]{64}$/i.test(result))throw new Error(`Invalid Origin ${label} SHA`);return result;}
function pathName(value:string):string{const path=value.trim();if(!path||path.startsWith('/')||path.split('/').some(part=>!part||part==='.'||part==='..'))throw new Error('Invalid Origin file path');return path;}
export async function createOriginBranch(env:Env,tenantId:string,owner:string,repo:string,branch:string,fromSha:string):Promise<unknown>{const token=await installationToken(env,tenantId,['repository:contents:write']);const ref=branchName(branch);return originRequest(token,`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/refs`,{method:'POST',body:JSON.stringify({ref:`refs/heads/${ref}`,sha:sha(fromSha,'commit')})});}
export async function commitOriginFiles(env:Env,tenantId:string,owner:string,repo:string,branch:string,expectedHeadSha:string,message:string,files:OriginWriteFile[]):Promise<unknown>{const token=await installationToken(env,tenantId,['repository:contents:write']);const target=branchName(branch);const expected=sha(expectedHeadSha,'commit');const cleanMessage=message.trim();if(!cleanMessage||cleanMessage.length>2000)throw new Error('Invalid Origin commit message');if(!Array.isArray(files)||files.length===0||files.length>1000)throw new Error('Origin commit must contain 1-1000 file changes');const unique=new Set<string>();let total=0;const changes=files.map(file=>{const path=pathName(file.path);if(unique.has(path))throw new Error('Origin commit contains duplicate file paths');unique.add(path);if(file.delete===true&&file.content!==undefined)throw new Error('An Origin file change cannot contain both content and delete');if(file.delete!==true&&file.content===undefined)throw new Error('Origin file content is required unless deleting');if(file.content!==undefined){total+=file.content.length;if(file.content.length>8*1024*1024)throw new Error('Origin file content is too large');}return file.delete?{path,delete:true}:{path,content:file.content,encoding:file.encoding||'utf-8',...(file.mode?{mode:file.mode}:{})};});if(total>32*1024*1024)throw new Error('Origin commit content is too large');return originRequest<{sha:string;treeSha:string;previousHeadSha:string}>(token,`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/git/commits:createFromFiles`,{method:'POST',body:JSON.stringify({targetBranch:target,expectedHeadSha:expected,message:cleanMessage,files:changes})});}
export async function createOriginPull(env:Env,tenantId:string,owner:string,repo:string,head:string,base:string,title:string,body?:string):Promise<unknown>{const token=await installationToken(env,tenantId,['repository:pull_requests:write']);const cleanTitle=title.trim();if(!cleanTitle||cleanTitle.length>256)throw new Error('Invalid Origin pull request title');if((body||'').length>65536)throw new Error('Origin pull request body is too large');return originRequest(token,`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/pulls`,{method:'POST',body:JSON.stringify({head:branchName(head),base:branchName(base),title:cleanTitle,body:body||''})});}
export async function mergeOriginPull(env:Env,tenantId:string,owner:string,repo:string,number:string,expectedHeadSha:string):Promise<unknown>{const token=await installationToken(env,tenantId,['repository:contents:write']);const pullNumber=number.trim();if(!/^\d+$/.test(pullNumber)||Number(pullNumber)<1)throw new Error('Invalid Origin pull request number');return originRequest(token,`/repos/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}/pulls/${encodeURIComponent(pullNumber)}/merge`,{method:'POST',body:JSON.stringify({expectedHeadSha:sha(expectedHeadSha,'commit')})});}
