import { describe, expect, it, beforeAll, afterAll } from 'vitest';
import { getPlatformProxy } from 'wrangler';
import type { D1Database } from '@cloudflare/workers-types';
import { readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { upsertProjectFile } from './project-runtime';
import { projectTree, readProjectFile, previewProjectDiff } from './project-context';
const testDir=dirname(fileURLToPath(import.meta.url));
const engineRoot=resolve(testDir,'../..');
const schemaPath=resolve(testDir,'../db/schema.sql');
const migration=resolve(engineRoot,'migrations/0007_workspace_runtime.sql');
const patchMigration=resolve(engineRoot,'migrations/0009_project_patches.sql');
const execSqlFile=async(db:D1Database,path:string)=>{const sql=await readFile(path,'utf8');for(const statement of sql.replace(/^\uFEFF/,'').replace(/^[\t ]*--[^\r\n]*(?:\r?\n|$)/gm,'').split(';').map(s=>s.trim()).filter(Boolean))await db.prepare(statement).run();};
describe('project agent context D1 integration',()=>{let db:D1Database;let dispose:(()=>Promise<void>)|undefined;beforeAll(async()=>{const platform=await getPlatformProxy({configPath:resolve(engineRoot,'wrangler.test.jsonc'),persist:false});db=platform.env.DB as D1Database;dispose=platform.dispose;await execSqlFile(db,schemaPath);await execSqlFile(db,migration);await execSqlFile(db,patchMigration);await db.prepare('INSERT INTO tenants (id,name,email,api_key_hash) VALUES (?,?,?,?)').bind('context-a','Context A','context-a@example.test','context-hash-a').run();await db.prepare('INSERT INTO projects (id,tenant_id,name) VALUES (?,?,?)').bind('context-project','context-a','Context Project').run();});
afterAll(async()=>{await dispose?.();});
it('returns bounded tree metadata and reads a single tenant-owned file',async()=>{await upsertProjectFile({DB:db} as never,'context-a','context-project','src/index.ts','const value = 1;',0);expect(await projectTree({DB:db} as never,'context-a','context-project')).toEqual([{path:'src/index.ts',version:1,contentSha256:expect.any(String),size:16}]);await expect(readProjectFile({DB:db} as never,'context-a','context-project','../secrets')).rejects.toThrow('Invalid project file path');await expect(readProjectFile({DB:db} as never,'other-tenant','context-project','src/index.ts')).rejects.toThrow('Project file not found');});
it('produces a version-aware diff without mutating the project',async()=>{await upsertProjectFile({DB:db} as never,'context-a','context-project','src/diff.ts','const value = 1;\nkeep();',0);const preview=await previewProjectDiff({DB:db} as never,'context-a','context-project','src/diff.ts','const value = 2;\nkeep();',1);expect(preview.baseVersion).toBe(1);expect(preview.lines).toEqual(expect.arrayContaining([{type:'remove',line:1,text:'const value = 1;'},{type:'add',text:'const value = 2;'}]));expect((await readProjectFile({DB:db} as never,'context-a','context-project','src/diff.ts')).version).toBe(1);await expect(previewProjectDiff({DB:db} as never,'context-a','context-project','src/diff.ts','stale',99)).rejects.toThrow('Project file version conflict');});
});
