'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, RefreshCw, Workflow, ChevronRight } from 'lucide-react';
import TaskGraphView from '@/components/graph/TaskGraphView';
import { getGraph,getGraphAttempts,getGraphs,resumeGraph } from '@/lib/graph-api';

export default function GraphsPage(){
 const [graphs,setGraphs]=useState<any[]>([]); const [selected,setSelected]=useState<any>(null); const [attempts,setAttempts]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [resuming,setResuming]=useState(false);
 const selectGraph=useCallback(async(id:string)=>{const [g,a]=await Promise.all([getGraph(id),getGraphAttempts(id)]);setSelected(g.graph);setAttempts(a.attempts||[]);},[]);
 const refresh=useCallback(async()=>{setError('');try{const r=await getGraphs();setGraphs(r.graphs||[]);if(selected?.id)await selectGraph(selected.id);else if(r.graphs?.[0])await selectGraph(r.graphs[0].id);}catch(e:any){setError(e.message||'Unable to refresh graphs');}},[selected?.id,selectGraph]);
 const resume=async()=>{if(!selected)return;setResuming(true);setError('');try{await resumeGraph(selected.id);await selectGraph(selected.id);await refresh();}catch(e:any){setError(e.message||'Unable to resume graph');}finally{setResuming(false)}};
 useEffect(()=>{refresh().finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(!selected?.id||!['running','awaiting-runtime','awaiting-approval'].includes(selected.status))return;const timer=setInterval(()=>{selectGraph(selected.id).catch(()=>undefined)},5000);return()=>clearInterval(timer)},[selected?.id,selected?.status,selectGraph]);
 return <div className="space-y-5 md:space-y-6 pb-28 md:pb-10">
  <header className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div className="min-w-0"><div className="flex items-center gap-2 text-sm text-[var(--accent-primary)]"><Workflow size={16}/> Durable work</div><h1 className="text-2xl md:text-3xl font-semibold text-[var(--text-primary)] mt-2">Execution graphs</h1><p className="text-sm text-[var(--text-secondary)] mt-1 max-w-2xl leading-6">Understand how Uden decomposed the work, what is recorded at each step, and where human attention is required.</p></div><Link href="/tasks/new" className="btn btn-primary flex items-center gap-2 self-stretch sm:self-auto justify-center">New work <ArrowRight size={15}/></Link></header>
  {error&&<div role="alert" className="glass-card p-4 border border-[var(--status-danger)]/30 text-sm text-[var(--status-danger)]">{error}</div>}
  {loading?<div className="glass-card p-8 text-[var(--text-secondary)]">Loading recorded execution history…</div>:graphs.length===0?<div className="glass-card p-8 md:p-10 text-center"><Workflow className="mx-auto mb-3 text-[var(--text-muted)]"/><p className="font-medium text-[var(--text-primary)]">No execution graphs yet</p><p className="text-sm text-[var(--text-secondary)] mt-2 max-w-md mx-auto">Start a piece of work and its durable execution trail will appear here. Nothing is shown until a graph is actually recorded.</p><Link href="/tasks/new" className="btn btn-primary inline-flex mt-5">Start work</Link></div>:<>
    <section aria-label="Execution graph history" className="glass-card border border-[var(--border-color)] p-2 md:p-3"><div className="flex items-center gap-2 overflow-x-auto" role="tablist">{graphs.map((g,i)=><button key={g.id} type="button" role="tab" aria-selected={selected?.id===g.id} onClick={()=>selectGraph(g.id)} className={`min-w-[190px] md:min-w-[240px] max-w-[300px] px-3.5 py-3 rounded-xl border text-left transition-colors ${selected?.id===g.id?'border-[var(--accent-primary)] bg-[var(--accent-primary)]/10':'border-transparent hover:border-[var(--border-color)] hover:bg-[var(--bg-secondary)]'}`}><span className="block text-[10px] uppercase tracking-wider text-[var(--text-muted)]">Run {graphs.length-i}</span><span className={`block mt-1 text-sm truncate ${selected?.id===g.id?'text-[var(--accent-primary)]':'text-[var(--text-primary)]'}`}>{g.goal?.slice(0,70)||g.id}</span></button>)}</div></section>
    {selected&&<div className="rounded-xl border border-[var(--border-color)] bg-[var(--bg-secondary)] px-3 py-2 text-xs text-[var(--text-secondary)] flex items-center gap-2 md:hidden"><Workflow size={13}/><span>Tap a step below to inspect its recorded state, attempts, cost, and output.</span><ChevronRight size={13} className="ml-auto"/></div>}
    {selected&&<TaskGraphView graph={selected} attempts={attempts} onRefresh={refresh} onResume={resume} resuming={resuming}/>}<div className="flex justify-end"><button type="button" onClick={()=>void refresh()} className="btn btn-secondary flex items-center gap-2 text-sm"><RefreshCw size={14}/> Refresh history</button></div>
  </>}
 </div>;
}
