'use client';
import { useCallback, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowRight, RefreshCw, Workflow } from 'lucide-react';
import TaskGraphView from '@/components/graph/TaskGraphView';
import { getGraph,getGraphAttempts,getGraphs,resumeGraph } from '@/lib/graph-api';

export default function GraphsPage(){
 const [graphs,setGraphs]=useState<any[]>([]); const [selected,setSelected]=useState<any>(null); const [attempts,setAttempts]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [resuming,setResuming]=useState(false);
 const selectGraph=useCallback(async(id:string)=>{const [g,a]=await Promise.all([getGraph(id),getGraphAttempts(id)]);setSelected(g.graph);setAttempts(a.attempts||[]);},[]);
 const refresh=useCallback(async()=>{setError('');try{const r=await getGraphs();setGraphs(r.graphs||[]);if(selected?.id)await selectGraph(selected.id);else if(r.graphs?.[0])await selectGraph(r.graphs[0].id);}catch(e:any){setError(e.message||'Unable to refresh graphs');}},[selected?.id,selectGraph]);
 const resume=async()=>{if(!selected)return;setResuming(true);setError('');try{await resumeGraph(selected.id);await selectGraph(selected.id);await refresh();}catch(e:any){setError(e.message||'Unable to resume graph');}finally{setResuming(false)}};
 useEffect(()=>{refresh().finally(()=>setLoading(false));},[]);
 useEffect(()=>{if(!selected?.id||!['running','awaiting-runtime','awaiting-approval'].includes(selected.status))return;const timer=setInterval(()=>{selectGraph(selected.id).catch(()=>undefined)},5000);return()=>clearInterval(timer)},[selected?.id,selected?.status,selectGraph]);
 return <div className="space-y-6 pb-10"><header className="flex flex-col sm:flex-row sm:items-end justify-between gap-4"><div><div className="flex items-center gap-2 text-sm text-[var(--accent-primary)]"><Workflow size={16}/> Durable work</div><h1 className="text-2xl md:text-3xl font-semibold text-[var(--text-primary)] mt-2">Execution graphs</h1><p className="text-sm text-[var(--text-secondary)] mt-1 max-w-2xl">See how Uden decomposed the work, what each step is doing, and where human attention is required.</p></div><Link href="/tasks/new" className="btn btn-primary flex items-center gap-2 self-start sm:self-auto">New work <ArrowRight size={15}/></Link></header>{error&&<div role="alert" className="glass-card p-4 border border-[var(--status-danger)]/30 text-sm text-[var(--status-danger)]">{error}</div>}{loading?<div className="glass-card p-8 text-[var(--text-secondary)]">Loading execution history…</div>:graphs.length===0?<div className="glass-card p-10 text-center"><Workflow className="mx-auto mb-3 text-[var(--text-muted)]"/><p className="font-medium text-[var(--text-primary)]">No execution graphs yet</p><p className="text-sm text-[var(--text-secondary)] mt-2">Start a piece of work and its durable execution trail will appear here.</p><Link href="/tasks/new" className="btn btn-primary inline-flex mt-5">Start work</Link></div>:<><div className="flex gap-2 overflow-x-auto pb-1" aria-label="Execution graph history">{graphs.map(g=><button key={g.id} onClick={()=>selectGraph(g.id)} className={`max-w-[320px] px-4 py-2.5 rounded-lg border text-sm whitespace-nowrap truncate transition-colors ${selected?.id===g.id?'border-[var(--accent-primary)] bg-[var(--accent-primary)]/10 text-[var(--accent-primary)]':'border-[var(--border-color)] text-[var(--text-secondary)] hover:text-[var(--text-primary)] hover:border-[var(--accent-primary)]'}`}>{g.goal?.slice(0,55)||g.id}</button>)}</div>{selected&&<TaskGraphView graph={selected} attempts={attempts} onRefresh={refresh} onResume={resume} resuming={resuming}/>}<div className="flex justify-end"><button type="button" onClick={()=>void refresh()} className="btn btn-secondary flex items-center gap-2 text-sm"><RefreshCw size={14}/> Refresh history</button></div></>}</div>;
}
