import { Hono } from 'hono';
import type { HonoEnv } from '../types';
import { createGitHubAuthorizationUrl, completeGitHubAuthorization, disconnectGitHub, listGitHubRepositories, getGitHubTree, getGitHubTreeBySha, getGitHubFile, getGitHubBlob, getGitHubCommit, getGitHubGitCommit, getGitHubRef, listGitHubCommits, searchGitHubCode, listGitHubPulls, getGitHubPull, getGitHubPullDiff, listGitHubActionsRuns, createGitHubBranch, commitGitHubFiles, createGitHubPull, mergeGitHubPull } from '../services/github-connector';
import { requirePermission, writeAudit } from '../services/permissions';
import { sanitizeError } from '../services/observability';

export const githubRoutes = new Hono<HonoEnv>();
const status = (message: string) => message === 'Forbidden' ? 403 : 502;
const repoParams = (c: any) => ({ owner: c.req.param('owner'), repo: c.req.param('repo') });

// Direct provider writes are intentionally disabled here. Authenticated user
// access must not become a second side-effect path around durable graph
// authorization, fencing, idempotency and reconciliation. Writes go through
// repository-operation-executor instead.
githubRoutes.use('/repos/:owner/:repo/*', async (c,next) => {
  if (['POST','PUT','PATCH','DELETE'].includes(c.req.method)) return c.json({error:'Direct GitHub mutations must execute through a durable graph repository operation'},409);
  await next();
});

 githubRoutes.get('/connect', async c => { try { await requirePermission(c.env.DB, c.get('tenantId'), 'settings:write'); return c.json({ authorizationUrl: await createGitHubAuthorizationUrl(c.env, c.get('tenantId')) }); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, message === 'Forbidden' ? 403 : 503); } });
githubRoutes.get('/callback', async c => { try { const code = c.req.query('code'); const state = c.req.query('state'); if (c.req.query('error')) return c.json({ error: 'GitHub authorization was denied' }, 400); if (!code || !state) return c.json({ error: 'Missing OAuth callback parameters' }, 400); const result = await completeGitHubAuthorization(c.env, code, state); await writeAudit(c.env.DB, result.tenantId, 'github.connect', 'github_connection', undefined, 'github-oauth', undefined, { login: result.login }); return c.json({ connected: true, login: result.login }); } catch (error) { return c.json({ error: sanitizeError(error) }, 400); } });
githubRoutes.delete('/connection', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'settings:write'); await disconnectGitHub(c.env, tenantId); await writeAudit(c.env.DB, tenantId, 'github.disconnect', 'github_connection', undefined, undefined, c.get('requestId')); return c.json({ disconnected: true }); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); return c.json({ repositories: await listGitHubRepositories(c.env, tenantId) }); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/tree', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await getGitHubTree(c.env, tenantId, owner, repo, c.req.query('ref'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/tree/:sha', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await getGitHubTreeBySha(c.env, tenantId, owner, repo, c.req.param('sha'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/file/*', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); const path = c.req.path.split('/file/')[1] || ''; return c.json(await getGitHubFile(c.env, tenantId, owner, repo, decodeURIComponent(path), c.req.query('ref'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/blob/:sha', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await getGitHubBlob(c.env, tenantId, owner, repo, c.req.param('sha'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/commits/:sha', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await getGitHubCommit(c.env, tenantId, owner, repo, c.req.param('sha'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/git/commits/:sha', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await getGitHubGitCommit(c.env, tenantId, owner, repo, c.req.param('sha'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/git/ref/*', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); const ref = c.req.path.split('/git/ref/')[1] || ''; return c.json(await getGitHubRef(c.env, tenantId, owner, repo, decodeURIComponent(ref))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/commits', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await listGitHubCommits(c.env, tenantId, owner, repo, c.req.query('ref'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/code/search', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); return c.json(await searchGitHubCode(c.env, tenantId, c.req.query('q') || '', c.req.query('owner'), c.req.query('repo'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/pulls', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await listGitHubPulls(c.env, tenantId, owner, repo, c.req.query('state') || 'open')); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/pulls/:number', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await getGitHubPull(c.env, tenantId, owner, repo, Number(c.req.param('number')))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/pulls/:number/diff', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.text(await getGitHubPullDiff(c.env, tenantId, owner, repo, Number(c.req.param('number')))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/actions/runs', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await listGitHubActionsRuns(c.env, tenantId, owner, repo, c.req.query('branch'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });

githubRoutes.post('/repos/:owner/:repo/branches', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:write'); const { owner, repo } = repoParams(c); const body = await c.req.json() as { branch?: string; fromSha?: string }; if (!body.branch || !body.fromSha) return c.json({ error: 'branch and fromSha are required' }, 400); const result = await createGitHubBranch(c.env, tenantId, owner, repo, body.branch, body.fromSha); await writeAudit(c.env.DB, tenantId, 'github.branch.create', 'github_branch', `${owner}/${repo}:${body.branch}`, c.get('executionPrincipal'), c.get('requestId')); return c.json(result, 201); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.post('/repos/:owner/:repo/commits', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:write'); const { owner, repo } = repoParams(c); const body = await c.req.json() as { branch?: string; expectedHeadSha?: string; message?: string; files?: unknown[] }; if (!body.branch || !body.expectedHeadSha || !body.message || !Array.isArray(body.files)) return c.json({ error: 'branch, expectedHeadSha, message and files are required' }, 400); const result = await commitGitHubFiles(c.env, tenantId, owner, repo, body.branch, body.expectedHeadSha, body.message, body.files as Parameters<typeof commitGitHubFiles>[7]); await writeAudit(c.env.DB, tenantId, 'github.commit.create', 'github_commit', `${owner}/${repo}:${body.branch}`, c.get('executionPrincipal'), c.get('requestId')); return c.json(result, 201); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.post('/repos/:owner/:repo/pulls', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:write'); const { owner, repo } = repoParams(c); const body = await c.req.json() as { head?: string; base?: string; title?: string; body?: string; draft?: boolean }; if (!body.head || !body.base || !body.title) return c.json({ error: 'head, base and title are required' }, 400); const result = await createGitHubPull(c.env, tenantId, owner, repo, body.head, body.base, body.title, body.body, body.draft === true); await writeAudit(c.env.DB, tenantId, 'github.pull.create', 'github_pull_request', `${owner}/${repo}:${body.head}`, c.get('executionPrincipal'), c.get('requestId')); return c.json(result, 201); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.post('/repos/:owner/:repo/pulls/:number/merge', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:write'); const { owner, repo } = repoParams(c); const number = Number(c.req.param('number')); const body = await c.req.json() as { expectedHeadSha?: string; method?: 'merge' | 'squash' | 'rebase' }; if (!body.expectedHeadSha) return c.json({ error: 'expectedHeadSha is required' }, 400); const result = await mergeGitHubPull(c.env, tenantId, owner, repo, number, body.expectedHeadSha, body.method || 'squash'); await writeAudit(c.env.DB, tenantId, 'github.pull.merge', 'github_pull_request', `${owner}/${repo}:${number}`, c.get('executionPrincipal'), c.get('requestId'), { expectedHeadSha: body.expectedHeadSha }); return c.json(result); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
