import { Hono } from 'hono';
import type { HonoEnv } from '../types';
import { createGitHubAuthorizationUrl, completeGitHubAuthorization, disconnectGitHub, listGitHubRepositories, getGitHubTree, getGitHubTreeBySha, getGitHubFile, getGitHubBlob, getGitHubCommit, getGitHubGitCommit, getGitHubRef, listGitHubCommits, searchGitHubCode, listGitHubPulls, getGitHubPull, getGitHubPullDiff, listGitHubActionsRuns } from '../services/github-connector';
import { requirePermission, writeAudit } from '../services/permissions';
import { sanitizeError } from '../services/observability';

export const githubRoutes = new Hono<HonoEnv>();
const status = (message: string) => message === 'Forbidden' ? 403 : 502;
const repoParams = (c: any) => ({ owner: c.req.param('owner'), repo: c.req.param('repo') });

 githubRoutes.get('/connect', async c => { try { await requirePermission(c.env.DB, c.get('tenantId'), 'settings:write'); return c.json({ authorizationUrl: await createGitHubAuthorizationUrl(c.env, c.get('tenantId')) }); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, message === 'Forbidden' ? 403 : 503); } });
githubRoutes.get('/callback', async c => { try { const code = c.req.query('code'); const state = c.req.query('state'); if (c.req.query('error')) return c.json({ error: 'GitHub authorization was denied' }, 400); if (!code || !state) return c.json({ error: 'Missing OAuth callback parameters' }, 400); const result = await completeGitHubAuthorization(c.env, code, state); await writeAudit(c.env.DB, result.tenantId, 'github.connect', 'github_connection', undefined, 'github-oauth', undefined, { login: result.login }); return c.json({ connected: true, login: result.login }); } catch (error) { return c.json({ error: sanitizeError(error) }, 400); } });
githubRoutes.delete('/connection', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'settings:write'); await disconnectGitHub(c.env, tenantId); await writeAudit(c.env.DB, tenantId, 'github.disconnect', 'github_connection', undefined, undefined, c.get('requestId')); return c.json({ disconnected: true }); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); return c.json({ repositories: await listGitHubRepositories(c.env, tenantId) }); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/tree', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await getGitHubTree(c.env, tenantId, owner, repo, c.req.query('ref'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/tree/:sha', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await getGitHubTreeBySha(c.env, tenantId, owner, repo, c.req.param('sha'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/file/*', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); const path = c.req.path.split('/file/')[1] || ''; return c.json(await getGitHubFile(c.env, tenantId, owner, repo, decodeURIComponent(path), c.req.query('ref'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/blob/:sha', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await getGitHubBlob(c.env, tenantId, owner, repo, c.req.param('sha'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/commits/:sha', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await getGitHubCommit(c.env, tenantId, owner, repo, c.req.param('sha'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/git/commits/:sha', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await getGitHubGitCommit(c.env, tenantId, owner, repo, c.req.param('sha'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/git/ref/*', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); const ref = c.req.path.split('/git/ref/')[1] || ''; return c.json(await getGitHubRef(c.env, tenantId, owner, repo, decodeURIComponent(ref))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/commits', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await listGitHubCommits(c.env, tenantId, owner, repo, c.req.query('ref'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/code/search', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); return c.json(await searchGitHubCode(c.env, tenantId, c.req.query('q') || '', c.req.query('owner'), c.req.query('repo'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/pulls', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await listGitHubPulls(c.env, tenantId, owner, repo, c.req.query('state') || 'open')); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/pulls/:number', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await getGitHubPull(c.env, tenantId, owner, repo, Number(c.req.param('number')))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/pulls/:number/diff', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.text(await getGitHubPullDiff(c.env, tenantId, owner, repo, Number(c.req.param('number')))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
githubRoutes.get('/repos/:owner/:repo/actions/runs', async c => { const tenantId = c.get('tenantId'); try { await requirePermission(c.env.DB, tenantId, 'github:read'); const { owner, repo } = repoParams(c); return c.json(await listGitHubActionsRuns(c.env, tenantId, owner, repo, c.req.query('branch'))); } catch (error) { const message = sanitizeError(error); return c.json({ error: message }, status(message)); } });
