import { Hono } from 'hono';
import type { HonoEnv } from '../types';
import { requirePermission, writeAudit } from '../services/permissions';
import { sanitizeError } from '../services/observability';
import { createOriginInstallUrl, completeOriginInstall, disconnectOrigin, listOriginRepositories, getOriginRepository, listOriginBranches, listOriginCommits, getOriginCommit, getOriginBlob, getOriginGitCommit, getOriginTree, listOriginPulls, getOriginPull, getOriginPullFiles, compareOriginCommits } from '../services/origin-connector';

export const originRoutes = new Hono<HonoEnv>();
const code=(message:string)=>message==='Forbidden'?403:502;
const params=(c:any)=>({owner:c.req.param('owner'),repo:c.req.param('repo')});

originRoutes.get('/connect',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'settings:write');return c.json({authorizationUrl:await createOriginInstallUrl(c.env,c.get('tenantId'))});}catch(error){const message=sanitizeError(error);return c.json({error:message},message==='Forbidden'?403:503);}});
originRoutes.get('/callback',async c=>{try{const receipt=c.req.query('installation_receipt');if(!receipt)return c.json({error:'Missing Origin installation receipt'},400);const result=await completeOriginInstall(c.env,c.get('tenantId'),receipt);await writeAudit(c.env.DB,c.get('tenantId'),'origin.connect','origin_connection',result.installationId,'origin-app',c.get('requestId'));return c.json({connected:true,...result});}catch(error){return c.json({error:sanitizeError(error)},400);}});
originRoutes.delete('/connection',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'settings:write');await disconnectOrigin(c.env,c.get('tenantId'));await writeAudit(c.env.DB,c.get('tenantId'),'origin.disconnect','origin_connection',undefined,undefined,c.get('requestId'));return c.json({disconnected:true});}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'github:read');return c.json(await listOriginRepositories(c.env,c.get('tenantId')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'github:read');const {owner,repo}=params(c);return c.json(await getOriginRepository(c.env,c.get('tenantId'),owner,repo));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/branches',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'github:read');const {owner,repo}=params(c);return c.json(await listOriginBranches(c.env,c.get('tenantId'),owner,repo));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/commits',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'github:read');const {owner,repo}=params(c);return c.json(await listOriginCommits(c.env,c.get('tenantId'),owner,repo,c.req.query('sha')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/commits/:sha',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'github:read');const {owner,repo}=params(c);return c.json(await getOriginCommit(c.env,c.get('tenantId'),owner,repo,c.req.param('sha')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/git/blobs/:sha',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'github:read');const {owner,repo}=params(c);return c.json(await getOriginBlob(c.env,c.get('tenantId'),owner,repo,c.req.param('sha')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/git/commits/:sha',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'github:read');const {owner,repo}=params(c);return c.json(await getOriginGitCommit(c.env,c.get('tenantId'),owner,repo,c.req.param('sha')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/git/trees/:sha',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'github:read');const {owner,repo}=params(c);return c.json(await getOriginTree(c.env,c.get('tenantId'),owner,repo,c.req.param('sha')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/pulls',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'github:read');const {owner,repo}=params(c);return c.json(await listOriginPulls(c.env,c.get('tenantId'),owner,repo,c.req.query('state')||'open'));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/pulls/:number',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'github:read');const {owner,repo}=params(c);return c.json(await getOriginPull(c.env,c.get('tenantId'),owner,repo,c.req.param('number')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/pulls/:number/files',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'github:read');const {owner,repo}=params(c);return c.json(await getOriginPullFiles(c.env,c.get('tenantId'),owner,repo,c.req.param('number')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/compare/:basehead',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'github:read');const {owner,repo}=params(c);return c.json(await compareOriginCommits(c.env,c.get('tenantId'),owner,repo,c.req.param('basehead')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
