import { Hono } from 'hono';
import type { HonoEnv } from '../types';
import { requirePermission, writeAudit } from '../services/permissions';
import { sanitizeError } from '../services/observability';
import { createOriginInstallUrl, completeOriginInstall, disconnectOrigin, listOriginRepositories, getOriginRepository, listOriginBranches, listOriginCommits, getOriginCommit, getOriginBlob, getOriginGitCommit, getOriginTree, listOriginPulls, getOriginPull, getOriginPullFiles, compareOriginCommits, createOriginBranch, commitOriginFiles, createOriginPull, mergeOriginPull } from '../services/origin-connector';

export const originRoutes = new Hono<HonoEnv>();
export const originCallbackRoutes = new Hono<HonoEnv>();
const code=(message:string)=>message==='Forbidden'?403:502;
const params=(c:any)=>({owner:c.req.param('owner'),repo:c.req.param('repo')});

originRoutes.get('/connect',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'settings:write');return c.json({authorizationUrl:await createOriginInstallUrl(c.env,c.get('tenantId'))});}catch(error){const message=sanitizeError(error);return c.json({error:message},message==='Forbidden'?403:503);}});
originCallbackRoutes.get('/',async c=>{try{const receipt=c.req.query('installation_receipt');if(!receipt)return c.json({error:'Missing Origin installation receipt'},400);const result=await completeOriginInstall(c.env,receipt);await writeAudit(c.env.DB,result.tenantId,'origin.connect','origin_connection',result.installationId,'origin-installation',undefined);return c.json({connected:true,installationId:result.installationId,namespaceId:result.namespaceId});}catch(error){return c.json({error:sanitizeError(error)},400);}});
originRoutes.delete('/connection',async c=>{try{const tenantId=c.get('tenantId');await requirePermission(c.env.DB,tenantId,'settings:write');await disconnectOrigin(c.env,tenantId);await writeAudit(c.env.DB,tenantId,'origin.disconnect','origin_connection',undefined,c.get('executionPrincipal'),c.get('requestId'));return c.json({disconnected:true});}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'origin:read');return c.json(await listOriginRepositories(c.env,c.get('tenantId')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'origin:read');const {owner,repo}=params(c);return c.json(await getOriginRepository(c.env,c.get('tenantId'),owner,repo));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/branches',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'origin:read');const {owner,repo}=params(c);return c.json(await listOriginBranches(c.env,c.get('tenantId'),owner,repo));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/commits',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'origin:read');const {owner,repo}=params(c);return c.json(await listOriginCommits(c.env,c.get('tenantId'),owner,repo,c.req.query('sha')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/commits/:sha',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'origin:read');const {owner,repo}=params(c);return c.json(await getOriginCommit(c.env,c.get('tenantId'),owner,repo,c.req.param('sha')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/git/blobs/:sha',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'origin:read');const {owner,repo}=params(c);return c.json(await getOriginBlob(c.env,c.get('tenantId'),owner,repo,c.req.param('sha')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/git/commits/:sha',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'origin:read');const {owner,repo}=params(c);return c.json(await getOriginGitCommit(c.env,c.get('tenantId'),owner,repo,c.req.param('sha')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/git/trees/:sha',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'origin:read');const {owner,repo}=params(c);return c.json(await getOriginTree(c.env,c.get('tenantId'),owner,repo,c.req.param('sha')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/pulls',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'origin:read');const {owner,repo}=params(c);return c.json(await listOriginPulls(c.env,c.get('tenantId'),owner,repo,c.req.query('state')||'open'));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/pulls/:number',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'origin:read');const {owner,repo}=params(c);return c.json(await getOriginPull(c.env,c.get('tenantId'),owner,repo,c.req.param('number')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/pulls/:number/files',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'origin:read');const {owner,repo}=params(c);return c.json(await getOriginPullFiles(c.env,c.get('tenantId'),owner,repo,c.req.param('number')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.get('/repos/:owner/:repo/compare/:basehead',async c=>{try{await requirePermission(c.env.DB,c.get('tenantId'),'origin:read');const {owner,repo}=params(c);return c.json(await compareOriginCommits(c.env,c.get('tenantId'),owner,repo,c.req.param('basehead')));}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});

originRoutes.post('/repos/:owner/:repo/branches',async c=>{try{const tenantId=c.get('tenantId');await requirePermission(c.env.DB,tenantId,'origin:write');const {owner,repo}=params(c);const body=await c.req.json() as {branch?:string;fromSha?:string};if(!body.branch||!body.fromSha)return c.json({error:'branch and fromSha are required'},400);const result=await createOriginBranch(c.env,tenantId,owner,repo,body.branch,body.fromSha);await writeAudit(c.env.DB,tenantId,'origin.branch.create','origin_branch',`${owner}/${repo}:${body.branch}`,c.get('executionPrincipal'),c.get('requestId'));return c.json(result,201);}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.post('/repos/:owner/:repo/commits',async c=>{try{const tenantId=c.get('tenantId');await requirePermission(c.env.DB,tenantId,'origin:write');const {owner,repo}=params(c);const body=await c.req.json() as {branch?:string;expectedHeadSha?:string;message?:string;files?:unknown[]};if(!body.branch||!body.expectedHeadSha||!body.message||!Array.isArray(body.files))return c.json({error:'branch, expectedHeadSha, message and files are required'},400);const result=await commitOriginFiles(c.env,tenantId,owner,repo,body.branch,body.expectedHeadSha,body.message,body.files as Parameters<typeof commitOriginFiles>[7]);await writeAudit(c.env.DB,tenantId,'origin.commit.create','origin_commit',`${owner}/${repo}:${body.branch}`,c.get('executionPrincipal'),c.get('requestId'));return c.json(result,201);}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.post('/repos/:owner/:repo/pulls',async c=>{try{const tenantId=c.get('tenantId');await requirePermission(c.env.DB,tenantId,'origin:write');const {owner,repo}=params(c);const body=await c.req.json() as {head?:string;base?:string;title?:string;body?:string};if(!body.head||!body.base||!body.title)return c.json({error:'head, base and title are required'},400);const result=await createOriginPull(c.env,tenantId,owner,repo,body.head,body.base,body.title,body.body);await writeAudit(c.env.DB,tenantId,'origin.pull.create','origin_pull_request',`${owner}/${repo}:${body.head}`,c.get('executionPrincipal'),c.get('requestId'));return c.json(result,201);}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
originRoutes.post('/repos/:owner/:repo/pulls/:number/merge',async c=>{try{const tenantId=c.get('tenantId');await requirePermission(c.env.DB,tenantId,'origin:write');const {owner,repo}=params(c);const body=await c.req.json() as {expectedHeadSha?:string};if(!body.expectedHeadSha)return c.json({error:'expectedHeadSha is required'},400);const result=await mergeOriginPull(c.env,tenantId,owner,repo,c.req.param('number'),body.expectedHeadSha);await writeAudit(c.env.DB,tenantId,'origin.pull.merge','origin_pull_request',`${owner}/${repo}:${c.req.param('number')}`,c.get('executionPrincipal'),c.get('requestId'),{expectedHeadSha:body.expectedHeadSha});return c.json(result);}catch(error){const message=sanitizeError(error);return c.json({error:message},code(message));}});
