import { Hono } from 'hono';
import { HonoEnv } from '../types';
import { executeTask, runTaskExecution } from '../services/executor';
import { createTaskGraph, decomposeTask } from '../services/task-graph';
import { executeTaskGraph, resumeTaskGraph } from '../services/graph-executor';
import { prepareBackgroundGraph, backgroundQueueMessage } from '../services/background-graph';
import { getPersistedGraph, listPersistedGraphs, listGraphAttempts } from '../services/graph-persistence';
import { requirePermission, writeAudit } from '../services/permissions';
import { getApprovalRequirement } from '../services/approval-gates';
import { sanitizeError } from '../services/observability';
import { listTasks, getTask, updateTask } from '../db/queries';

export const taskRoutes = new Hono<HonoEnv>();
const MAX_GRAPH_NODES = 100, MAX_GRAPH_GOAL = 20_000, MAX_NODE_PROMPT = 50_000, MAX_GRAPH_PAYLOAD = 500_000;
function validateGraphInput(plan: any): string | null { if (!plan || typeof plan !== 'object' || typeof plan.goal !== 'string' || !Array.isArray(plan.nodes)) return 'Invalid task graph plan'; if (!plan.goal.trim() || plan.goal.length > MAX_GRAPH_GOAL) return `Graph goal must be 1-${MAX_GRAPH_GOAL} characters`; if (plan.nodes.length === 0 || plan.nodes.length > MAX_GRAPH_NODES) return `Graph must contain 1-${MAX_GRAPH_NODES} nodes`; let size=0; for(const node of plan.nodes){ if(!node||typeof node!=='object'||typeof node.id!=='string'||typeof node.prompt!=='string') return 'Each graph node must have an id and prompt'; if(node.id.length>200) return 'Graph node id is too long'; if(node.prompt.length>MAX_NODE_PROMPT) return `Each node prompt must be at most ${MAX_NODE_PROMPT} characters`; if(!Array.isArray(node.dependencies)||!Array.isArray(node.contextFrom)) return `Node '${node.id}' has invalid dependency/context lists`; if(node.dependencies.length>MAX_GRAPH_NODES||node.contextFrom.length>MAX_GRAPH_NODES) return `Node '${node.id}' has too many relationships`; size+=node.prompt.length+node.id.length+JSON.stringify(node.dependencies).length+JSON.stringify(node.contextFrom).length; if(size>MAX_GRAPH_PAYLOAD)return `Graph payload exceeds ${MAX_GRAPH_PAYLOAD} characters`; } return null; }
function boundedInt(value:string|undefined,fallback:number,max:number){const parsed=Number.parseInt(value||'',10);return Number.isFinite(parsed)?Math.min(max,Math.max(0,parsed)):fallback;}

taskRoutes.post('/', async c => { const b=await c.req.json().catch(()=>({})); const t=c.get('tenantId'); if(!b.prompt||typeof b.prompt!=='string'||!b.prompt.trim())return c.json({error:'Prompt is required and must be a non-empty string'},400); try{return c.json(await executeTask(c.env,t,b.prompt,b.mode!=='permission-based'&&b.permissionless!==false,b.projectId),200);}catch(e){return c.json({error:sanitizeError(e)},500);} });
taskRoutes.post('/plan', async c => { const b=await c.req.json().catch(()=>({})); if(!b.prompt||typeof b.prompt!=='string'||!b.prompt.trim()||b.prompt.length>MAX_GRAPH_GOAL)return c.json({error:`Prompt is required and must be at most ${MAX_GRAPH_GOAL} characters`},400); const plan=decomposeTask(b.prompt.trim()); const validation=validateGraphInput(plan); if(validation)return c.json({error:validation},400); return c.json({plan,graph:createTaskGraph(crypto.randomUUID(),plan),approval:getApprovalRequirement(plan)},200); });

taskRoutes.post('/graph/execute', async c => { const b=await c.req.json().catch(()=>({})); const t=c.get('tenantId'); await requirePermission(c.env.DB,t,'graph:execute'); if(b.plan!==undefined&&(!b.plan||typeof b.plan!=='object'))return c.json({error:'plan must be an object when supplied'},400); if(!b.prompt&&!b.plan)return c.json({error:'Prompt or plan is required'},400); try{const plan=b.plan||decomposeTask(String(b.prompt).trim());const validation=validateGraphInput(plan);if(validation)return c.json({error:validation},400);const approval=getApprovalRequirement(plan);if(approval.required&&!b.approved){return c.json({error:'Human approval required before execution',approvalRequired:true,approval,retryWith:{approved:true}},428);}if(approval.required)await writeAudit(c.env.DB,t,'graph.approval','graph',undefined,undefined,c.get('requestId' as never) as string,{reasons:approval.reasons,nodes:approval.nodes});const result=await executeTaskGraph(c.env,t,plan,b.projectId);await writeAudit(c.env.DB,t,'graph.execute','graph',result.graph.id,undefined,c.get('requestId' as never) as string);return c.json(result,200);}catch(e){const message=sanitizeError(e);if(message==='Budget exhausted before node execution')return c.json({error:message},402);if(message==='Forbidden')return c.json({error:message},403);if(message.startsWith('Invalid graph:'))return c.json({error:message},400);return c.json({error:'Graph execution failed'},500);} });

taskRoutes.post('/graph/execute/background', async c => { const t=c.get('tenantId'); const principal=c.get('executionPrincipal'); await requirePermission(c.env.DB,t,'graph:execute'); const b=await c.req.json().catch(()=>({})); if(!c.env.TASK_GRAPH_QUEUE)return c.json({error:'Background execution is not configured'},503); if(b.plan!==undefined&&(!b.plan||typeof b.plan!=='object'))return c.json({error:'plan must be an object when supplied'},400);if(!b.prompt&&!b.plan)return c.json({error:'Prompt or plan is required'},400);try{const plan=b.plan||decomposeTask(String(b.prompt).trim());const validation=validateGraphInput(plan);if(validation)return c.json({error:validation},400);const approval=getApprovalRequirement(plan);if(approval.required&&!b.approved)return c.json({error:'Human approval required before background execution',approvalRequired:true,approval,retryWith:{approved:true}},428);const prepared=await prepareBackgroundGraph(c.env,t,plan,b.projectId,principal);await c.env.TASK_GRAPH_QUEUE.send(backgroundQueueMessage(t,prepared.graphId,principal),{contentType:'json'});await writeAudit(c.env.DB,t,'graph.queue','graph',prepared.graphId,undefined,c.get('requestId' as never) as string,{executionPrincipal:principal});return c.json({accepted:true,graphId:prepared.graphId,status:'queued'},202);}catch(e){return c.json({error:sanitizeError(e)},500);} });

taskRoutes.post('/graph/:id/resume', async c => { const t=c.get('tenantId'); try{await requirePermission(c.env.DB,t,'graph:resume');const result=await resumeTaskGraph(c.env,t,c.req.param('id'));await writeAudit(c.env.DB,t,'graph.resume','graph',c.req.param('id'),undefined,c.get('requestId' as never) as string);return c.json(result,200);}catch(e){const message=sanitizeError(e);if(message==='Graph not found')return c.json({error:message},404);if(message==='Graph is currently owned by another execution')return c.json({error:message},409);if(message==='Forbidden')return c.json({error:message},403);return c.json({error:'Graph resume failed'},500);} });

taskRoutes.get('/graphs', async c => {const t=c.get('tenantId');await requirePermission(c.env.DB,t,'graph:read');const limit=boundedInt(c.req.query('limit'),50,100)||1;const offset=boundedInt(c.req.query('offset'),0,1_000_000);return c.json({graphs:await listPersistedGraphs(c.env.DB,t,limit,offset)},200);});
taskRoutes.get('/graph/:id', async c => {await requirePermission(c.env.DB,c.get('tenantId'),'graph:read');const graph=await getPersistedGraph(c.env.DB,c.get('tenantId'),c.req.param('id'));return graph?c.json({graph},200):c.json({error:'Graph not found'},404);});
taskRoutes.get('/graph/:id/attempts', async c => {await requirePermission(c.env.DB,c.get('tenantId'),'graph:read');return c.json({attempts:await listGraphAttempts(c.env.DB,c.get('tenantId'),c.req.param('id'),c.req.query('nodeId'))},200);});
taskRoutes.get('/', async c => {const t=c.get('tenantId');const limit=boundedInt(c.req.query('limit'),50,100)||1;const offset=boundedInt(c.req.query('offset'),0,1_000_000);return c.json({tasks:await listTasks(c.env.DB,t,limit,offset)});});
taskRoutes.get('/:id', async c => {const task=await getTask(c.env.DB,c.req.param('id'),c.get('tenantId'));return task?c.json({task},200):c.json({error:'Not found'},404);});
taskRoutes.post('/:id/approve', async c => {const t=c.get('tenantId'),id=c.req.param('id'),b=await c.req.json().catch(()=>({}));await requirePermission(c.env.DB,t,'graph:execute');const task=await getTask(c.env.DB,id,t);if(!task)return c.json({error:'Not found'},404);if(task.status!=='awaiting-approval')return c.json({error:`Task status is '${task.status}', cannot approve`},400);await updateTask(c.env.DB,id,t,{status:'processing'});try{await writeAudit(c.env.DB,t,'task.approve','task',id,undefined,c.get('requestId' as never) as string);return c.json(await runTaskExecution(c.env,task,b.primaryModel||task.routingPlan?.primaryModel||task.proposal?.suggestedModel||'gpt-4o-mini',b.fallbackChain||task.routingPlan?.fallbackChain||[],b.expectedFormat||'markdown'),200);}catch(e){return c.json({error:sanitizeError(e)},500);}});
